app/config/locale/templates/en.email.auth.invitation.tpl
Corrected grammar and flow of sentence in EN Email Template.
=> Correct grammar in EN Email Template

app/views/console/database/collection.phtml, app/views/console/users/index.phtml, app/views/general/error.phtml, app/views/layouts/default.phtml, app/views/proxy.phtml
=> Fix code style in views

docs/AddOAuthProvider.md
=> Fix typos and grammar in AddOAuthProvider.md

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
fixed typos and grammar in the following files:
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
My small contribution to appwrite ;)
=> Fixed Grammar and Typo

CONTRIBUTING.md
=> editing grammar

app/config/locale/id.php
I forget to translate the inspirational quote.
Related to #25
=> id: translate inspirational quote

app/config/locale/no.php
- Added `no.php` file in `app/config/locale/` with Norwegian translation
=> Add Norwegian translation

README.md
- Grammar changes.
- Spelling mistakes changes.
=> Typo-changes

app/config/locale/hi.php
Updated the data for clarity in meanings and add translation for untranslated data
=> Updated the locale for Hindi Language

app/config/locale/templates/pt-br.email.auth.confirm.tpl, app/config/locale/templates/pt-br.email.auth.invitation.tpl, app/config/locale/templates/pt-br.email.auth.recovery.tpl
- Adjusted confirm, invitation and recovery PT-BR emails (issue #25 )
=> adjusting the PT-BR translation for a more appropriate speech (issue #25)

README.md
Added a badge so people can be notified when appwrite releases new versions and awesome features.
=> Add follow new releases badge

app/config/locale/templates/de.email.auth.confirm.tpl, app/config/locale/templates/de.email.auth.invitation.tpl, app/config/locale/templates/de.email.auth.recovery.tpl
I've found some typos in the german translation, this PR will fix them 🙂
=> Fix typos in german translation of template files

CONTRIBUTING.md, docs/AddOAuthProvider.md, docs/EnvironmentVariables.md
Hi there,
As I was reading through Appwrite's documentation and guidelines, I noticed some edits that I wanted to make, so I decided to submit this Pull Request. 
I have updated Appwrite's documentation and contributor guidelines by making grammar edits in the contributor guidelines particularly, and edited the phrasing of some sentences for enhanced readability. 
Hopefully this helps!
=> Updated documentation and contributor guidelines.

app/config/locale/templates/pt-pt.email.auth.invitation.tpl
This PR fixes some typos in the pt-pt translation template.
=> Fix typos on pt-pt translation template

app/config/locale/templates/pt-br.email.auth.confirm.tpl, app/config/locale/templates/pt-br.email.auth.invitation.tpl, app/config/locale/templates/pt-br.email.auth.recovery.tpl
=> Fix PT-BR Typo

README.md
=> grammatical errors - possessive

app/config/locale/sv.php
I came here to fix a typo while reviewing my PR, but that's already fixed :tada: so I got busy reviewing some other stuff, and realized people are translating that inspirational quote, so here goes, a Swedish translation using a fairly hard to learn native word "förbise" :tada:
=> Add an inspirational quote for the Swedish translation.

docs/tutorials/environment-variables.md
=> fixed typos

app/config/locale/fr.continents.php, app/config/locale/it.php
Made some modifications in italian and french translation
=> Made some modifications in italian and french translation

README.md
Made the readme more concise by modifying "easy to use" to "easy-to-use".
=> Changed easy to use to easy-to-use

README.md
Just thought these corrections will make the README.md file a bit more neat. Please merge this if it is helpful.
=> Minor corrections in README.md file

README.md
I've added Stargazers count and Follow on Twitter Badges.
=> Adding Stargazers and Follow on Twitter Badges

public/styles/scopes/console.less
=> hide scrollbar if not needed in menu

docs/tutorials/environment-variables.md
update description of _APP_CONSOLE_WHITELIST_IPS behavior
=> update description of behavior

app/config/languages.php, app/controllers/api/locale.php, docs/references/locale/get-currencies.md, docs/references/locale/get-languages.md, tests/e2e/Services/Locale/LocaleBase.php
- list all languages classified by ISO 639-1
- possible features
- add a "common" property to sort out mostly unknown languages and display only the most common ones
#351
=> [API] Locale - List languages - ISO 639-1

CHANGES.md, Dockerfile, docker/nginx.conf
=> Brotli support

app/app.php, app/controllers/api/account.php, app/controllers/api/teams.php, app/workers/mails.php, docker/supervisord.conf, tests/e2e/Scopes/Scope.php, tests/e2e/Services/Account/AccountBase.php, tests/e2e/Services/Teams/TeamsBaseClient.php
To speed up endpoints in which an email is sent, this PR adds a background worker which allows asynchronous sending of emails.
=> [Feature] Mail background worker

app/config/locales/templates/pt-br.email.auth.recovery.tpl
=> Fix pt-br email auth recover

CHANGES.md, app/views/console/users/index.phtml
=> Oauth grid

composer.json
=> Replaced Redis Resque Library

app/workers/certificates.php
Fixes #408 
Got tested in prod env, obtaining and using the certificate worked.
=> Add system email to certification obtaining

Dockerfile, bin/start, docker-compose.yml, docker/nginx.conf.template
=> Dynamic Nginx max request size from ENV var

app/controllers/api/projects.php, app/views/console/settings/index.phtml, src/Appwrite/Network/Validator/Domain.php, tests/unit/Network/Validators/DomianTest.php
=> Custom domain validation regex is invalid

tests/unit/Network/Validators/DomainTest.php
I've made a sync with the upstream and noticed some typo.
So here is a quick fix to correct the filename from DomianTest.php to DomainTest.php ;)
=> Corrected filename from DomianTest.php to DomainTest.php

app/config/collections.php, app/controllers/api/users.php, app/workers/deletes.php, docs/references/users/delete-user.md, src/Appwrite/Database/Adapter.php, src/Appwrite/Database/Adapter/MySQL.php, src/Appwrite/Database/Adapter/Redis.php, src/Appwrite/Database/Database.php, tests/e2e/Services/Users/UsersBase.php
First draft of the feature #378.
Following things will be added after first review:
- take advantage of the delete worker
- write tests
- write documentation
=> Delete user endpoint

app/controllers/api/storage.php, src/Appwrite/Resize/Resize.php
This PR contains the implementation of #271
=> Added a few more image preview features

CONTRIBUTING.md, README.md
* 10 spelling and grammar corrections in CONTRIBUTIONS.md
* Fixed numbering in ordered list (5 was missing)
* fixed colon spacing and missing commas
=> Fixed grammar and numbering in CONTRIBUTING.md and README

docs/tutorials/running-in-production.md
Fixed some grammar and typo mistakes such as trough and 3rrd.
=> Updated running-in-production.md

CHANGES.md, README.md, SECURITY.md
Added at before the email address as its more grammatically correct
=> Typo Fixes + Fixing Grammatical errors

app/config/locale/translations/templates/en.email.auth.invitation.tpl, app/config/locale/translations/templates/en.email.auth.recovery.tpl
Improve the invitation template to make it more readable and less confusing.
Fix the recovery template.
=> Refactor templates for EN locale

app/config/locale/translations/templates/cz.email.auth.confirm.tpl, app/config/locale/translations/templates/cz.email.auth.invitation.tpl
Improve the translation to make it more readable and less confusing.
=> Refactor templates for CZ locale

Dockerfile
Upgraded Swoole version
Leverage Appwrite existing tests suite
=> Swoole version upgrade

app/config/locale/translations/it.countries.php
Added missing translation for `Jordan` -> `Giordania`
Added missing translation for `Jordan` -> `Giordania`
yes.
=> Added missing translation (italian)

app/controllers/api/avatars.php, app/controllers/api/database.php, app/controllers/api/health.php, app/tasks/migrate.php, app/views/console/database/collection.phtml, app/views/console/database/document.phtml, app/views/console/database/form.phtml, app/views/console/database/rules/documentId.phtml, app/views/console/database/search/documents.phtml, app/views/console/users/index.phtml, app/workers/certificates.php, app/workers/tasks.php, app/workers/webhooks.php, composer.lock, tests/e2e/Client.php, tests/e2e/Services/Account/AccountBase.php, tests/e2e/Services/Functions/FunctionsBase.php, tests/e2e/Services/Functions/FunctionsCustomServerTest.php, tests/e2e/Services/Projects/ProjectsConsoleClientTest.php, tests/e2e/Services/Teams/TeamsBase.php, tests/e2e/Services/Teams/TeamsBaseClient.php, tests/e2e/Services/Teams/TeamsBaseServer.php
Replace a lot isset statements with the PHP7 Null coalescing operator to make syntax more clear.
Leverage Appwrite existing tests to make sure nothing breaks.
=> Refactor coalescing operator

.travis.yml, Dockerfile, app/cli.php, app/tasks/vars.php, bin/vars, build.sh
Adds a new Appwrite command line feature to debug currently set env vars inside the Appwrite container.
Added a new test inside the travis CI file.
=> Added vars debugger

app/controllers/api/locale.php
Removed hard-coded IP address when in dev mode.
Should work the same.
=> Removde hard-coded IP

app/init.php
Added a few extra setting to insure a persistent Redis connection.
Leverage existing test suit.
None
None
=> Fix for redis persistent connection

app/preload.php
Fixed minor log errors when trying to preload dev libraries on production builds.
Rely on existing tests suit.
None
Yes
=> Fix preloader broken dev paths

Dockerfile, app/controllers/api/account.php, app/controllers/api/locale.php, app/controllers/api/users.php, app/init.php, composer.json, composer.lock
Replaces current geoip2 mmdb reader with [maxmind reader](https://github.com/maxmind/MaxMind-DB-Reader-php) along with [native C extension](https://github.com/maxmind/libmaxminddb) which is noticeably faster.
Compatible with previous test cases
#474 
Yes
I had to add a block from lines 142 to 153 in Dockerfile (which is already repeated at line 22 to 33 and 107 to 127) otherwise I was getting error no autoconf, no compiler found, etc, anything wrong here?
In line 46 Dockerfile, according to libmaxmindb docs, `ldconfig` should be run but in alpine `ldconfig` needs to be run with config directory(https://stackoverflow.com/questions/36990951/ldconfig-seems-no-functional-under-alpine-3-3), is that correct path on that line?
In line 164 Dockerfile, is that path correct to load extension for …
=> Replace .mmdb reader with maxmind and native C extension

app/config/locale/translations/es.php, app/config/locale/translations/templates/es.email.auth.invitation.tpl, app/config/locale/translations/templates/es.email.auth.recovery.tpl
This PR is fixing some minor spell/typos errors I found in the Spanish translations.
It helps to [#25](https://github.com/appwrite/appwrite/issues/25)
=> Spanish translations revisition

Dockerfile, app/controllers/api/account.php, app/controllers/api/locale.php, app/controllers/api/users.php, composer.json, composer.lock, src/Appwrite/Extend/PDO.php, tests/unit/General/ExtensionsTest.php
Adds tests to check core extensions have been loaded properly. Usually we would use composer to check this, but with multistage Docker image we are installing dependencies independently from the environment.
Added a new general unit test suite.
=> Feat extensions tests

Dockerfile, build.sh, composer.json
Upgraded Swoole PHP extension version to 4.5.6
Current test should do the trick.
None
Yes.
=> Upgraded to Swoole 4.5.6

Dockerfile
Installing phpredis with git instead of wget + tar. Reduces build time.
Using current tests.
None
Yes
=> Feat install phpredis with git

docs/references/avatars/get-favicon.md
doc-fixing typos
Fixes typo to the documentation
Yes, I have
=> doc-fixing typos

app/tasks/doctor.php
=> fix-723-Doctor CLI: `_APP_OPTIONS_FORCE_HTTPS=disabled` not correctly evaluated

app/tasks/doctor.php
Added some fixes to the Doctor CLI
#723 
#725 
Yes
=> Added some code review fixes

app/tasks/doctor.php
Harmonize negative check result descriptions in Doctor CLI.
_BTW: Note that indents got solved by IDE on commit, although wasn't actively trying to remove them. Maybe we should enable some auto-formatting in whole project to adjust this behavior. [See e.g. IntelliJ](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html)_
Run `docker-compose exec appwrite doctor` with according docker compose config.
Closes #724
Yes ;)
=> 👌 IMPROVE: Doctor CLI: Harmonize negative check result descriptions (closes #724)

Dockerfile
Upgraded Swoole to version 4.5.8
None
Yes
=> Feat Upgrade Swoole Version

CHANGES.md, app/workers/mails.php, docs/tutorials/environment-variables.md
Adds option to disable all Appwrite system emails by passing an empty SMTP hostname value.
#730 
Yes.
=> Feat 730 disable smtp server

app/config/events.php
Added new notes for new webhooks. The new notes will be used as part of the Appwrite docs.
None
#730 
Yes.
=> Feat events docs update

app/views/console/home/index.phtml
As suggested by @AndroidNils, I have added a soon label near any future platform that is still disabled in the UI.
Not required for this change.
#742 
Yes.
=> Feat 742 Better UX for Future Platofrm

app/controllers/api/account.php, app/controllers/api/database.php, app/controllers/api/storage.php, app/controllers/api/teams.php, app/controllers/api/users.php, app/controllers/general.php, app/init.php, src/Appwrite/Event/Event.php, tests/unit/Auth/Validator/PasswordTest.php, tests/unit/Event/EventTest.php
Merged the events objects of $webhooks and $functions to a single one called $events
Should leverage current tests.
#744 
#307 
Yes
=> Merged all system events

app/views/install/compose.phtml, docker-compose.yml
Allow Traefik to run alongside another Traefik instance on the same host.
#767 
Yes.
=> Feat enable multiple Traefik instances on the same host

app/controllers/api/account.php, app/controllers/api/avatars.php, app/controllers/api/database.php, app/controllers/api/functions.php, app/controllers/api/health.php, app/controllers/api/locale.php, app/controllers/api/projects.php, app/controllers/api/storage.php, app/controllers/api/teams.php, app/controllers/api/users.php, app/controllers/general.php, app/controllers/mock.php, app/controllers/web/console.php, app/controllers/web/home.php, composer.json, composer.lock, src/Appwrite/Specification/Format/OpenAPI3.php, src/Appwrite/Specification/Format/Swagger2.php, tests/e2e/Services/Health/HealthCustomServerTest.php
Improved Route signature for defining dependency injection.
Same tests we are already using.
None
Yes
=> Feat upgrade inject signature

CHANGES.md
There were some Duplicates in this changelog, fixed them :)
Removed duplicates from Changelog
No need to test
Yes!
=> Removed duplicates from Changelog

CHANGES.md
Added QR code generator library
Add QR code generator library to changelog
Not needed
Yes!
=> Updated changes.md

app/controllers/api/database.php, app/controllers/api/functions.php, app/controllers/api/projects.php
Some of the endpoints aren't making use of the orderType param that is passed. 
We already have tests for the controllers.
None
Yes
=> fix: use orderType in DB query

app/workers/functions.php
Fixed a bug causing the Functions worker to not delete the correct containers when exceeding the allowed max number of functions. 
N/A
#307 
Yes.
=> Bug: Wrong functions count and deletion when deleting old containers

CONTRIBUTING.md
In the last paragraph of contribution guidelines, on last line "You can also help by reaching others how to contribute to Appwrite's repo!". I believe the word "reaching" should have been "teaching".
No code change
No related issues or PRs
Yes
=> Correcting the spelling in Contribution Guidelines

CHANGES.md
Added new sub-categories to make the changelog more readable
N/A
N/A
Yes
=> Feat organized change-log

app/config/variables.php, app/tasks/vars.php
=> Feat update env var docs

app/controllers/api/account.php, app/controllers/api/users.php, src/Appwrite/Utopia/Response.php, tests/e2e/Services/Users/UsersBase.php
Fixed a UI bug when user had an empty prefs object.
Added a missing test to get prefs endpoint on the users service.
N/A
Yes
=> Fix user prefs UI

.travis.yml
This PR should help us reduce Docker rate limits errors in Travis CI
N/A
None.
Yes.
=> Added docker login

src/Appwrite/Utopia/Response/Model/Collection.php, src/Appwrite/Utopia/Response/Model/Continent.php, src/Appwrite/Utopia/Response/Model/Country.php, src/Appwrite/Utopia/Response/Model/Currency.php, src/Appwrite/Utopia/Response/Model/Domain.php, src/Appwrite/Utopia/Response/Model/Error.php, src/Appwrite/Utopia/Response/Model/ErrorDev.php, src/Appwrite/Utopia/Response/Model/Execution.php, src/Appwrite/Utopia/Response/Model/File.php, src/Appwrite/Utopia/Response/Model/Func.php, src/Appwrite/Utopia/Response/Model/Key.php, src/Appwrite/Utopia/Response/Model/Language.php, src/Appwrite/Utopia/Response/Model/Locale.php, src/Appwrite/Utopia/Response/Model/Log.php, src/Appwrite/Utopia/Response/Model/Membership.php, src/Appwrite/Utopia/Response/Model/Permissions.php, src/Appwrite/Utopia/Response/Model/Phone.php, src/Appwrite/Utopia/Response/Model/Platform.php, src/Appwrite/Utopia/Response/Model/Project.php, src/Appwrite/Utopia/Response/Model/Rule.php, src/Appwrite/Utopia/Response/Model/Session.php, src/Appwrite/Utopia/Response/Model/Tag.php, src/Appwrite/Utopia/Response/Model/Task.php, src/Appwrite/Utopia/Response/Model/Team.php, src/Appwrite/Utopia/Response/Model/Token.php, src/Appwrite/Utopia/Response/Model/User.php, src/Appwrite/Utopia/Response/Model/Webhook.php
Made sure all response objects have default values.
Use existing tests
None
Yes
=> Updated default values

app/workers/audits.php, app/workers/certificates.php, app/workers/deletes.php, app/workers/functions.php, app/workers/mails.php, app/workers/tasks.php, app/workers/usage.php, app/workers/webhooks.php
Minor code cleanups
N/A
None
Yes
=> Cleaning workers

app/config/environments.php, docker/environments/build.sh, docker/environments/deno-1.6/Dockerfile, tests/e2e/Services/Functions/FunctionsCustomServerTest.php
Added support for Deno 1.6 as a Cloud Function environment.
Added a new test.
#307 
Yes
=> Added Deno 1.6

app/tasks/maintenance.php, composer.json, composer.lock, docker-compose.yml
- Removed unused DB connection object and vars
- Added process start log
- Added time log
N/A
#766 
Yes.
=> Fix minor refactoring for maintenance

app/http.php
Supports starting Appwrite in different port using a `PORT` environment variable.
N/A
Related to #547 
Yes
=> Feat support PORT env

app/controllers/general.php, composer.lock
Fixing duplicated storage init code.
Existing test should be a good cover.
None
Yes
=> Fixed multiple storage init

app/controllers/api/functions.php, composer.json, composer.lock
Added validation for uploaded code tags to the Cloud Functions API. This is less of a security feature because it can be easily manipulated, but rather a feature for better error handling and dev experience. The upload file is not executed at any point and only gets uncompressed and run inside the isolated function env. 
#307 
Yes
=> Feat tag file validation

app/config/variables.php, app/tasks/install.php, app/views/install/compose.phtml
- removes port expose for mariadb
- removes build commands from appwrite-maintenance
- append env variables to `docker-compose up` command
- fixed some small leftovers
✅
=> Fixes Install script

src/Appwrite/Database/Database.php
Fixes using filters based on the statusFilters variable when writing data.
✅
=> Fix filters enable/disable on databases

app/controllers/api/functions.php, docs/examples/0.7.0/client-flutter/examples/functions/create-execution.md, docs/examples/0.7.0/client-flutter/examples/functions/get-execution.md, docs/examples/0.7.0/client-flutter/examples/functions/list-executions.md, tests/e2e/Services/Functions/FunctionsCustomClientTest.php, tests/e2e/Services/Functions/FunctionsCustomServerTest.php
Changed param name from file to code again after another discussion with @christyjacob4.
Existing tests.
#307 
Yes
=> Feat updated file param name to code

docs/tutorials/add-storage-adapter.md
Adds Doc for adding new storage adapters.
N/A
YES
=> Doc add storage adapter

app/config/variables.php, app/controllers/api/projects.php, app/controllers/general.php, app/workers/certificates.php, src/Appwrite/Utopia/Response/Model/Domain.php
- fixes acme challenge
- adds `_APP_SYSTEM_SECURITY_EMAIL_ADDRESS` to variables
- fixes command for windows in certificate worker
- adds missing rule to domain model
- fixes typos
✅
=> fix ssl issuing

app/views/console/keys/index.phtml, src/Appwrite/Utopia/Response.php, src/Appwrite/Utopia/Response/Filters/V06.php
- add language list model to response filters
- fix missing class as leftover from previous commits
- fix inconsistens plural naming
✅
=> fix(response-filters): missing response filter model

app/tasks/install.php, composer.json, composer.lock
- introduces `utopia-php/analytics`
- create events on successful/failed installation
- sending events based on the success/failure
✅
=> Introduce utopia-php/analytics

.travis.yml, app/workers/functions.php, docker-compose.yml, tests/e2e/Services/Functions/FunctionsCustomServerTest.php
Added docker login for the Appwrite cloud functions worker to make sure we don't reach docker pulls limit.
Leverage existing tests.
#307 
Yes.
=> Feat docker login from fucntions

app/config/environments.php, docker/environments/build.sh, tests/e2e/Services/Functions/FunctionsCustomServerTest.php
- adds architecture detection to cloud functions tests
- removes ARM support for .NET 3.1 due to missing alpine support
✅
=> feat(tests): add architecture detection

app/controllers/api/projects.php, app/init.php, app/views/install/compose.phtml, app/workers/deletes.php, docker-compose.yml
- deletes domain certificate files with deletes worker
- fix missed production compose env variables
✅ 
✅
=> Delete certificate files with worker

CHANGES.md, app/init.php
=> Feat updated geo db

app/config/services.php, app/controllers/web/home.php
Added short descriptions for all the services. 
N/A
None. This is just an enhancement for the CLI 
YES
=> feat: added short descriptions for all services

app/controllers/api/teams.php
- fixes team invitation cta text
- now using the same variable as the subject, which is already being tested
:check:
=> fix(teams): invitation email

docs/tutorials/add-environment-variable.md
New doc for adding Environment variables
N/A
YES
=> Doc add environment variable

app/views/console/home/index.phtml
Before this fix when stats disabled
After
=> Fix usage stats disabled home view

app/views/console/functions/function.phtml
=> fix function packaging powershell command

composer.lock
=> Upgrade utopia-php/swoole library

docs/references/functions/list-executions.md
=> fix-functions-docs

CONTRIBUTING.md
Update instructions from conversation in Discord
=> Update code autocompletion instructions

app/controllers/api/account.php, app/controllers/api/teams.php, src/Appwrite/Detector/Detector.php, tests/unit/Detector/DetectorTest.php
The device detection part has became a big and repetitive chunk of code in the account and team controllers. I created an Appwrite library for abstracting most of the work related to the Appwrite data format. We might want to make the interface a bit more reusable in the future, but I think it serves its purpose for now.
Added 3 new unit tests
#903 
Yes
=> Feat abstract device detector

app/views/console/functions/function.phtml
Fixes multi line command being properly passed to Appwrite CLI PowerShell script.
=> fixes cloud functions upload powershell snippet

app/controllers/shared/web.php, app/views/console/database/collection.phtml, app/views/console/database/search/documents.phtml, app/views/console/database/search/files.phtml, app/views/console/settings/index.phtml, app/views/console/storage/index.phtml, app/views/console/users/index.phtml, app/views/console/users/team.phtml, app/views/home/auth/recovery.phtml, app/views/layouts/default.phtml
Adds missing port information in the console, Fixes storage images preview not working on different port.
=> fix-missing-port-on-url

CONTRIBUTING.md
Added a new advanced topic section for contributors who wish to better understand the Appwrite design and codebase.
N/A
N/A
Yes
=> Added advanced topic section for contributors

CHANGES.md, Dockerfile, app/controllers/api/functions.php, app/controllers/api/projects.php, app/workers/functions.php, app/workers/tasks.php, composer.json, composer.lock, tests/unit/Detector/DetectorTest.php
- Upgraded utopia-php/cli lib to version 0.10.0
- Upgraded matomo/device-detector lib to version 4.1.0
- Upgraded dragonmantank/cron-expression lib to version 3.1.0
- Upgraded influxdb/influxdb-php lib to version 1.15.2
- Upgraded phpmailer/phpmailer lib to version 6.3.0
- Upgraded adhocore/jwt lib to version 1.1.2
N/A
Yes.
=> Updated dependencies

CHANGES.md, app/tasks/doctor.php, app/views/console/database/search/files.phtml, app/views/console/functions/function.phtml, app/views/console/home/index.phtml, app/views/console/storage/index.phtml, public/dist/scripts/app-all.js, public/dist/scripts/app.js, public/scripts/dependencies/litespeed.js, public/scripts/filters.js
Fixed XSS in the console
N/A
N/A
Yes
=> Fixed XSS in the console

CHANGES.md, app/controllers/web/home.php, tests/e2e/General/HTTPTest.php
A new endpoint that returns the server and SDKs latest versions numbers. This can be useful for alerting users about a new available version.
Added a new e2e test.
CLI Upgrade command
Yes
=> Added latest versions endpoint

README.md
Fix the Typo and grammatical mistakes in the Readme.md file
- Fix the typo and grammatical mistakes in the readme file.
**Yes**
=> Typo fix and grammatical mistake

app/preload.php
Updates `statsd` and `device-detector` from their old vendor directories to their new counterparts.
#951 
Yes
=> Use updated package paths

Dockerfile, app/http.php, app/init.php, app/realtime.php, app/workers/audits.php, app/workers/certificates.php, app/workers/deletes.php, app/workers/functions.php, app/workers/mails.php, app/workers/tasks.php, app/workers/usage.php, app/workers/webhooks.php, composer.json, composer.lock, src/Appwrite/Resque/Worker.php, tests/benchmarks/http.js, tests/benchmarks/ws.js
Refactored the way resources are being used
#265 
Yes.
=> Refactored resources

CHANGES.md, app/http.php
Fixes timezone offset on user's audit log dates.
👍🏻
=> Fix timezone offset

app/controllers/api/users.php, app/tasks/sdks.php
=> Fix - 0.7.1 Review

CONTRIBUTING.md, app/controllers/api/database.php, tests/e2e/Services/Database/DatabaseBase.php
Fixed bug not allowing you to reset document permission.
Leverage existing tests.
#977 
Yes.
=> Allow permission reset

app/tasks/install.php
=> fix installation script not saving answers

docs/sdks/nodejs/GETTING_STARTED.md
=> feat-node-sdk-getting-started

app/config/variables.php
Updated Redis docs
N/A
N/A
Yes
=> Updated docs

docs/sdks/python/GETTING_STARTED.md
=> feat-python-sdk-getting-started

docs/sdks/php/GETTING_STARTED.md
=> feat-php-sdk-getting-started

docs/sdks/deno/GETTING_STARTED.md
=> feat-deno-sdk-getting-started

composer.lock
Fixed a PHP warning on redirect routes.
Leverage existing tests.
N/A
Yes.
=> Fix Redirect Warning

docs/sdks/ruby/GETTING_STARTED.md
=> feat-ruby-getting-started

CONTRIBUTING.md, README.md
This PR fixes a few issues with the in-repo documentation (README.md and CONTRIBUTING.md)
There is nothing to test.
As this was brought up through Discord, there are no related PRs or Issues
Yes
=> Doc fixing broken environment variables link

docs/sdks/dotnet/CHANGELOG.md, docs/sdks/dotnet/GETTING_STARTED.md
=> Add .NET Getting started

README.md
Updates the docker-compose link in the Installtion Section of the README
If you can think of a way to test it, go for it.
No related PRs or Issues
Yeah
=> Updated the docker-compose link in the Installation Section of the README

composer.json, composer.lock
=> bump utopia/analytics to 0.2.0

docs/sdks/web/GETTING_STARTED.md
=> Add Web Getting started 

docs/sdks/dart/GETTING_STARTED.md, docs/sdks/deno/GETTING_STARTED.md, docs/sdks/dotnet/GETTING_STARTED.md, docs/sdks/flutter/GETTING_STARTED.md, docs/sdks/nodejs/GETTING_STARTED.md, docs/sdks/php/GETTING_STARTED.md, docs/sdks/python/GETTING_STARTED.md, docs/sdks/ruby/GETTING_STARTED.md
=> feat-error-handling-section-on-sdks

docs/sdks/dart/GETTING_STARTED.md, docs/sdks/deno/GETTING_STARTED.md, docs/sdks/dotnet/GETTING_STARTED.md, docs/sdks/flutter/GETTING_STARTED.md, docs/sdks/nodejs/GETTING_STARTED.md, docs/sdks/php/GETTING_STARTED.md, docs/sdks/python/GETTING_STARTED.md, docs/sdks/ruby/GETTING_STARTED.md, docs/sdks/web/GETTING_STARTED.md
=> fix-getting-started-self-signed-cert

CHANGES.md, app/views/console/database/collection.phtml, app/views/console/database/index.phtml, app/views/console/storage/index.phtml, app/views/console/users/index.phtml
Changed all the console bottom controls to be consistent and easy to use even on high res screens.
N/A
#1061 
Yes.
=> Feat: Consistent Bottom Controls

app/config/environments.php, app/config/variables.php, docker/environments/build.sh, docker/environments/python-3.9/Dockerfile, tests/e2e/Services/Functions/FunctionsCustomServerTest.php
=> feat-python-3.9-env

.env, Dockerfile, app/config/variables.php, app/init.php, app/views/install/compose.phtml, docker-compose.yml
Allows to set default Appwrite Locale using .env
Existing tests should cover
#1052 
=> feat-locale-env-support

docs/references/account/update-password.md
Make update password docs more clear.
Problem:
This part of the documentation is a little confusing. It says "For validation, user is required to pass the password twice." And in the example is shows updatePassword('password', 'password'). 
However in the method description it says that we must pass in the new password, and the old password.
Yes
=> doc-na-Make update password docs more clear.

app/tasks/migrate.php, src/Appwrite/Migration/Migration.php
Changes the used class for migration task to the proper one.
✅
=> fix: migration for 0.8.x

package-lock.json, package.json
- updates yargs-parser package
- removes unused jest dependency
- add build scripts for convenience 
=> deps: update npm packages and add scripts

app/config/events.php, app/controllers/api/database.php, app/controllers/mock.php, app/views/console/database/collection.phtml, composer.json, composer.lock, public/dist/scripts/app-all.js, public/dist/scripts/app.js, public/scripts/services/form.js, src/Appwrite/Auth/Validator/Password.php, src/Appwrite/Database/Validator/Authorization.php, src/Appwrite/Database/Validator/DocumentId.php, src/Appwrite/Database/Validator/Key.php, src/Appwrite/Database/Validator/Permissions.php, src/Appwrite/Database/Validator/Structure.php, src/Appwrite/Database/Validator/UID.php, src/Appwrite/Network/Validator/CNAME.php, src/Appwrite/Network/Validator/Domain.php, src/Appwrite/Network/Validator/Email.php, src/Appwrite/Network/Validator/Host.php, src/Appwrite/Network/Validator/IP.php, src/Appwrite/Network/Validator/Origin.php, src/Appwrite/Network/Validator/URL.php, src/Appwrite/Specification/Format/OpenAPI3.php, src/Appwrite/Specification/Format/Swagger2.php, src/Appwrite/Task/Validator/Cron.php, src/Appwrite/Utopia/Response.php, src/Appwrite/Utopia/Response/Filters/V06.php, src/Appwrite/Utopia/Response/Model/Document.php
- sync with dev branch
- fixes all Validator class inheritances
- check type on spec generation
Waiting for utopia-php/storage release https://github.com/utopia-php/storage/pull/14
=> Refactor: whitelist type for spec generation

src/Appwrite/Migration/Migration.php, src/Appwrite/Migration/Version/V07.php
- fixes migration script for multidimensional array comparison
✅
=> fix: migration script to 0.8

app/controllers/api/avatars.php
Fixed a bug where some avatars cache was mistakenly shared.
Existing tests
N/A
Yes
=> Fixed cached bug

app/controllers/api/account.php
- improves error message when already logged in user tries to create an anonymous session 
- already covered
✅
=> fix: improve error message on anon login

app/controllers/api/functions.php, src/Appwrite/Database/Database.php
- fixes functions permissions when fetching execxutions
✅
=> fix: executions permission validation

CHANGES.md, app/controllers/api/account.php, app/controllers/api/users.php, src/Appwrite/Utopia/Response.php, src/Appwrite/Utopia/Response/Filters/V06.php, src/Appwrite/Utopia/Response/Model/Preferences.php, src/Appwrite/Utopia/Response/Model/User.php
- adds preferences to response models
- existing tests
✅
=> feat: preferences response model

app/workers/usage.php
Fix warning on the usage controller when receiving jobs with missing params from the functions worker. 
N/A
Yes
=> fix-usage-worker-errors

.travis.yml, phpunit.xml
- the CI can be so fast, that telegraf hasn't setup the database in influx
- fixes `Query has failed: database not found: telegraf` failing in tests
✅
=> tests(project): change order for influxdb to have a database

CHANGES.md, app/controllers/api/teams.php, app/views/console/settings/index.phtml, app/views/console/users/team.phtml, app/views/home/auth/join.phtml, tests/e2e/Services/Teams/TeamsBaseClient.php, tests/e2e/Services/Webhooks/WebhooksBase.php, tests/e2e/Services/Webhooks/WebhooksCustomClientTest.php
Refactor `inviteId` to `membershipId`
Reuse existing tests
NA
Yes
=> feat: refactor inviteId to membershipId

app/views/console/comps/footer.phtml
=> feat-discord-link

CHANGES.md, app/controllers/general.php, app/http.php
=> feat-auto-ssl-generation

CHANGES.md, app/controllers/api/teams.php
* Increase limit of members fetched during createTeamMembership to 2000
* Correct the event names in audits worker trigger
NA
NA
Yes
=> fix(teams): some minor issues with the API

app/tasks/install.php
=> feat-automated-install

app/views/console/users/index.phtml
(Attempt to) Fix OAuth form autocompletion on Chrome.
N/A
N/A
Yes.
=> Fix oauth autocomplete

app/views/console/users/index.phtml
Fixed a bug causing the users list in the console to break. #1144 
N/A
#1144
Yes.
=> Added string escaping

app/views/home/auth/signup.phtml
Fix for signup redirect when user is already logged.
N/A
#937 
Yes
=> Fix redirect from signup

app/controllers/general.php, src/Appwrite/Utopia/Response/Filters/V06.php, src/Appwrite/Utopia/Response/Filters/V07.php
Added a dummy response filter for backward compatibility to 0.7 SDKs
NA
NA
Yes
=> feat: 0.7 response filters

app/controllers/general.php
=> fix-certificates-queueing

app/tasks/sdks.php
=> feat-response-format-header-sdks

app/config/variables.php, app/tasks/install.php, app/views/install/compose.phtml
=> feat-auto-generate-secret-keys

CHANGES.md, app/config/platforms.php
Updated SDKs versions for 0.8.x release
N/A
N/A
Yes
=> Updated SDKs versions

app/views/install/compose.phtml, docker-compose.yml
=> fix(docker): functions worker missing openssl key

app/views/install/compose.phtml
=> fix(docker): influxdb image

docs/sdks/web/GETTING_STARTED.md
=> fix(docs): web sdk getting started

app/controllers/api/health.php
=> fixing clamav status when clamav is not running

app/http.php
=> modify swoole buffer output size

app/controllers/api/account.php
=> fixes deleteSession API removes browser's cookieFallback #1193

src/Appwrite/Auth/OAuth2/Twitch.php
Fixed some incorrect logic in Twitch OAuth adapter
NA
Fix for #1205 
Yes
=> fix: twitch oAuth issue

app/controllers/api/account.php
Pass the session object when creating an OAuth2 session
Existing tests
#1176 
YES
=> feat: pass session to cloud function in oauth create sessions

app/views/console/users/user.phtml
Rename deleteUser to delete
NA
NA
Yes
=> fix(users): rename deleteUser to delete

CHANGES.md, app/views/install/compose.phtml, tests/resources/docker/docker-compose.yml
Upgraded telegraf docker image version to v1.1.0, should now work fine on arm64.
e2e tests
A Discord issue. 
Yes
=> Feat upgrade telegraf version

app/controllers/mock.php
- adds a mock endpoint for the sdk-generator test that downloads a file
✅
=> feat(mock): download endpoint

docs/sdks/android/CHANGELOG.md, docs/sdks/android/GETTING_STARTED.md
Adds Readme for Android SDK
Not Required
YES
=> feat-android-sdk-readme

app/config/platforms.php, app/tasks/sdks.php, composer.json, composer.lock, docs/sdks/dart/CHANGELOG.md, docs/sdks/flutter/CHANGELOG.md
=> feat(sdks): update to sdk-generator@0.10.9

app/controllers/api/account.php, app/controllers/api/teams.php, app/controllers/api/users.php
Emails are case insensitive. Ignore email case across all APIs
Leverage Existing tests
#1240 
Yes
=> fix: ignore email case when creating account

app/tasks/sdks.php, docs/sdks/android/GETTING_STARTED.md, docs/sdks/deno/GETTING_STARTED.md, docs/sdks/flutter/GETTING_STARTED.md, docs/sdks/nodejs/GETTING_STARTED.md, docs/sdks/php/GETTING_STARTED.md, docs/sdks/python/GETTING_STARTED.md, docs/sdks/ruby/GETTING_STARTED.md, docs/sdks/web/GETTING_STARTED.md
Fix some issues with the getting started guide
NA
https://github.com/appwrite/sdk-for-android/pull/4
Yes
=> Update Getting started Guides

app/controllers/api/health.php
=> fix warning

app/controllers/api/health.php, app/workers/audits.php, app/workers/certificates.php, app/workers/deletes.php, app/workers/functions.php, app/workers/mails.php, app/workers/tasks.php, app/workers/usage.php, app/workers/webhooks.php, src/Appwrite/Resque/Worker.php
- Adds an abstract class for all Workers
✅
=> refactor(workers): create abstract worker class

tests/e2e/General/HTTPTest.php
=> fix(tests): skip swagger spec validation

composer.json, composer.lock
Use new PHP Runtimes with new Runtime docker hub repositories
Existing Tests should be good enough
YES
=> feat-new-functions-runtime

app/workers/functions.php
Tiny fix for a duplicated CLI call
Existing tests should be enough
N/A
Yes
=> Removed duplicated cli command

app/controllers/api/storage.php, app/controllers/mock.php
Revert Integer Validator in the Mock controller with Numeric
NA
Failing tests in the SDK generator
Yes
=> feat: revert integer validator to numeric

Dockerfile
=> deps(php): imagick to 3.5.0

package-lock.json, package.json
=> deps(npm): fix lock files

src/Appwrite/Utopia/Response/Model/Execution.php
Updated the description for the Execution model.
N/A
Discord: https://discord.com/channels/564160730845151244/636852860709240842/859495753188638770
Yes
=> Updated description on Execution Model

app/tasks/migrate.php, src/Appwrite/Migration/Version/V07.php, src/Appwrite/Migration/Version/V08.php, tests/unit/Migration/MigrationV08Test.php
=> feat(migration): 0.9.x

app/tasks/sdks.php
Add server side SDK warning to Kotlin SDK
NA
NA
YES
=> Feat update kotlin readme

app/config/collections.php, app/controllers/api/projects.php, src/Appwrite/Migration/Version/V08.php, tests/unit/Migration/MigrationV08Test.php
=> feat(projects): add version number

CHANGES.md
=> fix(changelog): 0.9

docs/sdks/flutter/GETTING_STARTED.md
Update Flutter Getting Started section with Information regarding Desktop platforms
N/A
YES
=> desktop platforms support on readme

app/controllers/api/database.php, src/Appwrite/Database/Adapter.php, src/Appwrite/Database/Adapter/MySQL.php, src/Appwrite/Database/Adapter/Redis.php, src/Appwrite/Database/Database.php
- cast filter values to `int` if numeric rule
- tbd
#1325 
✅
=> fix(database): properly cast to int

CHANGES.md
=> fix(changelog): 0.9.x

app/config/platforms.php, app/tasks/sdks.php, composer.json, composer.lock
Allows setting SDK's `docDirectories` which will generate docs based on the declared languages and their templates.
=> Feat kotlin java docs

docs/sdks/dart/CHANGELOG.md, docs/sdks/flutter/CHANGELOG.md
Add changelog for flutter and dart 
NA
NA
Yes
=> feat(sdks): added flutter and dart changelog

docs/sdks/android/GETTING_STARTED.md, docs/sdks/dart/GETTING_STARTED.md, docs/sdks/deno/GETTING_STARTED.md, docs/sdks/dotnet/GETTING_STARTED.md, docs/sdks/flutter/GETTING_STARTED.md, docs/sdks/kotlin/GETTING_STARTED.md, docs/sdks/nodejs/GETTING_STARTED.md, docs/sdks/php/GETTING_STARTED.md, docs/sdks/python/GETTING_STARTED.md, docs/sdks/ruby/GETTING_STARTED.md, docs/sdks/web/GETTING_STARTED.md
This PR will Fix a Mistype in SDK Getting Started files near the bottom
Yes, I have
=> Fix Mistype in SDK Getting Started files

README.md
Update version in README
NA
NA
Yes
=> feat(docs): update version in readme

app/controllers/api/account.php, app/controllers/api/health.php, app/controllers/api/users.php, app/http.php, composer.lock
- remove `app` resource
- replace with `utopia` resource
=> fix(app): remove app resource and replace with utopia

app/controllers/general.php, app/http.php, app/init.php, app/views/install/compose.phtml, docker-compose.yml
- if `PDOException` is thrown, reset the connection
✅
=> fix(http): reset pdo connection if broken

CHANGES.md
=> update changelog for 0.9.1

.gitignore, CONTRIBUTING.md, Dockerfile, dev/yasd_init.php.stub, docker-compose.yml
Adds and setups the debugger [yasd](https://github.com/swoole/yasd) when built with TESTING=true
N/A
YES
=> feat-dev-debugger

src/Appwrite/Utopia/Response.php
- fixes phpdoc block for setStatusCode
✅
=> fix(response): setStatusCode phpdoc block

docs/references/teams/create-team-membership.md
Update Create membership doc
N/A
YES
=> update create membership doc

app/controllers/api/database.php
Fixed wrong paths and duplicated method names
Existing tests
N/A
Yes
=> fix-db-open-api-spec

composer.json, composer.lock
Fixed index creation webhook test
Using existing tests
N/A
Yes
=> fix-index-test

app/init.php
- fix used attribute to match JWT with the session
#1251 
✅
=> fix(jwt): correct session validation

app/config/collections2.php, composer.lock
Added the missing index for the sessions collection
N/A
Yes
=> fix-sessions-index

app/controllers/api/account.php, app/controllers/api/avatars.php, app/controllers/api/database.php, app/controllers/api/functions.php, app/controllers/api/locale.php, app/controllers/api/projects.php, app/controllers/api/storage.php, app/controllers/api/teams.php, app/controllers/api/users.php, app/controllers/general.php, app/controllers/mock.php, app/controllers/shared/api.php, app/controllers/web/home.php, app/http.php, app/init.php, src/Appwrite/Auth/Auth.php, src/Appwrite/Specification/Format/OpenAPI3.php, src/Appwrite/Specification/Format/Swagger2.php, src/Appwrite/Utopia/Response.php
Removed references to the old DB library.
N/A
Yes
=> Feat cleanup old DB lib

app/controllers/api/account.php
This PR will fix a bug regarding two abuse-keys which were invalid and used param's they did not have. This will fix a bug with creating JWT's being rate limited for other users if one user hits the limit.
This issue was reported in the discord
Yes, I have
=> Fix Abuse Keys

app/config/platforms.php, composer.json, composer.lock, docs/sdks/flutter/CHANGELOG.md
=> sdks(flutter): release 0.7.1

app/controllers/api/projects.php, app/views/console/home/index.phtml
Fix for project API security issue.
YES
=> hot fix project api issue

composer.json, composer.lock
Updated abuse and audit libs
Use existing tests
N/A
Yes
=> Updated audit and abuse dependencies

app/controllers/api/account.php, app/controllers/api/database.php, app/controllers/api/teams.php, app/controllers/general.php, app/workers/certificates.php, app/workers/database.php, composer.json, composer.lock, tests/e2e/Services/Webhooks/WebhooksCustomServerTest.php
This PR brings `feat-database-indexing` in sync with `utopia-php/database:0.6.0`:
- Updates `composer.json`
- Updates `findFirst` to `findOne`
- Uses the `format` param for attributes
- Key Index constant renamed to `key`
Current test suite covers this behavior.
N/A
Yes.
=> feat(refactor-db): update utopia-php/database to 0.6

app/config/platforms.php
=> doc: use Angular as the example is for Angular

app/controllers/general.php
Simplify domain permission check. Always prefer `Authorization::reset` over `Authorization::disable`
Existing tests
N/A
Yes
=> Simplified Permission handling

app/views/console/functions/function.phtml, app/workers/database.php, src/Appwrite/Utopia/Response/Model/Func.php
No need for permission check in the worker scope.
Existing tests.
N/A
Yes
=> Permission fix

app/views/console/database/collection.phtml, app/views/console/database/document.phtml, app/views/console/functions/function.phtml, app/views/console/storage/index.phtml
UI change `Add * for wildcard access` to `Add 'role:all' for wildcard access`\
YES
=> feat-permission-help-text

app/controllers/api/database.php, app/init.php, app/workers/database.php, bin/worker-database, tests/e2e/Services/Database/DatabaseBase.php, tests/e2e/Services/Database/DatabaseCustomServerTest.php, tests/e2e/Services/Webhooks/WebhooksCustomServerTest.php
This PR:
- Fixes the logic for attribute and index deletion
- Updates `id` param on createIndex to `indexId` (and fixed tests)
- Implemented a method to name worker constants
End-to-end tests added for changes
N/A
Yes.
=> feat(refactor-db): tests for attribute and index deletion

app/views/install/compose.phtml, docker-compose.yml
=> docker(traefik): update to version 2.5

app/controllers/general.php, app/controllers/mock.php, app/controllers/shared/api.php, composer.json, composer.lock, src/Appwrite/Specification/Format/OpenAPI3.php, src/Appwrite/Specification/Format/Swagger2.php
Upgrade Framework to 0.18
Existing Tests should cover
YES
=> fix changed getURL to getPath

app/init.php, app/views/install/compose.phtml, docker-compose.yml
This PR fixes a issue with reconnecting to the SQL Server after a timeout or another connection error has taken place
All previous tests have been ran, there is no need to add new tests for this.
https://github.com/appwrite/appwrite/issues/1509
Yes, I have.
=> Initial Fix

app/workers/deletes.php
- Added missing offset to projects iteration.
- Added some missing types (Thx to Psalm vscode ext)
Using existing tests
N/A
Yes
=> fix-deletes-worker-missing-offset

app/tasks/usage.php
=> feat-usage-codereview

app/config/events.php
Adds new events related to users update email, name and password to the events config
N/A
YES
=> fix-events

app/workers/audits.php, app/workers/certificates.php, app/workers/deletes.php, app/workers/functions.php, app/workers/mails.php, app/workers/tasks.php, app/workers/usage.php, app/workers/webhooks.php, src/Appwrite/Resque/Worker.php
- cleaning up some smelly code style across workers
✅
=> refactor(workers): refactor the workers

src/Appwrite/Migration/Migration.php
- skip documents without ID or Collection
=> fix(migration): better warning message

app/controllers/general.php, src/Appwrite/Auth/Auth.php, tests/unit/Auth/AuthTest.php
- add role to authentication for privileged users
✅
=> fix(auth): add role for privileged users

phpunit.xml, tests/e2e/Services/Storage/StorageCustomClientTest.php
=> test(storage): default permissions with client

app/controllers/general.php
=> fix(ssl): fix check for auto generation

app/config/platforms.php, app/init.php, composer.json, composer.lock
=> chore(sdks): php sdk to 2.3.1

app/controllers/api/storage.php
Adds separate collection per bucket for storing Files. This is required for supporting custom ID for files, so that files can have unique ID per bucket
Existing tests
https://github.com/appwrite/appwrite/pull/1380
YES
=> feat-separate-files-collection-per-bucket

app/realtime.php
- replace assigning by reference with `Swoole\Table->get(mixed $key, string $column)`
- unsetting unused objects
#1605 
✅
=> fix(realtime): memory leak with swoole table

app/tasks/usage.php
- Fixes first time startup of usage container, retrying for mariadb connection, retrying for influx db database ready, retrying for console db ready
N/A
YES
=> Fix-usage-daemon-startup

app/config/auth.php, app/controllers/api/teams.php, app/workers/deletes.php
- Fixes - Array has 2 duplicate keys with value 'teamId' ('teamId', 'teamId')
- Fixes - Access to undefined constant `Appwrite\Database\Database::SYSTEM_COLLECTION_REALTIME_CONNECTIONS`
- Fixes - Array has 2 duplicate keys with value 'docs' ('docs', 'docs'). 
✅
=> fix(app): minor bugs

src/Appwrite/Utopia/Response.php, src/Appwrite/Utopia/Response/Model.php, src/Appwrite/Utopia/Response/Model/Attribute.php, src/Appwrite/Utopia/Response/Model/AttributeBoolean.php, src/Appwrite/Utopia/Response/Model/AttributeEmail.php, src/Appwrite/Utopia/Response/Model/AttributeFloat.php, src/Appwrite/Utopia/Response/Model/AttributeIP.php, src/Appwrite/Utopia/Response/Model/AttributeInteger.php, src/Appwrite/Utopia/Response/Model/AttributeList.php, src/Appwrite/Utopia/Response/Model/AttributeString.php, src/Appwrite/Utopia/Response/Model/AttributeURL.php, src/Appwrite/Utopia/Response/Model/Collection.php
Just an idea on how this could also be handled 👍🏻 
#1484 
✅
=> feat(feat-response-models-new-attributes): introduce response type array

.travis.yml, phpunit.xml
=> feat(tests): check for failing test

.travis.yml
Upgrade the Travis CI instance to `large` on `feat-database-indexing`. Related PR updates `master` branch.
Passing test suite is sufficient to prove this change works.
https://github.com/appwrite/appwrite/pull/1632
Yes
=> feat(refactor-db): upgrade travis instance from medium to large

src/Appwrite/Utopia/Response/Model/BaseList.php
Updated the `sum` attribute description for more clarity.
N/A
N/A
Yes
=> Fixed sum description

app/config/collections2.php, app/controllers/api/functions.php, tests/e2e/Services/Functions/FunctionsCustomServerTest.php
Chunked upload support on Create tag
YES
=> Feat-large-function-tags

app/controllers/api/database.php, app/controllers/web/home.php, composer.lock, src/Appwrite/Specification/Format/OpenAPI3.php, src/Appwrite/Specification/Format/Swagger2.php
Swagger2 + OpenAPI3 support for new response models - multiple possible values for a type. For example `attributeList`.
Swagger Editor didn't complain 😶
✅
=> Feat database indexing openapi fix

README.md
Adds a link to a new client SDK for Appcelerator Titanium based on the Android SDK
just a link. Code for the module in my repo.
:jack_o_lantern:  hacktoberfest :jack_o_lantern: 
:heavy_check_mark:
=> doc(all): add new client SDK: Appclerator Titanium

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/documentation.yaml, .github/ISSUE_TEMPLATE/feature.yaml
Improves GitHub issue forms
Not tested. Will do it before un-drafting.
✅
=> Fix: Updates to our GitHub issue forms

.github/workflows/tests.yml
=> ci(gh): add github action

.github/ISSUE_TEMPLATE/bug.yaml
This PR replaces `enviromnemt` with `environment` in .github/ISSUE_TEMPLATE/bug.yaml:61
Not applicable
Yes.
=> Fix typo in bug.yaml

README.md
Add `Getting Started for Android` in README
=> Add Getting started for Android in README

app/config/locale/languages.php
In languages.php file, native name of SINDHI and HINDI language was wrongly written. In this PR, I have corrected native name of 2 languages in languages.php file.
I have changed the native name of SINDHI and Hindi language which was not written correctly. My changes are correct and verified.
Help Translate Appwrite Locale and Email templates #25
Help Translate Appwrite to Sindhi language ✍️ #1759
Help improve Appwrite's Hindi language translation ✍️ #1690
YES
=>  Update languages.php

docs/tutorials/add-storage-adapter.md
envorinment -------> environment
=> doc(tutorials/add-storage-adapter) -------> fixed typo

app/controllers/api/database.php, composer.json, composer.lock
This PR solves a few bugs:
- Uses correct constant for minimum float value
- Clears external cache when collections/documents are deleted
- Pass filters to createAttribute to inherit default (`[]`)
- Uses Utopia\Database patch for optional array attributes
https://github.com/utopia-php/database/pull/80
Yes.
=> fix(refactor-db): more api bugfixes

app/controllers/mock.php
Chunked upload tests on mock API to test chunked upload support on SDKs
N/A
https://github.com/appwrite/sdk-generator/pull/302
YES
=> Feat-mock-upload-chunked

app/controllers/api/health.php
This PR improve the DB Health endpoint by also checking the connection is active with a simple `SELECT 1` query, if it succeeds then a successful status is returned. If anything goes wrong a 500 status code is returned.
https://github.com/appwrite/appwrite/issues/1947
Yes, I have
=> Improve health check for Database

app/config/platforms.php, composer.json, composer.lock
=> feat(sdks): release web 5.0.0

.github/ISSUE_TEMPLATE/bug.yaml
Adds new Appwrite version into GitHub issue form
Not required
✅
=> Added 0.11.x to GitHub bug form dropdown

README.md
Fixes a previous PR, editing a line in the README
No test plan needed.
#2374 on review [#r739813192](https://github.com/appwrite/appwrite/pull/2374/files/cc4ef95cc04001d9a463c8f526530ebd00404a9e#r739813192)
Yes
=> Fix Godot Engine line mentioning another user

src/Appwrite/OpenSSL/OpenSSL.php
Fix all PSR issues on OpenSSL library on master branch.
The CI should pass (tested locally).
Close #1962 
Yes
=> fix: PSR issues on OpenSSL at master

src/Appwrite/Extend/PDO.php, src/Appwrite/Extend/PDOStatement.php
It fixes the PSR issues in the Extend library, Used PHP-CS-Fixer to perform this task. 
Fixes #1944 
Yes
=> Fixed PSR issues in the Extend(src\Appwrite) library

docs/sdks/flutter/GETTING_STARTED.md
Issue #1985 
Updated getting started with flutter doc code to wrap functional code inside "void main" so that it works directly when copied.
Checked that the full code works directly
Related PR - https://github.com/appwrite/docs/pull/89
Yep
=> Issue #1985 - Changes added to getting started with flutter doc

src/Appwrite/Docker/Compose/Service.php, src/Appwrite/Docker/Env.php
Issue #1972 
Run php-cs-fixer in src/Appwrite/Docker/ folder
Further running php-cs-fixer diff should not show any additional change
Yes
=> Issue #1972: Ran php-cs-fixer in src/Appwrite/Docker/ folder

app/tasks/usage.php
- fixes the health check for InfluxDB in the usage worker
=> fix(usage): influxdb health check

app/workers/deletes.php
- adds realtime logs deletion
- improve codebase to be more dry
=> fix(deletes): add realtime logs and improve code

composer.json, composer.lock, tests/e2e/Services/Teams/TeamsBaseClient.php, tests/e2e/Services/Webhooks/WebhooksBase.php
Bump utopia-php/database to 0.12
If tests pass, we're good :)
N/A
Yes.
=> Bump utopia-php/database to 0.12

app/views/install/compose.phtml
=> feat(views/install): database worker

app/views/layouts/default.phtml
Uses Appwrite's pink as the theme colour of the website. This is used all over the place - discord embeds, mobile panel colour, scrolling out of the view colour...
Not required
✅
=> Updated theme color to Appwrite pink

CHANGES.md, app/realtime.php, app/workers/functions.php, docs/references/teams/update-team-membership-status.md, docs/sdks/flutter-dev/CHANGELOG.md, docs/sdks/flutter/CHANGELOG.md, tests/resources/functions/php/index.php, tests/unit/General/CollectionsTest.php
Correct typos i found in this repository
(Yeah)
=> doc: Fix typos

tests/e2e/Services/Locale/LocaleBase.php
On master, there are currently some locale problems with tests. This PR is supposed to fix master's tests.
Green circle
✅
=> Attempt to fix tests

app/controllers/api/functions.php, composer.lock, docs/references/functions/list-runtimes.md, src/Appwrite/Utopia/Response.php, src/Appwrite/Utopia/Response/Model/Runtime.php, tests/e2e/Services/Functions/FunctionsCustomServerTest.php
Add a new endpoint to return the currently active runtimes for the project. 
Added Tests to verify the structure and number of documents 
NA
YES
=> feat: add new endpoint

composer.json, composer.lock, src/Appwrite/Auth/Validator/Password.php, src/Appwrite/Database/Validator/Authorization.php, src/Appwrite/Database/Validator/Collection.php, src/Appwrite/Database/Validator/CustomId.php, src/Appwrite/Database/Validator/DocumentId.php, src/Appwrite/Database/Validator/Key.php, src/Appwrite/Database/Validator/Permissions.php, src/Appwrite/Database/Validator/Structure.php, src/Appwrite/Database/Validator/UID.php, src/Appwrite/Network/Validator/CNAME.php, src/Appwrite/Network/Validator/Domain.php, src/Appwrite/Network/Validator/Email.php, src/Appwrite/Network/Validator/Host.php, src/Appwrite/Network/Validator/IP.php, src/Appwrite/Network/Validator/Origin.php, src/Appwrite/Network/Validator/URL.php, src/Appwrite/Template/Template.php
=> chore(deps): update utopia dependencies

app/controllers/api/database.php
- enforce the defualt value to be a float value
- existing tests should cover good enough
✅
=> fix: convert default value to float on attribute creation

app/controllers/api/database.php, app/controllers/api/users.php, app/views/console/users/user.phtml, src/Appwrite/Detector/Detector.php
1. Add support for the Terminal User Agent
2. Refactor the usage of the old DeviceDetector.
Use Existing Tests
NA
YES
=> Feat: add user agent

app/controllers/api/database.php
Remove some leftovers from `listIndexes` endpoint
Need to write a test to validate the structure of the response.
NA
YES
=> feat: fix issue with listIndexes

docs/sdks/flutter/GETTING_STARTED.md
Adds new information related to Flutter web OAuth due to update in Flutter web auth plugin.
Ref: https://pub.dev/packages/flutter_web_auth
N/A
https://github.com/appwrite/sdk-generator/pull/325
YES
=> update flutter getting started

app/controllers/api/account.php, app/controllers/api/avatars.php, app/controllers/api/database.php, app/controllers/api/functions.php, app/http.php, app/init.php, app/realtime.php, app/workers/functions.php, tests/e2e/Services/Realtime/RealtimeCustomClientTest.php
=> feat: use arrow functions on authorization skip method

app/controllers/api/database.php, app/init.php, tests/e2e/Services/Database/DatabaseBase.php
- make enum attribute strict/case sensitive
- check the default value against elements on creation
- extended tests
✅
=> fix: strict enum attribute

app/config/platforms.php, composer.json, composer.lock, docs/sdks/dart/CHANGELOG.md, docs/sdks/flutter/CHANGELOG.md
- Updated sdk generator version
- Updated and released Flutter and Dart SDKs
- Updated Flutter and Dart SDK changelogs
N/A
YES
=> Feat-sdk-generator-update

app/controllers/api/account.php, app/controllers/api/functions.php, app/controllers/api/teams.php, app/init.php
As we are moving away from `Authorization::disable()` to a more declarative approach using `Authorization::skip($callback)` we are slowly migrating.
This PR also optimizes some parts of the Teams controller 👍🏻 
=> refactor: replace authorization disable with skip

app/http.php
=> fix: status code on uncaught exception

composer.lock, tests/e2e/Services/Database/DatabaseBase.php
=> fix: query on $id

app/controllers/api/database.php, tests/e2e/Services/Database/DatabaseBase.php
- check if there are more than 100 values for a query used and throw an error
- added tests
=> fix: database query value limits

CHANGES.md, composer.lock
- Adds runtime for PHP 8.1
- Adds runtime for Node 17.0
- Changed the order of displayed runtimes
Tests are covered in the runtimes lib.
N/A
Yes.
=> Feat-updated-runtimes

app/views/install/compose.phtml, docker-compose.yml
I've seen some cases where the realtime service was ready before the DB. This fix should help avoid any errors until the connection is available.
Existing tests.
N/A
Yes.
=> Set db as depended of realtime

app/controllers/api/health.php
=> fix: throw exception when antivirus is not available

app/config/platforms.php
Updates SDK version
N/A
N/A
YES
=> Fix-sdk-versions

docs/sdks/dart/CHANGELOG.md, docs/sdks/flutter/CHANGELOG.md
Simple fix to Flutter & Dart Change logs
YES
=> Fix-changelog

app/controllers/general.php, composer.json, composer.lock, src/Appwrite/Utopia/Request.php, src/Appwrite/Utopia/Request/Filters/V12.php, src/Appwrite/Utopia/Response/Filters/V11.php
=> fix: request and response filters

app/views/console/functions/function.phtml
- `data-forms-key-value` was executed too early
=> fix: ui for functions variables

README.md, docs/specs/overview.drawio.svg
Adds a new section to the readme and updated the architecture chart
N/A
N/A
Yes
=> Updated architecture

app/views/console/home/index.phtml, public/dist/scripts/app-all.js, public/dist/scripts/app.js, public/scripts/filters.js
Fixes requests sum in dashboard (instead of using last value):
Adds number format to realtime connections amount:
Manual testing
✅
=> Added sum to request, added format to realtime

app/config/collections.old.php, app/init.php
Fixes security weakness as mentioned at #2603
Cross fingers that tests are passing 😉. Everything should be fine, I might need to test the realtime test that is using `appwrite.test` as origin, but I want to see how it acts before I change it.
#2603
Many times.
=> Removed Appwrite Default Domains

docs/references/teams/update-team-membership-status.md
It adds an important detail to the docs for the Update Team Membership Status endpoint
None
Yes
=> Add important detail

app/controllers/api/users.php, app/workers/deletes.php
Fixes a bug in the deletes worker where the user and their session were not deleted.
N/A
YES
=> fix: reset user attributes and delete sessions when deleting a user

docker-compose.yml
Fixed the usage container entrypoint in dev mode
N/A
N/A
Yes
=> Fixed usage entrypoint in dev mode

app/views/console/database/collection.phtml, app/views/console/database/document.phtml
- fixes cast for float/int input fields in the console
#2590 
✅
=> fix: ui for int/float default values

app/controllers/general.php
Fix V08 response filter fallthrough
Yes
=> Fix V08 response filter fallthrough

app/views/console/users/index.phtml, app/views/home/auth/recovery/reset.phtml, app/views/home/auth/signin.phtml, app/views/home/auth/signup.phtml
Updated the console validations to match #2439 
N/A
#2439 
Yes.
=> Updated password length min requirment in the console

app/executor.php, app/views/install/compose.phtml, docker-compose.yml
=> feat: refactor some of the executor

docs/references/account/delete-session.md
Updates the description for deleting the current session
=> docs: update description for delete session endpoint

app/init.php, app/realtime.php, composer.json, composer.lock, src/Appwrite/Resque/Worker.php
This PR adds database reconnection logic to the realtime server. This was accomplished by adding a check in the database library to see if a collection exists.
Verified the reconnection works on startup.
Seldomly I have issues with the usage worker failing because a query executes before telegraf is ready. I couldn't reproduce this reliably, but I want to fix that too. 🙃 
https://github.com/utopia-php/database/pull/102
Yes.
=> Feat: retry db connection in realtime server

README-CN.md, README.md
Adds Chinese translation to README for our Chinese community members
翻译了README文档。我没有在中文语言环境开发的经验，欢迎与我用中文沟通以及帮我差错
N/A
Although detailed reviews from other experienced Chinese developers would be nice.
欢迎有在中文环境下开发的朋友们为我差错，纠正用词。
#2584
=> Adds Chinese translations to README

README-CN.md, README.md
Translations should be easier to find, and easily identified for non-english speakers.
This PR makes small changes to the two readme files to move the translation links to a more visible location
Yes
=> moved translation links to a more visible location

app/views/console/database/collection.phtml
- fix default value on UI if its disabled
- #2677 
✅
=> fix: ui boolean default values

app/controllers/api/functions.php, app/views/install/compose.phtml, src/Appwrite/Event/Event.php, tests/resources/docker/docker-compose.yml
Address comments in `builds-worker`
Use Existing tests
https://github.com/appwrite/appwrite/pull/2675
Yes
=> Feat add builds worker

app/controllers/mock.php
Quick code quality improvement for my last PR
=> OAUTh: Code  cleanup

README.md
Updates the status badge for passing tests on the master branch
=> docs: update status badge for tests

app/executor.php
This PR reintroduces the entrypoint environment variable for build stages fixing a number of runtimes
=> Feat fix build entrypoint

app/views/install/compose.phtml, docker-compose.yml
The existing compose file has appwrite-usage rely on the redis container, however, no redis connection env variables are being passed in. This just includes them for instances where you're using an external redis instance.
No testing is needed. It's just passing the environment variables in.
None
=> Update usage container to include redis vars

CHANGES.md, README-CN.md, README.md
- updates the readme files
- update the changelog
=> chore: release 0.12.2

app/controllers/api/functions.php, tests/e2e/Services/Functions/FunctionsCustomClientTest.php, tests/e2e/Services/Functions/FunctionsCustomServerTest.php, tests/e2e/Services/Realtime/RealtimeCustomClientTest.php, tests/e2e/Services/Webhooks/WebhooksCustomServerTest.php
All description from https://github.com/appwrite/appwrite/pull/2712 applies.
=> Improved deployment and build path structure

app/config/collections.php, app/controllers/api/functions.php, app/views/console/functions/function.phtml, app/workers/builds.php, src/Appwrite/Utopia/Response/Model/Deployment.php
All description from https://github.com/appwrite/appwrite/pull/2731 applies
=> Renamed 'deploy' to 'activate'

app/config/collections.php, app/controllers/api/teams.php, tests/e2e/Services/Teams/TeamsBaseClient.php
- adds `search` attribute to memberships
- adds fulltext index on `search` to memberships
- fixes team read permissions on migration
- fixes team update membership roles
E2E tests addded
#2789 
✅
=> fix: team membership roles & search

app/controllers/api/storage.php, app/controllers/shared/api.php, src/Appwrite/Messaging/Adapter/Realtime.php, tests/e2e/Services/Realtime/RealtimeCustomClientTest.php
Updates Realtime according new refactor
Related tests updated
https://github.com/appwrite/appwrite/pull/2769
YES
=> storage realtime event refactor

CHANGES.md, README-CN.md, README.md
=> chore: update readme for 0.12.3

app/controllers/general.php
Makes code a little bit more readable, removing unnecessary action
Manual QA on DO to make sure cert generation works
x
✅
=> Improved Token passing

composer.lock
Fix failing HTTPS cert generations due to library version missmatch.
Manual QA on DO:
x
✅
=> Updated composer lock

CONTRIBUTING.md
Adds line breaks to CONTRIBUTING.md in the PR instructions.
None
None
Yes
=> Add line breaks in CONTRIBUTING.md

app/tasks/usage.php, app/workers/builds.php
- fixes usage tags renamed to deployments, I thought this was fixed 🤔 
- passing the missing entrypoint param while calling createRuntime
YES
=> fix usage for tags deployments, pass entrypoint to runtimes

app/controllers/general.php
0.11 code readability improvement
Current tests
x
✅
=> Code cleanup

app/config/errors.php, app/controllers/api/account.php, app/controllers/api/functions.php, app/controllers/api/graphql.php, src/Appwrite/Extend/Exception.php
=> feat: add missing error codes

app/controllers/mock.php
Adds other expected attributes for large file upload mock endpoint
Related https://github.com/appwrite/sdk-generator/pull/388
Yes
=> Add other expected attributes for large file upload mock endpoint

app/views/console/functions/function.phtml
In UI we showed a command for creating execution using CLI, but it was missing the required parameter `activate`.
x
x
✅
=> Update create deployment docs

app/controllers/api/storage.php
Default Preview Logos were always on Local so was causing issue when using DO and S3
YES
=> default previews fix when files set on external storage

app/controllers/api/storage.php, docker-compose.yml
Fix executor when using S3 or DO
Manual QA
x
✅
=> Fix executor env vars

app/controllers/api/functions.php
`else`statement also expects it to be boolean. This converts to booelan before if/else, so its boolean in both
Manual QA
x
✅
=> Fix: Deployment activate param

CHANGES.md
=> chore: changelog for 0.13

app/views/install/compose.phtml
=> Feat 0.13 sync environment variables

app/config/platforms.php, docs/sdks/dart/CHANGELOG.md, docs/sdks/dart/EXAMPLES.md, docs/sdks/flutter/CHANGELOG.md, docs/sdks/flutter/EXAMPLES.md
Updates to changelog and minor SDK content updates
YES
=> Changelog for Flutter and Dart and some minor updates to Examples

app/config/platforms.php, docs/examples/0.13.x/client-flutter/examples/storage/create-file.md, docs/examples/0.13.x/server-dart/examples/functions/create-deployment.md, docs/examples/0.13.x/server-dart/examples/storage/create-file.md, docs/sdks/dart/CHANGELOG.md, docs/sdks/flutter/CHANGELOG.md
Flutter And Dart SDK updates. We need to merge and release new version of SDK generator to get this ready
[(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)
](https://github.com/appwrite/sdk-generator/pull/395)
YES
=> dart flutter fix

app/executor.php, src/Executor/Executor.php
1. Respect timeout environment variable in the API validators when set . 
2. Fix an uncaught exception
3. Increase Maintenance interval duration.
4. Set default value for execution `data` field
=> feat: fix timeout issues

.github/ISSUE_TEMPLATE/bug.yaml
=> chore: add 0.13.x to issue template

README.md
It seems you are missing a comma. Consider adding a comma.
=> Punctuation error

app/views/console/database/collection.phtml, app/views/console/database/document.phtml
- removes the step limit
#2764 
✅
=> fix: ui float input field

src/Appwrite/Utopia/Response/Model/AttributeBoolean.php, src/Appwrite/Utopia/Response/Model/AttributeEmail.php, src/Appwrite/Utopia/Response/Model/AttributeEnum.php, src/Appwrite/Utopia/Response/Model/AttributeFloat.php, src/Appwrite/Utopia/Response/Model/AttributeIP.php, src/Appwrite/Utopia/Response/Model/AttributeInteger.php, src/Appwrite/Utopia/Response/Model/AttributeURL.php
Updates extended attribute response models to provide appropriate example to give a proper example
https://appwrite.io/docs/models/attributeList
N/A
YES
=> update attribute examples

composer.json, composer.lock, tests/e2e/Services/Users/UsersBase.php
- adds tests for user search
- upgrade to new database library
- added tests for email
- #2394 
- https://github.com/utopia-php/database/pull/113
✅
=> fix: user search

app/controllers/general.php, app/executor.php, app/http.php, app/realtime.php, composer.json, composer.lock
This PR adds a 'detailedTrace' extra for the logging library so we can pick apart the stack traces for certain adapters such as Sentry so we can individually send what file caused it, what line number and other various pieces of data.
Yes, I have
=> Add a 'detailedTrace' extra for the logger library

app/views/console/storage/bucket.phtml
=> - Fix preview-image

app/controllers/general.php
=> feat: added comment about rethrowing PDO exception

app/controllers/api/storage.php
Fix bucket permission issues on createFile
#2949 
#2905 
YES
=> fix missing auth skip while getting bucket

README-CN.md
The parenthesis in Chinese are different from those in English. I found a few broken links in the Readme, which should now be fixed.
Nope
YES
=> Fix broken link in Chinese readme

app/tasks/usage.php
- fix using internal id for sub collection names, seems we missed this change in the usage worker before
YES
=> Fix usage worker to use Internal Id

public/scripts/views/forms/oauth-custom.js, src/Appwrite/Auth/OAuth2/Microsoft.php
1. Updated the keys in the Apple OAuth form to comply with their usage in the code
2. Updated the keys in the Microsoft OAuth form to be consistent with the one on Apple
3. Added the `JSON_THROW_ON_ERROR ` flag to `json_decode` to ensure errors are thrown.
NA
NA
YES
=> feat: update Microsoft OAuth Adapter

app/controllers/api/projects.php, app/controllers/api/storage.php, app/http.php
- Add missing attributes keys while creating default collections 
YES
=> Add missing default and format attribute keys

app/config/variables.php
We were missing a category in docs. Now it is there.
x (reported on Discord)
✅
=> Fix: Env vars config miss-structured

docs/references/account/update-session.md
Adds endpoint description of recently added update session endpoint.
x
Yes
=> Fix: update session docs

CHANGES.md, app/config/collections.php, app/controllers/api/account.php, app/controllers/api/projects.php, src/Appwrite/Utopia/Response/Model/Project.php
This PR will rename the project's 'providers' to 'authProviers' to prevent conflicts from arising in the future.
No tests have been written for this change.
Yes, I have.
=> Rename 'providers' to 'authProviders'

app/controllers/api/projects.php, src/Appwrite/Extend/Exception.php
- Prevent creating a project with `console` as ID. making `console` a reserved project ID
YES
=> CustomId console, reserved project

app/controllers/api/health.php, app/realtime.php, docs/references/health/get-queue-usage.md, src/Appwrite/Event/Event.php, tests/e2e/Services/Health/HealthCustomServerTest.php
- removes unused usage queue references
- removed tests
✅
=> fix: remove usage queue

app/controllers/api/account.php, tests/e2e/Services/Account/AccountBase.php
- verify email when magic url is used
- `countryName` now properly accessed
- extended tests for magic url
- #3130 
✅
=> fix(account): magic url and sessions locale

docs/sdks/python/GETTING_STARTED.md
=> docs: update typo on getting started page

app/views/console/database/document.phtml
- redirect to documents list after creating
- show success alert when updating document
- manual
✅
=> fix(ui): document crud redirect

app/controllers/api/users.php, tests/e2e/Services/Account/AccountBase.php, tests/e2e/Services/Account/AccountCustomClientTest.php, tests/e2e/Services/Account/AccountCustomServerTest.php, tests/e2e/Services/Users/UsersBase.php
- fixes the aggregation of the `search` filed when updating name and email for users
- extended tests
- #2974 
✅
=> fix(user): search integrity

app/controllers/api/locale.php
=> Refactor code for locale

app/controllers/api/health.php
Refactors and cleans up code in health.php
Manual 
- Checked if the IDE is still able to pickup/identify the params.
NIL
Yes
=> Refactor `health.php`

app/controllers/api/projects.php
Refactors `projects.php`
Manual
- checked if the IDE is still able to pickup params + builds locally
NIL
yes
=> Refactor `projects.php`

app/controllers/api/storage.php
Refactors `storage.php`
Manual
- checked if the IDE is still able to pickup params
NIL
yes
=> Refactor `storage.php`

app/controllers/api/teams.php
Refactors and cleans up code in `teams.php`
Manual 
- Checked if the IDE is still able to pickup/identify the params.
NIL
Yes
=> Refactor `teams.php`

app/config/collections.php, app/controllers/api/account.php, app/controllers/api/teams.php, app/controllers/api/users.php, app/init.php, app/workers/deletes.php
Implement subquery for memberships (users) so we no longer need to keep duplicate data.
- Current tests must pass
x
Yes
=> Feat: User membership subquery

app/controllers/api/functions.php
Tiny wording fix, don't like `deploy deployment` version.
x
x
Yes
=> Fix: Error wording

app/controllers/api/projects.php, composer.lock, tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
The logic remains the same, but max length was extracted into the library.. So it can be removed from Appwrite.
- To be sure, tests were added for too long hostname
- Current tests must pass
x
Yes
=> Feat: Upgrade hostname validator

app/controllers/api/account.php, src/Appwrite/Migration/Version/V13.php
=> fix: OAuth2 verification

app/controllers/general.php, composer.lock, src/Appwrite/Utopia/Request/Filters/V14.php, src/Appwrite/Utopia/Response/Filters/V11.php, src/Appwrite/Utopia/Response/Filters/V12.php, src/Appwrite/Utopia/Response/Filters/V13.php
Adds backward compatibility for people using Appwrite 0.14.x server, but 0.13.x-compatible SDK.
x
💯
=> Added backwards compatibility (response&request)

README.md
Update readme with new link for release 0.14 announcement
=> Update to include new release blog for 0.14

app/config/platforms.php, app/controllers/api/database.php, composer.json, composer.lock
* Removed redundant call to `orderAttributes` validator
* Update SDK  generator version
* Update android SDK version
=> feat: remove redundant order attributes validation

.github/ISSUE_TEMPLATE/bug.yaml
Add 0.14 version to bug report
None
x
Yes
=> Fix: Update Report Form

app/workers/functions.php
=> fix: scheduled functions execution

src/Appwrite/Migration/Migration.php, tests/unit/Migration/MigrationTest.php
- improve migration speed
- skip nested document migration, since we now use sub-queries
- improved the recursive array diff method
- manually
✅
=> feat: improve migration speed

tests/unit/Network/Validators/CNAMETest.php
Updates the CNAME testing domain to one that is active again
No test additions, just fixing a previously broken test
Yes
=> Update CNAME test domains

app/controllers/api/users.php, phpunit.xml, tests/unit/Network/Validators/CNAMETest.php
=> refactor `users.php`

docs/sdks/dart/GETTING_STARTED.md
Fix a small typo error in getting started for sdk-for-dart
N/A
https://github.com/appwrite/sdk-for-dart/issues/21
Yes
=> fix small typo error dart

.gitpod.Dockerfile, .gitpod.yml
Support quicker gitpod workspace prebuild and load for users
Largely iterative building and executing within the workspace to get an idea of average performance and if improvement in time to coding can be lowered
Slow workspace prebuilds reported in Gitpod discord.
Yes!
=> chore: enhance gitpod Dockerfile steps for prebuilds

.github/workflows/linter.yml, app/workers/audits.php, composer.lock, phpcs.xml, src/Appwrite/Auth/Auth.php, src/Appwrite/Auth/OAuth2/Tradeshift.php, src/Appwrite/Event/Event.php, src/Appwrite/Extend/Exception.php, src/Appwrite/Migration/Version/V13.php, src/Appwrite/Resque/Worker.php, src/Appwrite/Utopia/Response.php, src/Appwrite/Utopia/Response/Model.php, src/Executor/Executor.php, tests/e2e/Client.php, tests/e2e/Services/Account/AccountBase.php, tests/e2e/Services/Webhooks/WebhooksCustomClientTest.php, tests/e2e/Services/Webhooks/WebhooksCustomServerTest.php
Fixes Linter issues , makes codebase more compliant to PSR12 coding standards
Manual
NIL
Yes
=> fix: linter issues

app/views/console/functions/function.phtml
Fix incorrect deploy command shown during function deployment. 
Manual QA
N/A
Yes
=> Fix function deploy directory

docs/sdks/flutter/GETTING_STARTED.md
This PR make some changes on getting started with appwrite in Flutter acc to [issue 58]( https://github.com/appwrite/docs/pull/58) on `appwrite/docs`
=> Update GETTING_START.md for flutter

app/config/storage/logos.php
fixes failing linter tests
Manual
NIL
Yes
=> fix : linter issues

tests/e2e/Services/Database/DatabaseBase.php
=> null on default tests

.phpunit.result.cache, src/Appwrite/DSN/DSN.php, tests/unit/DSN/DSNTest.php
Add a new DSN class to allow parsing of DSN strings
Wrote unit tests
NA
YES
=> feat: add DSN

app/config/collections.php, app/controllers/api/database.php, app/init.php
Adding Internal Ids to Database Api Collections, Attributes, Indexes.
=> Feat internal ids Database Api

app/views/console/webhooks/webhook.phtml
Add UI for Webhook Signature Keys
Yes
=> Add UI for Webhook Signature Keys

docs/sdks/web/GETTING_STARTED.md
Updates examples to new webSDK syntax.
Not tested, not sure now. Should be fine? Nothing too crucial.
- https://github.com/appwrite/sdk-generator/pull/464
Yes
=> Fix: Web SDK examples

composer.lock, docs/tutorials/add-oauth2-provider.md, docs/tutorials/add-runtime.md, docs/tutorials/add-translations.md
- Runs linter on code example
- Add missing methods from OAuth2 class
- Fix bugs in the example
x
Yes
=> Fix: OAuth provider docs

app/controllers/api/projects.php
=> fix usage stats on dashboard

app/init.php, app/views/console/database/collection.phtml, app/views/console/database/document.phtml, app/views/console/functions/function.phtml, app/views/console/storage/bucket.phtml, app/views/console/users/index.phtml, app/views/console/users/team.phtml, app/views/console/users/user.phtml, composer.lock
=> feat: add analytics label for view as JSON

app/views/console/databases/database.phtml
- Fix redirection on Database deletion
UI only fix
YES
=> fix database deletion redirection

app/config/variables.php
Updates environment variable description to fix typo and clarify language.
Passed through Grammarly.
https://github.com/appwrite/docs/pull/207
=> Update _APP_FUNCTIONS_RUNTIMES to fix typo and clarify description

app/controllers/general.php, src/Appwrite/Utopia/Response/Filters/V14.php
=> feat: 0.15.x response filters

app/controllers/api/account.php
Trigger Messaging worker when creating phone verification
NA
NA
YES
=> feat: trigger sms for createVerification

app/config/platforms.php, composer.json, composer.lock
- bump node version number
- update sdk-generator
✅
=> feat: node sdk version 7.0.1

src/Appwrite/Migration/Version/V14.php
- uses correct internal id for migration
- manual ✅ 
✅
=> fix: internal attribute and index key on migration

app/views/console/databases/document.phtml
- add aatabaseId to delete document
#3462 
✅
=> fix(ui): delete document

app/config/platforms.php, composer.json, composer.lock
=> chore: bump sdk versions

app/views/console/databases/collection.phtml
=> fix(ui): document link

README-CN.md, README.md
Update links to example compose file to point at the autogenerated one from Appwrite's homepage.
Addresses issue outlined in https://github.com/appwrite/appwrite/issues/3453.
=> Update link in readme to example compose file

app/views/console/databases/index.phtml
This PR fixes the typo in database create success alert message
Yes
=> fix: typo in database create success alert message

README.md
Lists real-time as a service to README
None
None
Yes
=> Added realtime services to README

docs/services/storage.md
=> docs(storage): fix link to databases page

app/views/console/databases/collection.phtml
=> fix(ui): redirect after deleting collection

app/realtime.php, tests/e2e/Services/Realtime/RealtimeConsoleClientTest.php
- since the `console` project cannot be found anymore, I added a case for it to manual authentication
- added test
✅
=> fix: realtime authentication on console

app/tasks/usage.php
=> set proper log namespace

src/Appwrite/Auth/Phone/Telesign.php
Corrects TeleSign reference material link (currently it links to Twilio docs)
No testing necessary
None
Yes
=> Fix: Correct TeleSign reference material link

CONTRIBUTING.md, composer.json
- adds handy scripts to composer
- manually
✅
=> feat: composer scripts

app/controllers/api/databases.php
=> Fix attribute databaseId

src/Appwrite/Migration/Version/V14.php
- fixes migration of attributes and indexes
- both where not completely migrated due to re-creation of the document invalidating the cursor pagination
- manually
- #3482 
✅
=> fix: migration of attributes and indexes

CONTRIBUTING.md
The old instructions for generating new specifications + new SDK no longer work. This aims to update the instructions.
Update instructions to generate swagger specs and SDK. Let me know if these look correct, not sure if this is the exact procedure.
=> Update instructions to generate new specifications

app/config/platforms.php, composer.json, composer.lock
Bumps our SDK Generator version to the latest and updates the CLI Version number to the current one
Yes
=> Update SDK generator to 0.19.6 and bump CLI version

app/controllers/mock.php
- Make the mock download endpoint response consistent with the rest of responses
Blocks https://github.com/appwrite/sdk-generator/pull/439
=> Consistent response for mock download

src/Appwrite/Utopia/Response/Model/Deployment.php
The deployment object has no list of valid status codes. This makes it difficult to create conditionals when handling responses from SDK.
This is a temporary solution. What we should have is:
- Enums for possible status code for each resource (can they be common?).
- Dedicated descriptions for each status code.
- Autogenerated documentation page.
The above will be pitched as a separate issue.
=> Add possible status codes to deployment object.

src/Appwrite/Utopia/Response/Model/Deployment.php
This updates the deployment object model example, returned for function deployment events.
This update will apply after the console spec files are updated.
Preview below.
=> Deployment object model example updated

app/workers/deletes.php
The property isn't used anymore
Existing Tests
YES
=> Remove unused property

app/views/home/auth/recovery/reset.phtml
Fixes the Alert and Redirect of Successful Password resets in Appwrite
Yes
=> Fix password reset redirect and alert

src/Appwrite/Utopia/Response/Model/AttributeEmail.php, src/Appwrite/Utopia/Response/Model/AttributeEnum.php, src/Appwrite/Utopia/Response/Model/AttributeIP.php, src/Appwrite/Utopia/Response/Model/AttributeURL.php
This PR removes constants from response models
Yes, I have
=> Remove constants from response models

app/views/console/comps/header.phtml, app/views/console/users/index.phtml
This PR renames the Users page to Authentication in the sidebar and main page title.
Yes, I have
=> Rename users page to Authentication

docs/references/avatars/get-flag.md, docs/services/locale.md
Our 2 letter country codes now follow a standard. This gives users a way to lookup country codes :)
=> Add country code spec link to local and flag endpoint

app/views/install/compose.phtml, docker-compose.yml
- upgrades mariadb to `10.8.3`
- upgrades redis to `7.0.4`
- manual
- existing tests
✅
=> feat: upgrade mariadb and redis

src/Appwrite/Specification/Format/OpenAPI3.php, src/Appwrite/Specification/Format/Swagger2.php
Updates datetime example for specs
Existing tests
https://github.com/appwrite/appwrite/pull/3516
Yes
=> Update specs datetime example

public/scripts/services/date.js
Update following datetime merge for the `date` service:
- Use client languages
- Use client timezone 
Existing tests
https://github.com/appwrite/appwrite/pull/3516
Yes
=> Fix console date service locale usage

app/controllers/api/databases.php, app/controllers/api/functions.php, app/controllers/api/storage.php, app/controllers/api/teams.php, app/controllers/api/users.php
Fix "only variables can be passed by reference" errors
Existing tests
Yes
=> Fix reset error

app/controllers/mock.php
Mock headers endpoint
https://github.com/appwrite/sdk-generator
YES
=> mock headers endpoint

CHANGES.md
=> Changelog 0.16.x

src/Appwrite/Utopia/Response/Model/Bucket.php
Fix bucket response model `fileSecurity` property
Tested via SDKs
Yes
=> Fix filesecurity response type

.github/workflows/linter.yml
- Use composer docker image to run lint to fix intermittent issues with action
This PR will test it
Yes
=> Fix lint action

app/controllers/api/avatars.php
The default gray color on the Avatars API has a poor contrast on the UI and offers poor readability of the text. This PR replaces the default color to Pink to solve the issue
=> feat: update default avatars color

docs/sdks/dart/CHANGELOG.md, docs/sdks/flutter/CHANGELOG.md
Updated Flutter and Dart changelog 
NA
NA
YES
=> feat: update dart and flutter changelog

app/views/console/databases/collection.phtml, composer.lock
Remove negative margin from the settings card to keep it consistent with the other screens
=> feat: fix margin on collection settings

app/controllers/api/databases.php, app/controllers/web/console.php, app/views/console/databases/collection.phtml, app/views/console/databases/document.phtml, app/views/console/databases/form.phtml, src/Appwrite/Messaging/Adapter/Realtime.php, src/Appwrite/Utopia/Response/Model/Document.php, tests/e2e/Services/Databases/DatabasesBase.php
1. Rename document.$collection to document.$collectionId
2. Add document.$databaseId
Updated Test Cases
* https://github.com/appwrite/appwrite/issues/3484
Yes
=> Update document model

app/views/console/comps/permissions-matrix.phtml
Increase margin above add role button
Manual test
Yes
=> Fix permissions UI margin

CHANGES.md, src/Appwrite/Migration/Version/V15.php
- fixes missing migration of `time` column in abuse
- manual
✅
=> fix: migration for abuse time column

README-CN.md, README.md
- update readmes to use `1.0.1`
✅
=> chore: update readme for 1.0.1

docs/sdks/cli/GETTING_STARTED.md, docs/sdks/dart/EXAMPLES.md, docs/sdks/flutter-dev/EXAMPLES.md, docs/sdks/flutter/EXAMPLES.md, docs/services/databases.md, docs/services/storage.md
Update some references to `role:all` to `any`.
None
None
Yes
=> Change role:all to any in docs

CONTRIBUTING.md, README.md
Updated the typo mistake in readme.md file.
=> Typo fix readme.md file

docs/sdks/flutter/GETTING_STARTED.md
Fix our flutter getting started to patch the flutter_web_auth_2 [instructions](https://pub.dev/packages/flutter_web_auth_2#web).
None
None
Yes
=> Update flutter getting started to match library

app/config/variables.php
Update list of supported providers based on:
https://github.com/appwrite/appwrite/blob/939b5a00f5a87c3a16a70adb201d5d1c4b9a013e/app/init.php#L1032-L1036
None
None
Yes
=> Update list of supported SMS Providers

app/config/platforms.php, composer.json, composer.lock
Update SDK generator and versions
Not required
Supercedes https://github.com/appwrite/appwrite/pull/3897
Yes
=> Update SDK generator and versions

app/config/platforms.php, composer.json, composer.lock
Update the sdk generator
NA
NA
YES
=> chore: update sdk generator

README.md
=> Add ProductHunt badge

src/Appwrite/Utopia/Response/Filters/V15.php, tests/unit/Utopia/Response/Filters/V15Test.php
Fix:
1. Document $collectionId to $collection
2. Fix empty DateTimes to 0
Unit tests
None
Yes
=> Fix response filters

app/workers/messaging.php
Updated the reference of  [class](https://github.com/appwrite/appwrite/issues/3859#issuecomment-1249833928).
Tested it and it works fine✌️.
=> Fixed the bug #3859

CONTRIBUTING.md, app/config/providers.php, src/Appwrite/Extend/Exception.php
**It fixes a small typo's in files.**
**Updated the typo's**
**Yes, I have read the [Contributing Guidelines](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)**
=> fixed typo 

docs/sdks/dart/CHANGELOG.md, docs/sdks/flutter/CHANGELOG.md
=> update Flutter/Dart changelogs

app/config/providers.php
=> Fixed typo in providers.php

README-CN.md
=> doc_update_readme

app/config/events.php
=> Fixed typo in events.php

docker-compose.yml
Fixed typo in docker-compose.yml
=> Fixed typo in docker-compose.yml

src/Appwrite/Extend/Exception.php
=> Fix typo in Exception.php

app/controllers/api/functions.php
Rename retry build to create build
Yes
=> Rename retry build to create build

CHANGES.md, app/controllers/api/databases.php, composer.lock, tests/e2e/Services/Databases/DatabasesBase.php
- fixes default value for attributes being `false`
- adds tests for creating boolean attribute with `false`
- #4039 
✅
=> fix: boolean attribute default value

app/config/collections.php, composer.lock, src/Appwrite/Utopia/Database/Validator/Queries/Projects.php, tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
Allows to query projects by teamId. Useful for new console.
x
Yes
=> Feat: teamId queries on listProjects

CONTRIBUTING.md, README.md, docs/services/account.md, docs/services/avatars.md
I have fixed some minor typos and rephrased words
Yes, I have read the [Contributing Guidelines](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)
cc @adityaoberai
=> Fixed Typo's and Rephrased words

src/Appwrite/Specification/Format/OpenAPI3.php, src/Appwrite/Specification/Format/Swagger2.php
This PR adds meaningful examples to the phone number string in auth examples. The phone number used is `+12065550100`, this is a US phone number, starting with 555, which is reserved like example.com to be an invalid number.
Example before this change: 
```js
import { Client, Account } from "appwrite";
const client = new Client();
const account = new Account(client);
client
.setEndpoint('https://[HOSTNAME_OR_IP]/v1') // Your API Endpoint
.setProject('5df5acd0d48c2') // Your project ID
;
const promise = account.createPhoneSession('[USER_ID]', '');
promise.then(function (response) {
console.log(response); // Success
}, function (error) {
console.log(error); // Failure
});
```
Example after this change
```js
import { Client, Account } from "packageName";
const client = new Client();
const …
```
=> Add meaningful phone number to generated examples.

tests/e2e/General/HTTPTest.php
Fix spec tests due to a change in response format from https://validator.swagger.io/
Existing tests
Not public facing
Yes
=> Fix spec tests

app/cli.php, app/tasks/usage.php, src/Appwrite/Usage/Calculators/Aggregator.php, src/Appwrite/Usage/Calculators/Database.php, src/Appwrite/Usage/Calculators/TimeSeries.php, tests/e2e/General/HTTPTest.php
Reverts appwrite/appwrite#4545
=> Revert "Fix usage on DB Pools"

app/controllers/api/functions.php, app/workers/builds.php, src/Appwrite/Utopia/Response/Model/Deployment.php, tests/e2e/Services/Functions/FunctionsCustomServerTest.php
This PR adds the build time to deployments for easier access
Yes
=> Add build time to deployments

README-CN.md
Adds announcement for 1.0!!!!!
=> Update Chinese README-CN.md

app/controllers/api/account.php
Updated the naming of some of our account routes to become more consistent with other services.
N/A
N/A
Yes
=> Updated titles on account routes

app/controllers/api/projects.php, src/Appwrite/Utopia/Response/Model/UsageProject.php, tests/e2e/General/UsageTest.php, tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
- adds databases and buckets to project usage
- adapted tests
✅
=> feat: add databases and buckets to projects usage

src/Appwrite/Usage/Stats.php
* Fix difference in naming
YES
=> fix difference in naming in inbound and outbound usage metrics

SECURITY.md
We typically support the latest version of Appwrite and 1 minor version back. It seems like this file was not updated for some of our recent releases.
None
None
Not needed
Yes
=> Update supported versions in security policy

README-CN.md, README.md, SECURITY.md
=> sync: 1.1.x

app/cli.php
Adds retry logic to tasks.
Goal of this PR is to fix failing tests.
x
Not user facing changes.
Yes
=> Add retry logic to CLI

app/cli.php, docker-compose.yml
=> fix: volume sync

.gitpod.yml
Adds submodule pull into rebuild, and fixes order of Docker pull&build (pull didn't run properly)
x
No, not user-facing change.
Yes
=> Fix: Gitpod prebuilds

Dockerfile, composer.lock
Added a new build arg for the appwrite console
NA
NA
YES
=> feat: add build args for console

src/Appwrite/Usage/Calculators/TimeSeries.php
=> fix project Id issues

app/controllers/api/project.php
=> fix hourly stats

app/workers/functions.php, src/Executor/Executor.php
=> Improve: Executor error handler

app/config/errors.php
Using vague terms like "check the docs" is poor SEO. This makes some small phrasing changes so developers can get more accurate searches.
=> Updated the error descriptions for better SEO.

docs/sdks/nodejs/GETTING_STARTED.md
See https://github.com/appwrite/sdk-for-node/pull/43
=> Fixed README documentation

README-CN.md
Removed invalid link from readme
=> Remove invalid link

src/Appwrite/Migration/Version/V17.php, tests/unit/Docker/EnvTest.php
Implement auto-migration for differences between 1.2.x and master
=> Feat: 1.2.x migrations

.gitmodules
Upgrade to new console release.
=> Upgrade console

.gitmodules
=> Feat: console upgrade 2.1.1

src/Appwrite/Migration/Version/V17.php
FIx warning in migation, not migratin mimeType
=> Fix: 1.2.x migration

src/Appwrite/Utopia/Response/Model/Project.php, tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
=> Fix: auth session limit model

docs/sdks/dart/CHANGELOG.md, docs/sdks/flutter/CHANGELOG.md
Adds changelog for Flutter and Dart
=> Fix: SDK changelogs

composer.lock
Upgrade SDK generator to include GraphQL fix needed for homepage
=> Feat: Upgrade SDK generator

docs/sdks/flutter/GETTING_STARTED.md
Update docs used in sdk-generator.
=> Fix:getting started docs

app/config/variables.php
Moves vars varegory to root level to properly render in docs
=> Fix missing env var category

composer.json, composer.lock
Update storage to fix bug with S3 provider paths.
Closes: https://github.com/appwrite/appwrite/issues/3433
CI
* https://github.com/appwrite/appwrite/issues/3433
Yes
=> Bump utopia-php/storage

app/controllers/api/account.php, app/controllers/api/teams.php, app/controllers/shared/api.php, app/workers/certificates.php, app/workers/mails.php, src/Appwrite/Event/Mail.php
Refactor to make mails event and worker more general
=> refactor: make mails event and worker general

app/config/errors.php, app/controllers/api/account.php, src/Appwrite/Extend/Exception.php, tests/e2e/Services/Account/AccountConsoleClientTest.php
=> feat: update account codes

src/Appwrite/Platform/Tasks/Hamster.php
=> feat: add hamster script

dev/stats_2023-01-26.csv, src/Appwrite/Platform/Tasks/Hamster.php
=> Feat aggregate stats

app/init.php
This PR Updates the DBIP Database that Appwrite uses
=> Update DBIP Database

README-CN.md, README.md
- fix tests badge on readme
- manual
=> fix(readme): tests badge

src/Appwrite/Platform/Tasks/Hamster.php
=> feat: add hamster background task

src/Appwrite/Platform/Tasks/Hamster.php
=> feat: clear mail attachments

composer.lock
=> Update messaging + SDK generator

src/Appwrite/Network/Validator/Origin.php
- Fix validating origin for apple platforms
=> Fix validating origin for apple platforms

tests/extensions/TestHook.php
=> Feature slow test

Dockerfile, tests/extensions/TestHook.php
- Use Appwrite docker base `appwrite/base:0.1.0` image
No feature changes
=> build using appwrite base docker image

app/controllers/api/teams.php, docs/references/teams/create-team-membership.md, tests/e2e/Services/Teams/TeamsBaseClient.php
- Supports UserID, email and Phone in team invite
YES
=> Team Invite Improvements

.github/workflows/codeql-analysis.yml, .github/workflows/linter.yml, .github/workflows/tests.yml
It often doesn't make sense to wait until a test on an older commit finishes and it's best to cancel so that the workflows on the newest commit can run.
Manual:
As shown above, the in progress Tests and CodeQL workflows were cancelled because the code was modified and new workflows were initiated.
None
=> Update the github workflows to cancel if PR is modified

app/controllers/api/databases.php, src/Appwrite/Utopia/Database/Validator/IndexedQueries.php, src/Appwrite/Utopia/Database/Validator/Queries/Documents.php, tests/e2e/Services/Databases/DatabasesBase.php
Remove the requirement for list documents queries to made against attributes with an index
Existing tests
=> Remove indexed attribute query requirement

src/Appwrite/Platform/Tasks/Hamster.php
=> feat: update hamster scrpipt

src/Appwrite/Platform/Tasks/Hamster.php
=> feat: update docker image

app/config/collections.php, app/controllers/api/functions.php, app/workers/functions.php, composer.lock
=> Fix schedules functions

Dockerfile, composer.json, composer.lock
- https://github.com/appwrite/appwrite/issues/5213
=> Fix XML reading issue

app/config/platforms.php, composer.json, composer.lock, docs/sdks/dart/CHANGELOG.md, docs/sdks/flutter/CHANGELOG.md
=> For SDK release

Dockerfile, app/config/collections.php, app/controllers/api/functions.php, app/workers/builds.php, bin/patch-create-missing-schedules, bin/patch-delete-schedule-updated-at-attribute, src/Appwrite/Migration/Version/V17.php, src/Appwrite/Platform/Services/Tasks.php, src/Appwrite/Platform/Tasks/PatchDeleteScheduleUpdatedAtAttribute.php
Fix missing env variables on functions executed over scheduler.
x
=> Fix: scheduler env variables

app/controllers/api/databases.php, app/workers/databases.php, src/Appwrite/Utopia/Database/Validator/Queries.php, src/Appwrite/Utopia/Database/Validator/Queries/Base.php, src/Appwrite/Utopia/Database/Validator/Queries/Document.php, src/Appwrite/Utopia/Database/Validator/Queries/Documents.php, src/Appwrite/Utopia/Database/Validator/Query/Select.php, src/Appwrite/Utopia/Response/Model/AttributeRelationship.php, tests/e2e/Services/Databases/DatabasesBase.php
=> Feat relations updates

src/Appwrite/Platform/Tasks/Hamster.php
=> feat: update appwrite image

README-CN.md, README.md, composer.lock
Added hiring badge to the readme
=> feat: update readme

src/Appwrite/Migration/Version/V18.php
=> Add options key to attributes
