- .gitmodules
> feat: update console version

- .gitmodules
- app/config/services.php
> fix: console server duplicate key

- README-CN.md
- README.md
Updates blog link to Appwrite 1.3 announcement blog in Readme
Visible in Readme
None
> Fix: Update Appwrite 1.3 blog link in Readme

- CHANGES.md
- app/controllers/api/databases.php
- tests/e2e/Services/Databases/DatabasesBase.php
- Fix auto-setting custom ID on nested documents
- Added tests for nested ID not included
> Fix auto-setting custom ID on nested documents

- .github/workflows/release.yml
- Dockerfile
- only build console on host build architecture
- build release using CI
- manual
> ci: release action

- composer.lock
- src/Appwrite/Platform/Tasks/Hamster.php
> feat: upgrade hamster script

- src/Appwrite/Utopia/Response/Model/AttributeDatetime.php
This PR fixes the code for the example provided on this page -> https://appwrite.io/docs/models/attributeDatetime
- #5272 
Yes
> fix-models-attributeDatetime-object-example

- app/config/errors.php
Fixes the error description for duplicate user
Closes: https://github.com/appwrite/appwrite/issues/5147
Manual testing
* https://github.com/appwrite/appwrite/issues/5147
> fix error description for duplicate user

- app/config/platforms.php
- app/tasks/sdks.php
- composer.lock
- docs/examples/1.3.x/console-cli/examples/console/variables.md
1. Updated default branch for pushing sdks to `dev` instead of `main` or `master`
2. Updated CLI version
3. Updated git commands to only fetch the required branch rather than fetching all branches and tags  
4. Updated git commands to explicitly push to the branch of interest   
> feat: update cli version

- docs/sdks/apple/GETTING_STARTED.md
The method should be `registerOAuthHandler()`.
None
None
> Fix typo in Apple Getting Started

- CONTRIBUTING.md
The CLI expects name=value for arguments rather than just positional.
None
None
> Update CONTRIBUTING.md to fix specs command

- Dockerfile
Add public directory to the build image
> feat: update dockerfile to include public directory

- app/config/cloud/employees.json
- app/config/cloud/heroes.json
> Update cards emails

- app/controllers/api/avatars.php
> Fix bugs with cards

- docs/sdks/web/GETTING_STARTED.md
fix : wrong links for getting started for web
no code changes
#5359
> fix : wrong links for getting started for web

- app/controllers/api/databases.php
- tests/e2e/Services/Databases/DatabasesBase.php
Fix update document merging existing data after preprocessing instead of before
Added test
> Fix update document merging existing data after pre-processing

- CHANGES.md
> Update CHANGES.md to include team prefs fix

- app/config/errors.php
- app/controllers/api/projects.php
- app/workers/deletes.php
- src/Appwrite/Extend/Exception.php
Adds check to ensure custom domains cannot be created with using the domain from APP_DOMAIN or from other projects.
> feat: add checks for domain

- app/views/general/error.phtml
Button doesn't nessessarly take you to console. With problematic setup of oauth in developer's app, it may take you back to the app.
> Fix: OAuth error copy

- app/worker.php
- app/workers/functions.php
- composer.lock
- docker-compose.yml
Makes sure function errors are logged to Sentry
x
> Feat: Improve logs

- app/config/errors.php
- app/controllers/api/projects.php
- composer.lock
- phpunit.xml
- src/Appwrite/Extend/Exception.php
- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
> Feat update project creation

- app/controllers/general.php
- composer.json
- composer.lock
- tests/e2e/Client.php
- tests/e2e/General/HTTPTest.php
- tests/e2e/Scopes/Scope.php
- tests/e2e/Services/Databases/DatabasesBase.php
- tests/e2e/Services/GraphQL/StorageServerTest.php
- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
- Update framework to include a check to ensure that the matched URL has the same amount of segments (separated by /) as the route. This ensures that a URL will not match an incorrect route if parameters are missing.
- Add assertion to ensure routes are not mismatched
- Fixed existing tests
> Update framework to fix route mismatches

- app/workers/functions.php
Uses tag instead of extra in logging. That makes filtering and querying possible.
x
> Feat: Improve logging

- app/controllers/general.php
- app/controllers/web/console.php
- composer.lock
- tests/e2e/General/HTTPTest.php
- implement trailing wildcards
- fixes acme challenge
- fixes console deep link
- manual
*na*
> fix: trailing wildcards

- app/controllers/web/console.php
- tests/e2e/General/HTTPTest.php
> Fix the routing for the default OAuth2 pages

- app/controllers/api/projects.php
Fixed missing import of Utopia DateTime class
> fix: missing import

- app/config/errors.php
- app/controllers/api/databases.php
- src/Appwrite/Extend/Exception.php
Add new error message to differentiate between missing data and missing data _and_ permissions between document create and document update.
N/A
N/A
> Update document missing params error message

- app/controllers/api/storage.php
- app/workers/deletes.php
- separated  cache deleteCacheByDate() and cacheDeleteByResource() 
- added  cacheDeleteByResource()  to put file API
> cache deletion bug fix

- app/controllers/general.php
Adds info about database of a project into Sentry logs.
x
> Feat: Add database to log

- src/Appwrite/Platform/Tasks/Hamster.php
> fix: missing collection error

- app/controllers/api/projects.php
- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
- Password no longer required to delete project
- Updated existing test
- https://github.com/appwrite/appwrite/issues/5509
> remove password required for project deletion

- app/controllers/api/databases.php
- tests/e2e/Services/Databases/DatabasesCustomClientTest.php
Fixes updating relationship on delete parameter in two way type
Added E2E test case to verify if relationship is okay after updating or not 
[- (Related PR or issue)](https://app.asana.com/0/1204806686347431/1204464303389708)
> fixed relationship update bug in two way type

- app/controllers/api/users.php
Fix an error in invoking the Exception constructor
> feat: update error in Exception constructor

- docs/sdks/flutter/GETTING_STARTED.md
- Update macOS minimum requirement
- https://github.com/appwrite/sdk-for-flutter/issues/147
> Update Flutter GETTING_STARTED.md

- app/controllers/api/functions.php
- app/controllers/api/storage.php
- app/controllers/mock.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
- tests/e2e/Services/Storage/StorageBase.php
- Fixing chunked upload
- #5392 
- https://github.com/appwrite/sdk-generator/pull/648
> content-range end should be 1 less than file size

- app/config/collections.php
- app/controllers/api/account.php
- app/controllers/api/users.php
- app/controllers/shared/api.php
- app/init.php
- docs/references/users/update-user-labels.md
- src/Appwrite/Auth/Auth.php
- src/Appwrite/Utopia/Response/Model/Membership.php
- src/Appwrite/Utopia/Response/Model/User.php
- tests/e2e/Services/Account/AccountBase.php
- tests/e2e/Services/Users/UsersBase.php
- tests/unit/Auth/AuthTest.php
This labels attribute can be used apply labels to users. These labels can eventually be used:
* with permissions to grant access
* to filter users in the Users collection
Automated
Depends on:
* https://github.com/utopia-php/database/pull/280
Blocks:
* https://github.com/appwrite/console/pull/457
> Add a new labels attribute to the Users collection

- app/controllers/api/account.php
Fixes the expire format of Sessions for magic url api 
closes: https://github.com/appwrite/appwrite/issues/5428
> fix: expire format in magic url sessions

- app/controllers/api/account.php
Uses the userId to fetch the user to whom the account subscription event is to be sent.
- Fixes #5095
> fix: trigger account subscription event on email verification

- app/workers/deletes.php
`listByGroup()` didn't have any pagination queries so it was getting stuck in an infinite loop.
TBD
None
> Ensure deletes worker iterates over all schedules

- src/Appwrite/Utopia/Response/Model/Key.php
- src/Appwrite/Utopia/Response/Model/User.php
Add a note about how often the attributes are updated.
Tests should pass
- https://github.com/appwrite/console/pull/475
> Update description for User and Key accesedAt

- bin/upgrade
- src/Appwrite/Platform/Services/Tasks.php
- src/Appwrite/Platform/Tasks/Install.php
- src/Appwrite/Platform/Tasks/Upgrade.php
Before, we used the same command for both installation and upgrades. This lead to problems because developers would try to upgrade in the wrong folder and end up creating a new installation.
This new upgrade command validates the existence of an existing installation before proceeding with the upgrade to ensure no new installation is created when upgrading.
The following screenshot shows:
Running the upgrade command w/o an installation results in an error:
Installation still works:
Upgrading with an existing installation:
> Feat upgrade task

- app/workers/deletes.php
Previously we deleted all the project collections, but we didn't delete the project document from the console projects collection.
Fixes https://github.com/appwrite/appwrite/issues/5588
Manually deleted an org and then recreated the project with same ID.
- https://github.com/appwrite/appwrite/issues/5588
> Delete project when deleting org

- app/controllers/api/users.php
Fixes #5717
All automated tests should pass
- #5717
> Delete duplicate users endpoint

- app/controllers/general.php
- app/views/general/error.phtml
If an endpoint throws an exception, an error like this is shown:
This PR adds some styling so that the page matches the Console
Manual:
Prod mode:
Dev mode:
None
> Style Appwrite Error Page

- app/config/variables.php
To handle special characters like '@' or '/', the user and secret values must be URL encoded.
- https://github.com/appwrite/appwrite/pull/5916
> Update the docs for the _APP_SMS_PROVIDER env var

- app/config/locale/translations/pt-pt.json
Added missing word to Portuguese (pt-pt) email template
Fixes #5693
- #5693
> Added missing word to portuguese email template

- app/config/collections.php
- app/controllers/api/migrations.php
> Feat: Move oauth secret to identity

- docker-compose.yml
This PR fixes debugger usage in 1.4.x
> fixes debugger usage

- app/controllers/api/migrations.php
- app/controllers/general.php
- app/controllers/web/console.php
- app/init.php
- app/workers/builds.php
- composer.json
- composer.lock
- docker-compose.yml
- src/Appwrite/Auth/OAuth2/Firebase.php
- src/Appwrite/Messaging/Adapter/Realtime.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
> Fix Migrations Stability

- composer.json
- composer.lock
utopia/domains - latest release is 0.3.2
> Fix domains on cl 1.1.x

- docs/references/functions/create-build.md
Create build endpoint is currently missing a description. This fixes the problem by adding the required md file.
> Fix missing description for function create build endpoint

- README.md
Update after linode/akamai acquisition and rebrand:
Linode Storage is now -> Akamai Object Storage
Akamai/Linode is now -> Akamai Compute
> Update Akamai integration further according to their latest rebrand

- app/config/errors.php
- app/controllers/api/storage.php
- src/Appwrite/Extend/Exception.php
- tests/e2e/Services/Storage/StorageBase.php
- Fix upload file with colliding ID overwriting original
- Added test
> Fix colliding ID overrides

- CONTRIBUTING.md
I updated the documentation on building static files and redirecting to the correct repo.
NA
https://github.com/appwrite/appwrite/issues/5318
> Added Documentation change on static files

- docker-compose.yml
This PR updates appwrite assistant docker image version
> updates appwrite assistant docker image version

- docker-compose.yml
This PR updates assistant docker version 
> update assistant version

- app/controllers/api/avatars.php
- tests/e2e/Services/Avatars/AvatarsBase.php
> Check if host is public domain before requesting

- app/controllers/mock.php
- Add back headers route which was duplicated but both were removed instead of one
> Fix mock headers

- composer.json
- composer.lock
> Chore update migrations

- .github/workflows/cleanup-cache.yml
Workflow should trigger on pull_request.closed, not all pull_request.
None
- https://github.com/appwrite/appwrite/pull/6080
> Update the trigger for the cleanup actions cache workflow

- app/controllers/shared/api.php
The method has been removed since it's no longer necessary.
Ran `docker compose exec -T appwrite test --debug` locally:
- https://github.com/utopia-php/framework/pull/92
> Remove route setIsActive() call

- app/worker.php
> fix: make logger nullable in workers

- src/Appwrite/Migration/Version/V19.php
Skip the cache collection because:
1. There may be * in the $id of the document which causes problems when paginating with a cursor.
1. Nothing was done to the cache collection so we don't need to process it.
Before fix:
After fix, the migration is successful:
- https://github.com/appwrite/appwrite/issues/6140
> Override forEachDocument() to skip the cache collection

- app/views/install/compose.phtml
Add missing volumes as compared to the dev docker-compose.yml file.
Closes: https://github.com/appwrite/appwrite/issues/6132
Manual:
- https://github.com/appwrite/appwrite/issues/6132
> Fix Not Found error when deploying function from git

- src/Appwrite/Platform/Tasks/Schedule.php
> Add required params for scheduled functions

- app/config/errors.php
Explicitly list the environment variables that need to be configured to make it clear what needs to be done.
Closes #6136
Manual
- #6136
> Update the error message for router_domain_not_configured

- app/views/install/compose.phtml
- docker-compose.yml
The hostname used to be appwrite-executor so we'll change it back to what it was.
None
- https://github.com/appwrite/appwrite/issues/6137
> Change executor hostname back to appwrite-executor

- app/config/roles.php
Alloes console users to use assistant instead of project owners
* https://github.com/appwrite/appwrite/issues/6143
> Fix: AI Assistant

- app/controllers/api/teams.php
Make URL optional for Create Membership API and Serverside Requests
* https://github.com/appwrite/appwrite/issues/6130
- [] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?
> Make URL optional for Create Membership API and Serverside Requests

- app/config/roles.php
- app/controllers/general.php
- app/controllers/web/console.php
- app/http.php
- app/workers/certificates.php
- Automatically issues SSL for first domain connected to new instance
- Servers API+Console by default, if domain is not known
x
> Fix: Untrusted custom domains + auto-ssl

- app/controllers/api/functions.php
When we use latest DB lib, this will be needed to fix redeploys.
On QA server, manually.
x
> Fix: Function redeploys

- app/views/install/compose.phtml
- docker-compose.yml
The appwrite-schedules container fetches functions and needs the openssl key to decrypt function variables. Without this, the variables may end up being false.
None
None
> Add _APP_OPENSSL_KEY_V1 to the compose file

- app/controllers/api/account.php
- app/controllers/api/functions.php
- app/workers/certificates.php
- composer.json
- composer.lock
Fixes manual internal id insertion and bumps db version 
> fixes manual internal id insertion

- composer.lock
Upgrade migration library
Fixes
- https://github.com/appwrite/appwrite/issues/6174
- https://github.com/appwrite/appwrite/issues/6176
> chore: update dependencies

- app/config/platforms.php
- composer.json
- composer.lock
> Chore bump sdk versions

- .gitmodules
> Chore update console

- app/workers/deletes.php
The project deletion failed because old code for deleting domain was still present. By removing the old code and replacing it with the new delete rule code, the project deletion is now working.
Fixes #6252 
Manually created a project with a project rule and function rule and tested deleting the project. The logs show the process was completed successfully:
In addition, before and after SQL queries show the records have been removed from the database.
- #6252
> Fix project deletion

- composer.lock
Fixes #6303
None
- https://github.com/appwrite/appwrite/issues/6303
> Bump composer to fix migration bug

- src/Executor/Executor.php
Uses correct variable for the logic. Thanks to this, very-long-running functions will work as expected.
Current tests must pass
https://github.com/appwrite/appwrite/issues/6244
> Fix execution call timeout

- composer.lock
- tests/e2e/Services/Users/UsersBase.php
- Fix empty fulltext search
Added test + manual test
- https://github.com/appwrite/appwrite/issues/6337
> Fix empty fulltext search

- .gitmodules
Bump Appwrite Console to [3.2.0](https://github.com/appwrite/console/releases/tag/3.2.0).
Manual
- https://github.com/appwrite/console/pull/564
- https://github.com/appwrite/console/pull/541
- https://github.com/appwrite/console/pull/567
> Bump console to version 3.2.0

- package.json
- in order to use this repository as a node modules, we need a very basic `package.json`
> feat: package json

- app/controllers/api/projects.php
- app/http.php
Temporarily disable database creates
> chore: remove DB creates

- app/controllers/api/projects.php
> chore: update database

- CONTRIBUTING.md
Update contributing guide about hacktoberfest to help avoid random submissions.
> Update with hacktoberfest instructions.

- app/controllers/api/projects.php
Adds the ability to override the database for the creation of new projects
> chore: add database overrides

- app/views/install/compose.phtml
- docker-compose.yml
This upgrade fixes problem related to executions and deployments, when error was "File not found". This only occurred with external S3 provider configured for storage.
* https://github.com/appwrite/appwrite/issues/6439
* https://github.com/open-runtimes/executor/pull/42
> Fix: Upgrade executor

- README-CN.md
Fixes https://github.com/appwrite/appwrite/issues/6488
Manual
- https://github.com/appwrite/appwrite/issues/6488
> Update logo in README-CN.md

- .gitmodules
> chore: upgrade console to 3.2.2 on cloud

- app/views/install/compose.phtml
- composer.lock
- docker-compose.yml
Adds support for Dart 3.1 in Appwrite Functions
* https://github.com/appwrite/website/pull/251
> Feat: Dart 3.1 support

- CONTRIBUTING.md
- app/controllers/api/health.php
- app/init.php
- composer.json
- composer.lock
- docker-compose.yml
- src/Appwrite/Event/Database.php
- src/Appwrite/Platform/Tasks/Maintenance.php
- src/Appwrite/Platform/Workers/Databases.php
- tests/e2e/Services/Health/HealthCustomServerTest.php
- tests/resources/docker/docker-compose.yml
Remove resque dependency from Appwrite
> chore: remove resque library and update health check endpoints

- app/views/install/compose.phtml
- docker-compose.yml
Uses new executor version that improves logging of errors when starting function executions and builds.
https://github.com/open-runtimes/executor/compare/0.4.4...0.4.5
Current tests.
https://github.com/open-runtimes/executor/pull/45
> Feat: Upgrade executor

- app/controllers/api/projects.php
Update backup timings for the databases
> chore: update backup timings

- app/config/errors.php
- app/realtime.php
- src/Appwrite/Extend/Exception.php
- add realtime error to the error configuration
- throw appropriate errors in realtime
- only log errors to provider if exception is unexpected
- some misc improvements to realtime code
> feat: realtime error handling

- app/config/errors.php
Update status code for unsupported protocol error
https://app.asana.com/0/1148249895651207/1205785314240511/f
> Updated the error code for unsupported protocol

- .gitmodules
> chore: bump console version

- README.md
The provided pull request (PR) details the inclusion of the official documentation URL within the README file of the Appwrite repository.
I have included the documentation link for the benefit of first-time Appwrite users. This update covers minor documentation change,  the addition of links for Rancher, Docker Swarm, and Kubernetes documentation.
- [✔️] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
> added docs url

- .gitpod.yml
- `composer update` shouldnt be an automatic task and be replace by `composer install`
- manaul
> gitpod: fix composer usage

- app/controllers/api/account.php
- app/controllers/api/projects.php
- app/controllers/api/teams.php
- src/Appwrite/Platform/Workers/Certificates.php
- src/Appwrite/Platform/Workers/Mails.php
- Remove unused mail vars
- Leave user placeholder in default email template
- Refactor email templates to have the controller localize and prepare the template for mail worker
- Update emails from certificate worker to match pattern of other emails
- Add support for variables in email template subject
Manual:
<details>
<summary>Custom Email Template w/ Variables in Subject</summary>
**Template:**
**Email:**
</details>
<details>
<summary>Certificate Email Fix</summary>
</details>
<details>
<summary>Default Email Template</summary>
</details>
Issues addressed: 
- https://github.com/appwrite/appwrite/issues/6440
- https://github.com/appwrite/appwrite/issues/6435
Historical PRs:
- https://github.com/appwrite/appwrite/pull/6047
> Fix certificate emails and add support for variables in email template subject

- app/controllers/api/projects.php
Update the project creation logic inside the create project endpoint.
> chore: update project creation database allocation

- src/Appwrite/Platform/Workers/Deletes.php
During the worker refactor, some changes to the deletes worker weren't migrated over.
None
Previous PRs:
* https://github.com/appwrite/appwrite/pull/5839
* https://github.com/appwrite/appwrite/pull/5842
> Fix regression from worker refactor

- src/Appwrite/Platform/Workers/Deletes.php
Deletes documents from VCS repositories and vcsComments collections when a project or a linked function is deleted. 
Fixes #7018, #7019
Tested manually
* https://github.com/appwrite/appwrite/issues/7018
* https://github.com/appwrite/appwrite/issues/7019
> Delete linked VCS repos and comments

- CONTRIBUTING.md
- Dockerfile
- dev/xdebug.ini
- dev/yasd_init.php.stub
This PR adds XDebug's configuration files to Appwrite to leverage the XDebug extension implemented in the PR here: https://github.com/appwrite/docker-base/pull/20
Build with the new docker-base and test if the debugger works
> Add XDebug

- app/controllers/api/health.php
- tests/e2e/Services/Health/HealthCustomServerTest.php
Adds threshold parameter to queue health APIs. This is useful for uptime monitoring when you want to ensure queue size does not exceed the expected load.
New tests
x
> Implement health tresholds

- app/controllers/api/vcs.php
Replace `deletes` with `queueForDeletes`
Tested locally
> Fix git installation deletion

- app/controllers/api/databases.php
Fixes the bug https://github.com/appwrite/appwrite/issues/5595
> Bug add enum longer length

- .github/workflows/linter.yml
- adds a step to the linter which validates the integrity of `composer.json` and `composer.lock`
> Add a CI task to validate composer file and lock

- app/config/collections.php
- app/controllers/api/messaging.php
- src/Appwrite/Utopia/Response/Model/Subscriber.php
- tests/e2e/Services/GraphQL/Base.php
- tests/e2e/Services/GraphQL/MessagingTest.php
- tests/e2e/Services/Messaging/MessagingBase.php
Adds user name in subscriber response model
> adds user name in subscriber response model

- Dockerfile
- bin/get-migration-stats
- src/Appwrite/Platform/Services/Tasks.php
- src/Appwrite/Platform/Tasks/CalcTierStats.php
- src/Appwrite/Platform/Tasks/GetMigrationStats.php
- src/Appwrite/Platform/Tasks/Hamster.php
> feat: add migration stats task

- app/init.php
- src/Appwrite/Migration/Migration.php
- src/Appwrite/Migration/Version/V19.php
- src/Appwrite/Platform/Tasks/Migrate.php
Migrates enum attribute size to 255 for bug fix https://github.com/appwrite/appwrite/issues/5595
> migrates enum attribute size to 255

- .gitmodules
- upgrade console to 3.2.9
- tested on console repo
> chore: upgrade console to 3.2.9

- app/controllers/api/account.php
- app/controllers/api/users.php
- src/Appwrite/Platform/Workers/Messaging.php
- tests/e2e/Services/GraphQL/UsersTest.php
- tests/e2e/Services/Users/UsersBase.php
> adds target when creating user via server endpoint

- .gitmodules
> bump: console version

- .gitmodules
> chore: update console version

- app/config/collections.php
- app/controllers/api/account.php
- app/controllers/api/projects.php
- app/controllers/shared/api.php
- src/Appwrite/Auth/Auth.php
Allows you to extend duration of session as long as you are sending requests.
x
> Feat: Session extension

- .gitmodules
- upgrade to 3.2.15
- https://github.com/appwrite/console/pull/647
> feat: upgrade console to 3.2.15

- app/controllers/api/project.php
- src/Appwrite/Utopia/Response/Model/UsageProject.php
- tests/e2e/General/UsageTest.php
- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
- custom date range for usage
- manual
- #7005
> feat: project usage custom date range

- app/worker.php
- src/Appwrite/Platform/Tasks/Maintenance.php
- src/Appwrite/Platform/Workers/Deletes.php
> provide retention time as queue server resource

- app/controllers/api/account.php
- app/controllers/api/teams.php
- app/controllers/general.php
Revert the expired cookie after tests that showed it did not have any effect 
NA
> fix: remove expired cookie

- app/worker.php
- src/Appwrite/Platform/Tasks/Maintenance.php
- src/Appwrite/Platform/Workers/Deletes.php
> PEA-15 Refactor Deletes and maintenance worker

- app/controllers/api/functions.php
- composer.lock
- src/Appwrite/Platform/Workers/Functions.php
Change function execution usage trigger to count also failed executions.
> Refactor usage execution trigger

- .gitmodules
> chore: update console

- app/config/collections.php
- app/controllers/api/account.php
- app/controllers/api/databases.php
- app/controllers/api/functions.php
- app/controllers/api/project.php
- app/controllers/api/storage.php
- app/controllers/api/users.php
- src/Appwrite/Hooks/Hooks.php
- src/Appwrite/Platform/Tasks/CalcTierStats.php
- src/Appwrite/Platform/Tasks/CreateInfMetric.php
- src/Appwrite/Platform/Tasks/Hamster.php
- src/Appwrite/Platform/Workers/Deletes.php
- src/Appwrite/Platform/Workers/Usage.php
- src/Appwrite/Platform/Workers/UsageHook.php
> rename stats collection

- src/Appwrite/Platform/Workers/Deletes.php
> fix deletes worker

- src/Appwrite/Platform/Tasks/CreateInfMetric.php
> Refactor inf metric calc

- app/controllers/shared/api.php
Add back a section of code that was mistakenly removed.
Fixes #7147 
Manually tested an account.get() call and confirmed the last activity updated:
Issue:
- #7147
Previous PRs:
- https://github.com/appwrite/appwrite/pull/5781
- https://github.com/appwrite/appwrite/pull/6022
> Fix user last activity not updating

- app/controllers/api/storage.php
- improves preview and view endpoint
- No new tests
> Improve large file handling

- app/controllers/api/storage.php
- app/init.php
- composer.lock
- src/Appwrite/Utopia/Response/Model/Bucket.php
- Update to use compression constants from storage lib
- Existing tests
> PEA-38 compression constants

- .github/workflows/tests.yml
We were running  the Services tests, but not the General.
CI jobs should pass
None
> Add General E2E tests to CI pipeline

- src/Appwrite/Enum/MessageStatus.php
Create an enum for Message status since there's a set of possible values for the status.
None
None
> Create an enum for Message status

- app/controllers/api/messaging.php
- composer.lock
- src/Appwrite/Platform/Workers/Messaging.php
Updated based on PR https://github.com/appwrite/appwrite/pull/7245
CI tests should pass.
- https://github.com/appwrite/appwrite/pull/7245
> Messaging uniform logic fixes

- app/controllers/api/account.php
- app/controllers/api/projects.php
- app/controllers/api/teams.php
- app/controllers/api/users.php
- composer.json
- composer.lock
- phpunit.xml
- src/Appwrite/Platform/Workers/Certificates.php
- src/Appwrite/Platform/Workers/Mails.php
> fix: escape html in email params

- src/Appwrite/Utopia/Database/Validator/Queries/Topics.php
- tests/e2e/Services/Messaging/MessagingBase.php
The Console needs to be able to filter on total subscribers so the API should allow querying on total.
Manual and E2E
None
> Add support for querying topic total

- src/Appwrite/Platform/Workers/Hamster.php
> chore: update collection name in hamster

- app/views/install/compose.phtml
- docker-compose.yml
Update assistant version to 0.3.0
> feat: update assistant

- app/controllers/api/account.php
- app/controllers/api/teams.php
- src/Appwrite/Platform/Workers/Mails.php
- fix redirect param not being set in custom templates
- dont escape redirect params in Mails worker
- to be added
> fix: hotfix for redirect param in custom templates

- composer.lock
- src/Appwrite/Platform/Workers/Hamster.php
This PR renames `usage_network_infinity` to `usage_bandwidth_infinity` in order for it to show up correctly in mixpanel.
> Rename usage_network_infinity to usage_bandwidth_infinity

- app/init.php
- src/Appwrite/Platform/Workers/Deletes.php
To ensure data is consistent, subscribers should be deleted if a target is deleted. In addition, the topic total should be updated when the subscriber is deleted.
Manual
None
> Delete subscribers and update topic totals when deleting target

- src/Appwrite/Platform/Workers/Messaging.php
Fix cc + bcc targets fetched by identifier instead of $id
> Fix cc + bcc targets fetched by identifier instead of $id

- app/config/locale/templates/email-webhook-failed.tpl
- src/Appwrite/Platform/Workers/Mails.php
- src/Appwrite/Platform/Workers/Webhooks.php
> Refactored url construction

- app/controllers/api/health.php
This PR adds the threshold param to the queue failed health endpoint to better match all the other endpoints
> Add threshold to queue failed health endpoint

- src/Appwrite/Platform/Workers/Messaging.php
> chore: add logs

- app/controllers/api/account.php
- src/Appwrite/Auth/Phrase.php
- src/Appwrite/Utopia/Response/Model/Token.php
- tests/e2e/Services/Account/AccountBase.php
- tests/e2e/Services/Account/AccountCustomClientTest.php
Renames from `securityPhrase` to `phrase` for simplicity.
Existing tests updated
x
> Feat: Rename security phrases

- app/config/errors.php
- app/controllers/api/messaging.php
- src/Appwrite/Messaging/Status.php
- src/Appwrite/Platform/Workers/Messaging.php
- tests/e2e/Services/Messaging/MessagingBase.php
> Update to standard namespacing for enums

- app/config/errors.php
- app/controllers/api/health.php
- composer.json
- composer.lock
- docs/references/health/get-certificate.md
- src/Appwrite/Extend/Exception.php
- src/Appwrite/Utopia/Response.php
- src/Appwrite/Utopia/Response/Model/HealthCertificate.php
- tests/e2e/Services/Health/HealthCustomServerTest.php
Get status of certificate for a domain to check whether it is still valid or expired.
> Add health certificate validity endpoint

- tests/e2e/Services/GraphQL/AccountTest.php
- tests/e2e/Services/GraphQL/Base.php
- tests/e2e/Services/GraphQL/BatchTest.php
Fix GraphQL tests not updated for method name changes
Existing tests
> Fix graphql tests

- app/controllers/api/health.php
- src/Appwrite/Platform/Workers/Deletes.php
* Update param from `queueName` to `name`
* Use atomic deletes for decreasing attribute
> Update param name

- src/Appwrite/Platform/Tasks/Specs.php
- Specs use cloud endpoint by default
- Manually tested
> PEA-334 - Fix spec use cloud endpoint by default

- composer.lock
- src/Appwrite/Utopia/Database/Validator/Queries/Users.php
> Feat support label queries

- app/config/errors.php
- app/controllers/api/messaging.php
- src/Appwrite/Extend/Exception.php
- Throw on updating sent, processing, failed message
- Only set schedule active is status is scheduled
Existing tests
> Fix updating message status

- app/controllers/api/messaging.php
- src/Appwrite/Platform/Workers/Messaging.php
- tests/e2e/Services/GraphQL/Base.php
The adapter was updated in https://github.com/utopia-php/messaging/pull/75, but the API also needs to be updated.
Existing tests
> Fix telesign params

- app/controllers/api/messaging.php
- tests/e2e/Services/Messaging/MessagingBase.php
Fix swapping options/credentials on create/update SMTP provider
> Fix smtp provider update

- app/config/collections.php
- app/controllers/api/messaging.php
- src/Appwrite/Utopia/Response/Model/Topic.php
- tests/e2e/Services/Messaging/MessagingBase.php
Allow setting permissions on a topic for who is allowed to subscribe to it. Enhances security and allows more flexibility in how topics can be used. Also brings the permission model more in line with other resources (functions)
> Feat subscribe permission

- app/config/errors.php
- app/controllers/general.php
- app/controllers/shared/api.php
- src/Appwrite/Extend/Exception.php
- tests/e2e/General/HooksTest.php
- move user and project logic from general to api hook
- remove project_unknown error in favor of project_not_found
- added general tests for hooks
- manually and existing
> fix: blocked users web controllers

- docker-compose.yml
- replaces redis command with redis insights, the official GUI by redis
> dev: introduce redis insights

- composer.json
- composer.lock
> Update image lib

- app/controllers/api/avatars.php
Asana task: https://appwrite.sentry.io/issues/4139632090/?project=6054168&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=24&utc=true
> Update exception for github session not found

- src/Appwrite/Auth/Validator/Phone.php
- tests/unit/Auth/Validator/PhoneTest.php
Constrain valid phone numbers to contain 7-15 digits.
> Feat more phone validation

- app/controllers/api/project.php
- Fix calculation of project network usage in the usage endpoint
- Manual
> fix project network usage

- app/controllers/api/project.php
- check the related pr
- https://github.com/appwrite/appwrite/pull/7608
> usage logs updates

- app/controllers/api/account.php
- app/controllers/api/functions.php
- app/controllers/api/messaging.php
- app/controllers/api/teams.php
- app/controllers/api/vcs.php
- app/controllers/shared/api.php
- app/init.php
- app/worker.php
- src/Appwrite/Event/Messaging.php
- src/Appwrite/Platform/Tasks/ScheduleMessages.php
- src/Appwrite/Platform/Workers/Builds.php
- src/Appwrite/Platform/Workers/Deletes.php
- src/Appwrite/Platform/Workers/Messaging.php
- tests/e2e/Services/Account/AccountCustomClientTest.php
Remove device callback resources from workers
Existing tests
> Remove callback resources from workers

- app/config/collections.php
- app/controllers/api/functions.php
- app/controllers/api/messaging.php
- src/Appwrite/Platform/Tasks/ScheduleBase.php
- src/Appwrite/Platform/Workers/Deletes.php
Remove resourceCollection from schedule collection
> Refactor remove resource collection

- app/controllers/general.php
Removes CURL request from Appwrite Router, to prevent 1 request using 2 worker threads.
Disadvantage is that this creates code duplication. We strive for better solution once we have coroutine HTTP server.
- Current tests must pass
x
> Fix: Router CURL

- app/controllers/general.php
Reverts appwrite/appwrite#7627
> Revert "Fix: Router CURL"

- app/controllers/api/users.php
Insert providers null in case of Empty data
> Provider null

- .github/workflows/publish.yml
This PR adds ARM64 to the docker publish GitHub action as well as Qemu for cross-compilation using buildx
> Add ARM64 to docker publish

- app/controllers/api/health.php
Fix content-type for writing text file.
Tested on a bucket
https://github.com/appwrite/appwrite/pull/7591
> Fix content-type of file

- app/controllers/api/messaging.php
- tests/e2e/Services/Messaging/MessagingBase.php
Fix missing subscribe for topic update
Added test
> Fix update topics permissions

- app/controllers/api/messaging.php
- src/Appwrite/Platform/Workers/Messaging.php
- tests/e2e/Services/Messaging/MessagingBase.php
Allow using APNS sandbox mode
Added test
> Allow setting APNS to sandbox mode

- .github/workflows/tests.yml
Fixes failing tests on 1.5 branch. WOrks locally, only fails in CI/CD
CICD must pass
x
> Fix: Functions CI/CD tests

- app/controllers/api/account.php
> Fix missing userId on update challenge

- src/Appwrite/Event/Mail.php
- Add option to reset attachment in mail event
> Fix mail reset attachment

- src/Appwrite/Event/Mail.php
> Fix return

- app/controllers/api/teams.php
- tests/e2e/Services/Teams/TeamsBaseClient.php
- tests/e2e/Services/Teams/TeamsBaseServer.php
In organization members list it says MFA is enabled on member even if they don't have any authenticator added. Additional check ensures this doesn't happen
None
x
> Fix: False positive MFA

- app/controllers/api/account.php
Added a default value, an empty string to name in the function (->setName($profile->getAttribute('name') ) of ./controllers/api/account.php file.
Fixes https://github.com/appwrite/appwrite/issues/7597
- https://github.com/appwrite/appwrite/issues/7597
> Bug 7597 - Adding default value

- src/Appwrite/Platform/Workers/Messaging.php
Fix messaging duplication in the worker
> Fix duplication

- app/config/variables.php
- app/controllers/api/projects.php
https://github.com/appwrite/appwrite/issues/7051
> Allow ssl along with tls in custom smtp

- app/controllers/api/account.php
- docs/references/account/update-session.md
> Update endpoint description

- app/config/errors.php
- app/controllers/api/account.php
- composer.lock
- src/Appwrite/Extend/Exception.php
- tests/e2e/Services/Account/AccountCustomClientTest.php
Update error types for Create Account endpoints
> chore: update error types for create account endpoints

- src/Appwrite/Platform/Tasks/SDKs.php
- Fixes cover image in SDK repositories
- https://github.com/appwrite/sdk-generator/issues/778
> update cover image for SDKs

- src/Appwrite/Specification/Format.php
Prevents unwanted changes
Consoel SDk
x
> Fix: SDKs enums

- README.md
> Updated header

- app/controllers/api/messaging.php
- src/Appwrite/Platform/Workers/Messaging.php
> Feat seperate image IDs

- app/controllers/api/messaging.php
- app/controllers/api/storage.php
Add JWT's to push image URLs and validate in a new route 
> Feat image jwts

- .gitmodules
> bump: console 4.0.2

- src/Appwrite/Migration/Version/V20.php
> Fix stats migration

- app/config/platforms.php
- composer.lock
- docs/sdks/dart/CHANGELOG.md
- docs/sdks/flutter/CHANGELOG.md
> release: flutter/dart sdks

- src/Appwrite/Migration/Version/V20.php
Fix migrations:
- Not deleting index doument
- Trying to delete index by wrong ID
- Not changing type of array attributes unless they had an index
Manual test
> Fix index migrations

- app/config/platforms.php
- composer.lock
> Release python sdk

- app/controllers/api/vcs.php
- src/Appwrite/Event/Build.php
- src/Appwrite/Platform/Workers/Builds.php
* fix deployments stuck at processing 
* Ensure project is passed in the event because the init hook
isn't able to detect the project.
* Make sure the build is triggered for each function.
* Reset the build event so the shutdown hook doesn't trigger
again.
* prevent an error with one function deployment stopping others
* reduce nested code
Manually deployed via GitHub:
None
> Fix git deployments

- composer.lock
Fixes https://github.com/appwrite/appwrite/issues/6322
Added * platform and then used https://google.com for the success URL:
https://github.com/appwrite/appwrite/assets/1477010/a94e10a6-38bb-4b4d-8c0f-d944cdea0aa7
- https://github.com/appwrite/appwrite/issues/6322
> Allow wildcards for url validation like OAuth2 success

- app/controllers/api/databases.php
- app/controllers/api/storage.php
- app/controllers/api/teams.php
- app/controllers/general.php
Move database exception wrapping into error handler instead of per-route
> Fix database exception wrapping

- src/Appwrite/Platform/Workers/Builds.php
The extra trim is needed because the extra quotes interfere with additional operations in the executor/orchestration library.
Manual and CI
None
> Escape function build command

- app/controllers/general.php
> Fix exception wrap order

- README-CN.md
- README.md
Replacing 1.5.4 w/ 1.5.3
Reverts incorrect version update in Readme
> Revert Version Update

- app/controllers/api/teams.php
> Fix membership query to use internalId

- app/controllers/api/teams.php
> Use team internal ID for checks and queries for membership

- app/init.php
- use team internal ID instead of team Id for admin mode
> Admin mode use teamInternalId

- app/controllers/api/avatars.php
- composer.json
- composer.lock
Prevent redirects in the avatars endpoints when trying to fetch icons and images
> chore: update avatars API

- app/controllers/api/account.php
- app/controllers/api/teams.php
- app/controllers/api/users.php
> use internal ids for query

- app/controllers/api/vcs.php
Fix VCS Silent Mode
Tested manually
> Fix vcs silent mode

- app/views/install/compose.phtml
- docker-compose.yml
See:
* https://github.com/open-runtimes/executor/pull/60
* https://github.com/open-runtimes/executor/pull/61
CI should pass.
- https://github.com/appwrite/appwrite/issues/6362
> Bump executor version to fix docker conflict error

- app/views/install/compose.phtml
Add DB env vars to webhook worker since every worker requires the DB env vars because a connection is created on init.
Fixes: #7844 
Confirmed installing creates a docker-compose.yml file with the DB vars in the webhook's environments:
Confirmed triggering a webhook event fires sucessfully.
- #7844
> Fix webhooks failed connection

- app/config/platforms.php
- composer.lock
See https://github.com/appwrite/sdk-for-cli/issues/116
Manual
- https://github.com/appwrite/sdk-for-cli/issues/116
> Fix CLI login

- app/http.php
Improves var names and docs, to make this complex function more understandable.
No need
x
> Improve comments and var names

- src/Appwrite/Vcs/Comment.php
Update VCS Comment to be more contextual.
> Update VCS Comment

- CHANGES.md
- Add 1.5.4 changes to CHANGES.md
In addition, the following manual tests should be performed:
```
docker compose build
docker tag appwrite-dev appwrite/appwrite:1.5.4
docker run -it --rm \
--volume /var/run/docker.sock:/var/run/docker.sock \
--volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
--entrypoint=install \
appwrite/appwrite:1.5.4
```
None
> Prepare 1.5.4 release

- README-CN.md
- README.md
Reverting revert of https://github.com/appwrite/appwrite/pull/7828
N/A
https://github.com/appwrite/appwrite/pull/7828
> 1.5.4 ReadMe Bump

- composer.json
- composer.lock
> Transaction and reconnection fixes

- app/controllers/api/messaging.php
Removes a duplicate call to fetch the Topic document.
> Remove a Redundant Call to Fetch the Topic Document Again

- src/Appwrite/Auth/OAuth2/Autodesk.php
Fixed wrong refresh variable in the autodesk OAuth class.
- N/A
> Fixed wrong refresh var for Autodesk

- app/config/errors.php
Change error code for unsupported OAuth provider
> Fix OAuth error code

- app/controllers/general.php
Removing as I assume these were leftover after https://github.com/appwrite/appwrite/pull/7818.
None
- https://github.com/appwrite/appwrite/pull/7818
> Remove var_dump calls

- app/init.php
- composer.lock
- Set HTTP version to 1.1 for DO spaces adapter
- Manual tests
> PEA-649 storage do adapter http version

- docker-compose.yml
> Update executor version

- app/realtime.php
> Comment timer tick

- app/controllers/api/messaging.php
The parameter and paylaod was missing from the request so it failed to trigger.
Manually setting the payload is important because the payload isn't in the response body like it is for create/update operations.
Fixes: https://github.com/appwrite/appwrite/issues/7832
Confirmed the event triggered in a function:
- #7832
> Fix delete message event not firing

- composer.json
- composer.lock
> Update db for relationships and object as array attributes fixes

- docker-compose.yml
Bump executor version to 0.5.1
> Bump executor version to 0.5.1

- app/controllers/general.php
- tests/e2e/General/ModeTest.php
- prevents using admin mode on console project
- added tests
> fix: admin mode on console

- app/controllers/general.php
> Match memberships on internal ID

- README-CN.md
- README.md
Some of the links are updated, list of products and sdks out dated.
This fixes these issues.
> Update SDK and docs links in readme

- app/controllers/api/account.php
The factor parameter is case insensitive so we need to make sure comparing the parameter to the constant is case insensitive too.
Manually tested.
None
> fix(auth): fix challenge type check

- composer.lock
- src/Appwrite/Platform/Workers/Databases.php
- tests/e2e/Services/Databases/DatabasesBase.php
- tests/e2e/Services/Databases/DatabasesCustomServerTest.php
Delete all attributes who are related to the deleted collection.
Limbo attribute.
- https://github.com/appwrite/appwrite/issues/6012
> Delete relating attributes on delete collection 

- app/config/avatars/flags.php
Add French Polynesia flag to flags.php so we can use the /flags API
> Add French Polynesia flag to flags.php

- app/controllers/shared/api.php
- we check for admin mode before the mfa checks, which is unnecessary
- existing tests
- manual tests
> fix: mfa with admin mode

- app/config/locale/countries.php
Since we use ISO 3166 standard for country codes, we should document it in the code so we can easily look up whether a country code is in the standard or not.
CI should pass
None
> Document standard for country codes

- app/config/platforms.php
- composer.json
- composer.lock
- docs/sdks/flutter/CHANGELOG.md
- Update Flutter SDK version and release
- https://github.com/appwrite/sdk-for-flutter/pull/197
> Release Flutter SDK

- composer.lock
- src/Appwrite/Extend/Exception.php
> Feat upgrade db

- app/controllers/api/avatars.php
Some 4xx errors are being reported. There is no need to report the same.
> Remove logger code from avatars.php

- app/http.php
- app/init.php
- composer.lock
- tests/e2e/Services/Storage/StorageBase.php
Downloads from storage are slow. Increasing chunk size to 7 MB from 2 MB might help increase file download speed. 
> Update chunk size to 7 MB

- app/http.php
- app/init.php
- composer.lock
- tests/e2e/Services/Storage/StorageBase.php
Reverts appwrite/appwrite#8060
> Revert "Update chunk size to 7 MB"

- app/controllers/api/projects.php
> Ensure namespace is set if override equals shared tables

- app/controllers/general.php
- src/Appwrite/Event/Database.php
- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
> Fix shared queue name

- app/controllers/api/account.php
> Fix syntax error

- src/Appwrite/Platform/Workers/Databases.php
> Fix missing id attribute error

- app/http.php
- app/init.php
- tests/e2e/Services/Storage/StorageBase.php
Increase chunk size to 10 MB to increase file download speed
> Increase chunk size to 10 MB

- src/Appwrite/Platform/Workers/Deletes.php
Fix collection not found errors thrown for orphan projects
> Catch DB errors on delete

- src/Appwrite/Platform/Workers/Deletes.php
- Fix shared project delete not accounting for audit/abuse tables
> Fix shared project delete

- app/controllers/general.php
- app/init.php
- composer.json
- composer.lock
- Update Logger from 0.3.* to 0.5.*
- Add old sentry syntax conversion
- Add sampler for experiment logger, and set it to 4%
Test locally and make sure it all works.
> Update Logger and migrations, implement sampler.

- app/controllers/api/projects.php
- composer.lock
Change from 1 in 20 to 1 in 5 projects on shared tables DB
> Increase shared tables projects

- app/worker.php
> Remove throw PdoException in Error hook

- .gitmodules
> Chore update submodule

- app/config/variables.php
> Chore update executor host default var

- app/realtime.php
> Wrap realtime stats in an edition check

- app/views/install/compose.phtml
- app/worker.php
- composer.lock
- docker-compose.yml
- src/Appwrite/Docker/Compose.php
- src/Appwrite/Platform/Workers/Messaging.php
- tests/resources/docker/docker-compose.yml
- tests/unit/Docker/ComposeTest.php
> Sync with main

- app/init.php
- src/Appwrite/Platform/Workers/Builds.php
- src/Appwrite/Platform/Workers/Usage.php
Track the following build metrics:
- Total number of builds
- Builds time
- Total number of successful builds
- Successful builds time
- Total number of failed builds
- Failed builds time
> Add metrics for successful and failed builds

- app/config/platforms.php
- docs/references/account/update-mfa-authenticator.md
* fix(docs): remove extraneous word in Verify authenticator description
* chore(sdks): bump major version since there are breaking changes
None
- None
> Release SDKs

- Dockerfile
See https://github.com/appwrite/docker-base/releases/tag/0.9.1
Fixes https://github.com/appwrite/appwrite/issues/8209.
CI should pass
- https://github.com/appwrite/appwrite/issues/8209
> Bump base image from 0.9.0 to 0.9.1

- composer.lock
> Chore:update cache & database

- tests/e2e/Services/Functions/FunctionsCustomClientTest.php
The execution is async so give the function a bit more time to execute.
CI shoudl pass
Parent PR:
* https://github.com/appwrite/appwrite/pull/8316
> Fix flaky function test

- app/controllers/api/vcs.php
- composer.json
- composer.lock
- src/Appwrite/Utopia/Response.php
- src/Appwrite/Utopia/Response/Model/VcsContent.php
- tests/e2e/Services/VCS/VCSConsoleClientTest.php
Adds endpoint to provide file and directory contents of VCS repository. Needed for UI work for 1.6
Branches endpoint still works
New contents endpoint works
x
> Feat: vcs.getRepositoryContents()

- app/controllers/api/functions.php
- app/controllers/general.php
- src/Appwrite/Platform/Workers/Builds.php
- src/Appwrite/Platform/Workers/Functions.php
- tests/e2e/Services/Functions/FunctionsCustomClientTest.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
- tests/resources/functions/php-fn/index.php
- tests/resources/functions/php-large/index.php
- tests/resources/functions/php/index.php
> Add appwrite version in function variables

- README.md
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
- tests/resources/functions/php-fn/index.php
- tests/resources/functions/php-large/index.php
- tests/resources/functions/php/index.php
Lust a lazy way to ensure tests are passing
> Tests: Ensure CI/CD works

- src/Executor/Executor.php
- tests/e2e/Services/Functions/FunctionsCustomClientTest.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
> Fix execution duration

- app/cli.php
- app/controllers/general.php
- app/http.php
- app/realtime.php
- app/worker.php
Remove detailed trace from error logs for compliances (because of function arguments).
N/A
> Remove detailed trace

- composer.json
- composer.lock
- src/Appwrite/Platform/Workers/Migrations.php
This PR updates migrations to 0.5 and fixes the changes in the exceptions API.
> Update Migrations to 0.5

- app/controllers/api/databases.php
Mark all relationship attributes as sensitive so they aren't passed via realtime to prevent sending data to subscribers who shouldn't have access to the nested data.
Manually 
None
> Remove relationship attributes from realtime event payloads

- CONTRIBUTING.md
- Dockerfile
- dev/xdebug.ini
Adding Xdebug profiler for debug builds
> feat: Adding profiler for debugging

- .gitignore
- .gitmodules
- Dockerfile
- app/controllers/web/console.php
- app/http.php
- app/views/install/compose.phtml
- docker-compose.yml
- phpunit.xml
- tests/e2e/General/HTTPTest.php
- tests/e2e/General/HooksTest.php
- removes submodule
- adds new console container to dev and prod compose files
- adjust the old console endpoints so we have backwards compatibility
- https://github.com/appwrite/console/pull/1197
> feat: containerized console

- app/controllers/api/functions.php
- app/controllers/general.php
- src/Appwrite/Platform/Workers/Builds.php
- src/Appwrite/Platform/Workers/Functions.php
- tests/e2e/Services/Functions/FunctionsCustomClientTest.php
- tests/resources/functions/php-fn/index.php
- tests/resources/functions/php-large/index.php
- tests/resources/functions/php/index.php
Adds APPWRITE_REGION in function variables
> Add APPWRITE_REGION in function variables

- app/controllers/api/account.php
- app/controllers/api/teams.php
- src/Appwrite/Event/Mail.php
- tests/e2e/Services/Teams/TeamsCustomClientTest.php
Strip any HTML content from email variables.
> Feat strip mail vars

- composer.lock
This PR updates the lock file to include [0.5.2 of migrations](https://github.com/utopia-php/migration/releases/tag/0.5.2)
> Update lock file with new migrations version

- tests/e2e/Services/Functions/FunctionsBase.php
- tests/e2e/Services/Functions/FunctionsCustomClientTest.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
Extracting "waiting for deployment to be ready" to a function
Making sure the functions tests pass.
> tests: Refactor deployment check in function tests

- .github/workflows/pr-scan.yml
This PR introduces an automated security scanning process for all pull requests using Trivy, a comprehensive vulnerability scanner. The implementation aims to enhance our project's security posture by identifying potential vulnerabilities in both our Docker images and source code early in the development process.
Key features of this implementation:
* Automated scans triggered on PR open, sync, and reopen events.
* Scans both the Docker image built from the PR and the source code.
* Focuses on CRITICAL and HIGH severity vulnerabilities for Docker images and source code.
* Presents scan results as a clear, formatted comment on the PR for easy review, to catch any potential new introductions.
1. Forked Appwrite/appwrite repo and implemented workflow …
> Adding PR Security Scan

- app/init.php
Updating the DBIP to the latest version
> chore: Upgrading dbip to latest version

- app/controllers/general.php
- composer.lock
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
Fix domain executions not being tracked in metrics because the event wasn't being triggered.
Fixes https://github.com/appwrite/appwrite/issues/8339
> Fix queueForUsage not triggering for domain executions

- composer.json
- composer.lock
- src/Appwrite/Platform/Workers/Builds.php
Allows to use tags (0.1.x) to allow non-breaking changes to templates in future.
This is temporary fix and should not be merged to 1.6.x. In 1.6.x, only tag names will be supported. This is only a patch for 1.5.x version to prevent breaking changes.
With "Main" branch
With "0.1.0" branch:
With "0.1.*" branch:
x
> Fix: template tags

- src/Appwrite/Utopia/Response/Model/TemplateFunction.php
- tests/e2e/Services/Functions/FunctionsCustomClientTest.php
Add scopes to functions template
> Add scopes to function template

- src/Appwrite/Migration/Migration.php
- src/Appwrite/Migration/Version/V19.php
- src/Appwrite/Platform/Tasks/Migrate.php
Fixes https://github.com/appwrite/appwrite/issues/8491
- https://github.com/appwrite/appwrite/issues/8491
> fix: Moving migration to be inside coroutine completely

- .github/workflows/tests.yml
Updates the benchmark comment instead of posting a new comment
> Feat update benchmark comment

- app/controllers/api/functions.php
- src/Appwrite/Utopia/Response/Model/Runtime.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
adds `key` param to runtime model
> feat: base runtimes key

- app/config/locale/templates.php
Adding the missing `otpSession`
> Feat adding email templates

- app/controllers/api/functions.php
Disconnect git only when the provider id is an empty string
Manually
> Fix keep git

- app/init.php
- composer.json
- composer.lock
Upgrading utopia-php/logger to the latest version
> chore: Upgrading logger

- src/Appwrite/Platform/Workers/Builds.php
Closes #8506
Tested manually with two git repositories one with space and one without
- #8506 
- [] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
> Fix deploy from git with space

- src/Appwrite/Platform/Workers/Builds.php
Solves missing logs in swift failed build.
Before:
After:
x
> Fix: missing build logs

- app/controllers/api/account.php
- app/controllers/api/vcs.php
- app/views/install/compose.phtml
- docker-compose.yml
> Refactor console links

- src/Appwrite/Utopia/Response.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
> Add boundary to multipart header

- app/controllers/shared/api.php
- Trigger functions event only if event is not paused
- Manually verified
> Trigger functions event only if event is not paused

- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
- tests/resources/functions/php-scopes/index.php
Fixes failing test from previous PR
E2E tests
- https://github.com/appwrite/appwrite/pull/8554
> Fix: Env vars functiosn test

- README.md
Updates Init copy in readme
- View the Readme
- N/A
> chore: Update Init copy

- .github/workflows/pr-scan.yml
Fixes permissions for non contributors and allows workflow to edit comments instead of spamming. 
See test run in https://github.com/EVDOG4LIFE/appwrite_wfTest/pull/21
> Permissions + Comment Fix

- app/config/function-templates.php
> Fix: go version

- composer.lock
> Bump database

- app/views/install/compose.phtml
- docker-compose.yml
- upgrades console image to `5.0.1`
- fix install compose version
> chore: upgrade console

- app/controllers/general.php
- app/init.php
Update the experimental logger config to the new syntax
> 1.6.x logging test

- app/config/platforms.php
- app/views/install/compose.phtml
- composer.lock
- docker-compose.yml
> chore: bump console sdk

- docs/sdks/dart/CHANGELOG.md
- docs/sdks/flutter/CHANGELOG.md
- add changelog for
- dart
- flutter
> docs: add changelogs for dart and flutter

- app/init.php
Update geodb to latest version
> feat: update geodb

- README.md
Updates Init copy in readme
- View readme
- N/A
> chore: Update Init copy in readme

- app/controllers/api/account.php
- app/controllers/api/functions.php
- app/controllers/api/users.php
- app/controllers/api/vcs.php
- app/controllers/shared/api.php
- app/init.php
- src/Appwrite/Extend/Exception.php
- src/Appwrite/Functions/Validator/Headers.php
- src/Appwrite/Platform/Workers/Builds.php
- src/Appwrite/Platform/Workers/Messaging.php
- src/Appwrite/Specification/Format/Swagger2.php
- src/Appwrite/Utopia/Response/Filters/V16.php
- src/Appwrite/Utopia/Response/Filters/V18.php
- src/Appwrite/Utopia/Response/Model/Document.php
- src/Executor/Executor.php
- tests/e2e/Services/Databases/DatabasesBase.php
- tests/e2e/Services/Functions/FunctionsBase.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
- tests/e2e/Services/Webhooks/WebhooksBase.php
- tests/unit/Functions/Validator/HeadersBench.php
- tests/unit/Functions/Validator/HeadersTest.php
> Remove tenant in document filter

- app/config/locale/translations/en.json
- app/controllers/api/account.php
- composer.lock
Improves datetime copy for more readability
Before
After
x
> Fix: Improve mail datetime format

- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
Improves tests to ensure dynamic keys and endpoint URL works in async executions
x
> Fix: Add Functions templates async test

- app/init.php
- src/Appwrite/Platform/Workers/Messaging.php
> Phone auth metric rename

- app/controllers/api/functions.php
- app/controllers/general.php
- src/Appwrite/Platform/Workers/Builds.php
- src/Appwrite/Platform/Workers/Functions.php
Adds new ENV vars to functions
x
> Feat: VCS vars to deployments & executions

- app/controllers/general.php
- src/Appwrite/Platform/Workers/Functions.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
Ensures that function with logging=false still always makes execution, just doesn't have logs and errors
x
> Fix: logging behaviour for Functions

- Dockerfile
Bump base image to fix security vulnerabilities
Security Scan Results for PR should show 0 vulnerabilities.
None
> Bump docker base

- app/controllers/api/avatars.php
- app/controllers/api/vcs.php
> Fix auth injection

- app/controllers/api/avatars.php
- app/controllers/api/vcs.php
Reverts appwrite/appwrite#8694
> Revert "Fix auth injection"

- src/Appwrite/Platform/Tasks/ScheduleBase.php
Reverts appwrite/appwrite#8691
> Revert "Fix typo in scheduler base"

- src/Appwrite/Platform/Tasks/ScheduleBase.php
> fix: typo in scheduler base

- src/Appwrite/Messaging/Adapter/Realtime.php
- src/Appwrite/Platform/Workers/Functions.php
- src/Appwrite/Platform/Workers/Migrations.php
- src/Appwrite/Specification/Format/Swagger2.php
- tests/e2e/Services/Realtime/RealtimeBase.php
- tests/e2e/Services/Realtime/RealtimeConsoleClientTest.php
- tests/e2e/Services/Realtime/RealtimeCustomClientTest.php
- adds channels `projects.XXXX` to `console` project on realtime
- added tests
- #8186
> feat(realtime): projects channels

- SECURITY.md
> Version Bump

- app/config/collections.php
> originalId

- app/assets/security/10k-common-passwords
- app/controllers/api/avatars.php
> Fix Walter References

- app/config/function-templates.php
- app/config/platforms.php
- composer.json
- composer.lock
- src/Appwrite/Utopia/Response/Model/Execution.php
> Feat: Add new runtimes

- app/config/function-templates.php
- composer.json
- composer.lock
> chore: update php runtimes

- composer.json
- composer.lock
> chore: update utopia-php/system to 0.9.0

- app/config/collections.php
- composer.lock
> chore: add missing indexes

- docker-compose.yml
Bump assistant, new version using GPT 4o + 1.6.x docs
> chore: bump assistant

- app/config/regions.php
Updates the BLR region name from "Banglore" to "Bangalore" as "Banglore" is incorrect.
CI should pass
None
> Fix typo in BLR region

- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
Add missing tests for project variable endpoints
> Add tests for project variables

- app/controllers/api/account.php
- app/controllers/api/users.php
- composer.lock
- src/Appwrite/Utopia/Response/Model/Target.php
- tests/e2e/Services/Account/AccountCustomClientTest.php
- tests/e2e/Services/Health/HealthCustomServerTest.php
- tests/e2e/Services/Users/UsersBase.php
- Fix FCM targets incorrectly marked as expired
- Reset expired status if manually updating target identifier
Updated existing tests + added tests
> Fix target deletes

- src/Appwrite/Platform/Modules/Functions/Module.php
- src/Appwrite/Platform/Modules/Functions/Services/Workers.php
- src/Appwrite/Platform/Modules/Functions/Workers/Builds.php
> fix: builds worker new structure

- app/config/collections.php
- app/controllers/api/functions.php
- app/controllers/api/project.php
- src/Appwrite/Utopia/Response/Model/Variable.php
- tests/e2e/Services/Functions/FunctionsConsoleClientTest.php
- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
Add secret variables to functions and projects which can be updated and deleted but value can't be read.
> Add secret attribute to variables

- src/Appwrite/Platform/Modules/Sites/Http/Sites/UpdateSite.php
Add build and serve runtime to updateSite
> Add build and serve runtime to updateSite

- app/controllers/general.php
- app/views/install/compose.phtml
- docker-compose.yml
- src/Appwrite/Platform/Modules/Functions/Workers/Builds.php
- src/Appwrite/Platform/Modules/Sites/Http/Deployments/GetDeployment.php
- src/Appwrite/Platform/Modules/Sites/Http/Deployments/ListDeployments.php
- src/Appwrite/Platform/Modules/Sites/Http/Sites/CreateSite.php
- src/Appwrite/Utopia/Response/Model/Deployment.php
> Feat: Implement preview deployments

- app/config/site-templates.php
- src/Appwrite/Platform/Modules/Sites/Http/Sites/GetTemplate.php
> Fix: unwanted notice

- app/controllers/api/proxy.php
Throw 409 exception if subdomain already exists, otherwise return 204 status code.
> Throw exception for error

- .github/workflows/tests.yml
- src/Appwrite/Platform/Modules/Sites/Http/Deployments/GetDeployment.php
- src/Appwrite/Platform/Modules/Sites/Http/Deployments/ListDeployments.php
> Fix: deployment domain incorrect

- src/Appwrite/Messaging/Adapter/Realtime.php
> Fix: sites deployment logs realtime

- app/config/collections.php
- app/config/frameworks.php
- app/config/site-templates.php
- app/views/install/compose.phtml
- docker-compose.yml
- src/Appwrite/Platform/Modules/Functions/Workers/Builds.php
- src/Appwrite/Platform/Modules/Sites/Http/Sites/ListFrameworks.php
- src/Appwrite/Utopia/Response/Model/Framework.php
- src/Appwrite/Utopia/Response/Model/TemplateFramework.php
- src/Appwrite/Utopia/Response/Model/TemplateSite.php
> Feat: Styled&timestamped logs

- src/Appwrite/Platform/Modules/Sites/Http/Sites/GetTemplate.php
> Fix: sites get template missing key

- app/controllers/api/vcs.php
- src/Appwrite/Platform/Modules/Functions/Workers/Builds.php
- src/Appwrite/Vcs/Comment.php
> Feat add sites comments

- src/Appwrite/Utopia/Database/Validator/Queries/Migrations.php
- src/Appwrite/Utopia/Response/Model/Migration.php
> Fix missing allow attribute

- app/controllers/api/databases.php
> Fix validator usage for updating string size

- composer.lock
> upgrade utopia storage

- app/config/errors.php
- app/controllers/api/databases.php
- composer.json
- composer.lock
- tests/e2e/Services/Databases/DatabasesCustomServerTest.php
Reverts appwrite/appwrite#8946
> Revert "Update database"

- app/controllers/general.php
> feat fix web routes

- app/controllers/general.php
> debug: whitelist console

- app/controllers/api/teams.php
- tests/e2e/Services/Teams/TeamsCustomClientTest.php
Fixes 500 error that occurs when only MFA memberships privacy was enabled
> fix: memberships privacy mfa

- .github/workflows/tests.yml
- src/Appwrite/Platform/Workers/Deletes.php
- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
> Fix project type delete checks

- .github/workflows/sdk-preview.yml
- .gitignore
- app/config/specs/open-api3-latest-client.json
- app/config/specs/open-api3-latest-console.json
- app/config/specs/open-api3-latest-server.json
- app/config/specs/swagger2-latest-client.json
- app/config/specs/swagger2-latest-console.json
- app/config/specs/swagger2-latest-server.json
- composer.json
- composer.lock
- src/Appwrite/Platform/Tasks/SDKs.php
- src/Appwrite/Specification/Format/OpenAPI3.php
- src/Appwrite/Specification/Format/Swagger2.php
- create a console sdk for each PR
> ci: console sdk previews

- app/controllers/api/databases.php
- composer.lock
Unset hardcode index length for string, depend on Index validation to do the work, since when no length is provided , the validator uses the attributes length.
> Unset index length

- app/controllers/api/vcs.php
- src/Appwrite/Platform/Modules/Compute/Base.php
- src/Appwrite/Platform/Modules/Functions/Workers/Builds.php
- src/Appwrite/Platform/Modules/Sites/Http/Deployments/CreateDeployment.php
- src/Appwrite/Platform/Modules/Sites/Http/Sites/CreateSite.php
Create preview url rule when deployment is created instead of when build is ready
> Create preview url rule when deployment is created

- .github/workflows/sdk-preview.yml
- .gitignore
- app/config/specs/open-api3-latest-client.json
- app/config/specs/open-api3-latest-console.json
- app/config/specs/open-api3-latest-server.json
- app/config/specs/swagger2-latest-client.json
- app/config/specs/swagger2-latest-console.json
- app/config/specs/swagger2-latest-server.json
- composer.lock
- src/Appwrite/Platform/Tasks/SDKs.php
- src/Appwrite/Specification/Format/OpenAPI3.php
- src/Appwrite/Specification/Format/Swagger2.php
> sync: 1.6.x

- app/controllers/api/functions.php
- app/controllers/api/proxy.php
- app/controllers/general.php
- src/Appwrite/Platform/Workers/Certificates.php
Add backwards compatibility for changes to the rules collection in 1.7
Original PR for reference - https://github.com/appwrite/appwrite/pull/8951/
> chore: backwards compatibility for 1.6.x

- app/views/install/compose.phtml
- docker-compose.yml
Bump console to version 5.2.25
None
None
> Bump console to version 5.2.25

- app/config/site-templates.php
> Change case to sentence case for site template titles

- app/cli.php
- app/controllers/general.php
- app/http.php
- app/realtime.php
- app/worker.php
Expose more information to the logging system, allow to override system hostname.
> feat: add more tags to logging

- CONTRIBUTING.md
- app/controllers/general.php
- app/init.php
Improves local experience with preview domains on Gitpod
x
> Fix: Preview domains locally

- app/views/install/compose.phtml
- docker-compose.yml
Bump console to version 5.2.27
None
None
> Bump console to version 5.2.27

- composer.json
- composer.lock
Upgrade utopia-php/database to [0.53.200](https://github.com/utopia-php/database/releases/tag/0.53.200) to prevent drop table if exist
> Bomb db 0.53.200

- app/config/collections.php
- app/config/errors.php
- app/config/roles.php
- app/config/scopes.php
- app/controllers/api/functions.php
- app/controllers/general.php
- app/init.php
- src/Appwrite/Extend/Exception.php
- src/Appwrite/Platform/Modules/Sites/Http/Logs/DeleteLog.php
- src/Appwrite/Platform/Modules/Sites/Http/Logs/GetLog.php
- src/Appwrite/Platform/Modules/Sites/Http/Logs/ListLogs.php
- src/Appwrite/Platform/Modules/Sites/Http/Sites/GetSite.php
- src/Appwrite/Platform/Modules/Sites/Services/Http.php
- src/Appwrite/Platform/Workers/Functions.php
- src/Appwrite/Utopia/Database/Validator/Queries/Logs.php
- src/Appwrite/Utopia/Response/Model/Execution.php
> Logs for sites

- composer.lock
- Upgrade utopia storage library version
> Chore: upgrade utopia storage

- src/Appwrite/Utopia/Response/Model/Project.php
> fix doc comment for filter method

- src/Appwrite/Platform/Workers/Migrations.php
- Add sentry error in case of throwable exception.
- Check source & destinations for nulls.
- 
> Migration throw error

- app/cli.php
- app/controllers/api/avatars.php
- app/controllers/api/functions.php
- app/controllers/api/messaging.php
- app/controllers/api/migrations.php
- app/controllers/api/project.php
- app/controllers/api/projects.php
- app/controllers/api/proxy.php
- app/controllers/api/vcs.php
- app/controllers/general.php
- app/controllers/mock.php
- app/controllers/shared/api.php
- app/http.php
- app/init.php
- app/worker.php
- src/Appwrite/Platform/Tasks/Maintenance.php
- src/Appwrite/Platform/Tasks/Migrate.php
- src/Appwrite/Platform/Tasks/ScheduleBase.php
- src/Appwrite/Platform/Tasks/ScheduleExecutions.php
- src/Appwrite/Platform/Tasks/ScheduleFunctions.php
- src/Appwrite/Platform/Tasks/ScheduleMessages.php
- src/Appwrite/Platform/Tasks/Specs.php
- src/Appwrite/Platform/Workers/Builds.php
- src/Appwrite/Platform/Workers/Certificates.php
- src/Appwrite/Platform/Workers/Databases.php
- src/Appwrite/Platform/Workers/Deletes.php
- src/Appwrite/Platform/Workers/Migrations.php
- src/Appwrite/Platform/Workers/Webhooks.php
Rename occurrences of dbForConsole to dbForPlatform in preparation for clear segmentation between platform and project APIs
> chore: replace occurrences of dbForConsole to dbForPlatform

- src/Appwrite/Event/Webhook.php
- src/Appwrite/Platform/Workers/Webhooks.php
Optimise the webhook payload size
> chore: optimise webhooks payload

- app/controllers/api/functions.php
- app/controllers/api/projects.php
- app/controllers/shared/api.php
- app/http.php
- app/init.php
- app/realtime.php
- app/worker.php
- composer.json
- composer.lock
- phpunit.xml
- src/Appwrite/Platform/Workers/Deletes.php
Reverts appwrite/appwrite#9111
> Revert "chore: initial commit"

- src/Appwrite/Event/Webhook.php
> chore: fix attribute name

- app/controllers/api/functions.php
- app/controllers/api/projects.php
- app/controllers/shared/api.php
- app/http.php
- app/init.php
- app/realtime.php
- app/worker.php
- composer.json
- composer.lock
- src/Appwrite/Platform/Workers/Deletes.php
Add support for the redis adapter for abuse 
Orignal PR was reverted - https://github.com/appwrite/appwrite/pull/9111
> chore: use redis adapter for abuse

- app/worker.php
- src/Appwrite/Platform/Workers/Deletes.php
Fix bug in the deletes worker where the type of abuse retention was `string` instead of `int` 
> Migrate to redis abuse

- composer.lock
- src/Appwrite/Platform/Workers/Databases.php
Don't re-throw not found exception after cleaning up when deleting an attribute fails
> Delete attribute No throwing Exception on not found

- .github/workflows/tests.yml
- app/controllers/shared/api.php
- src/Appwrite/Event/Audit.php
Add hostname to Audits.
Manual.
N/A.
> Add hostname to audits

- app/controllers/general.php
- app/http.php
- app/init.php
- app/worker.php
- composer.json
- composer.lock
Reverts appwrite/appwrite#9190
> Revert "Fix dead connections"

- app/controllers/general.php
- app/http.php
- app/init.php
- app/worker.php
- composer.json
- composer.lock
> Fix dead connections

- app/controllers/general.php
> Log path with populated parameters

- src/Appwrite/Platform/Workers/Databases.php
> Add relatedCollection default

- composer.json
- composer.lock
This PR updates fetch to 0.3.0 so we can utilise the new retry functionality for cloud.
All tests should pass as normal as no functionality has been modified.
> Update Fetch to 0.3.0

- src/Appwrite/Platform/Workers/Deletes.php
Wrap getDocument inside of a try catch to prevent errors from being thrown in case of orphan projects
> Fix maintenance job

- src/Appwrite/Platform/Workers/Deletes.php
Add missing case for scheduled executions
> chore: add missing case for executions

- src/Appwrite/Auth/OAuth2/Amazon.php
Fixes Amazon OAuth.
Problem? Amazon for some reason was not returning the encoded state.
Solution: Encode the state using `urlencode`.
working:
> fix: amazon oauth

- app/config/specs/open-api3-latest-client.json
- app/config/specs/open-api3-latest-console.json
- app/config/specs/open-api3-latest-server.json
- app/config/specs/swagger2-latest-client.json
- app/config/specs/swagger2-latest-console.json
- app/config/specs/swagger2-latest-server.json
- src/Appwrite/Utopia/Response/Model/UsageDatabase.php
- src/Appwrite/Utopia/Response/Model/UsageDatabases.php
- src/Appwrite/Utopia/Response/Model/UsageProject.php
Updates specs for -
* https://github.com/appwrite/appwrite/pull/9260
N/A.
- https://github.com/appwrite/appwrite/pull/9260
> Update: Latest sdk specs

- composer.json
- composer.lock
> Update Sdk Generator dependency

- app/config/collections/common.php
- app/controllers/api/storage.php
- app/controllers/shared/api.php
- app/init.php
Reverts appwrite/appwrite#9281
> Revert "Transformed at addition"

- README.md
> replaced init for cloud link

- app/config/collections/common.php
- app/controllers/api/storage.php
- app/controllers/api/vcs.php
- app/controllers/shared/api.php
- app/init.php
Recreating - https://github.com/appwrite/appwrite/pull/9281
> Add transformed at

- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
Make the session limit tests assert eventually
This is an attempt to fix project tests that are very flaky at the moment
> Make sessions limit tests assert eventually

- src/Appwrite/Platform/Tasks/ScheduleBase.php
- src/Appwrite/Platform/Tasks/ScheduleExecutions.php
- src/Appwrite/Platform/Tasks/ScheduleFunctions.php
- src/Appwrite/Platform/Tasks/ScheduleMessages.php
Message scheduling has issues on AMQP due to connection timeouts in the coroutine.
> fix(schedule-tasks): revert back to direct pool usage

- app/controllers/general.php
- tests/e2e/Services/Sites/SitesBase.php
- tests/e2e/Services/Sites/SitesCustomServerTest.php
Add tests:
- Astro starter (templates)
- Domain reclaiming
New tests
x
> Chore: Improve tsts

- composer.lock
- src/Appwrite/Platform/Workers/StatsResources.php
- Fix: image transformations counting function was never called
> Fix: missing call for image transformations counting

- src/Appwrite/Platform/Workers/Deletes.php
> Fix drop abuse on shared table project delete

- .github/workflows/tests.yml
> Only run all table mode tests on db update

- src/Appwrite/Platform/Workers/StatsResources.php
- Fix: missing periodic metric
> Fix: missing periodic metric

- tests/e2e/Services/Databases/DatabasesBase.php
> Fix patch index validation

- src/Appwrite/Platform/Workers/Builds.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
- tests/resources/functions/node/index.js
This PR fixes the memory set in builds worker and creates a new test that checks the correct specification is set in both functions and builds.
New tests have been added to prevent future regressions.
- https://github.com/appwrite/appwrite/issues/9345
> Fix build memory specifications

- composer.lock
- src/Appwrite/Platform/Modules/Compute/Base.php
- src/Appwrite/Platform/Modules/Functions/Http/Deployments/Template/Create.php
- src/Appwrite/Platform/Modules/Functions/Http/Functions/Create.php
- src/Appwrite/Platform/Modules/Functions/Services/Http.php
- src/Appwrite/Platform/Modules/Sites/Http/Deployments/Template/Create.php
- src/Appwrite/Platform/Modules/Sites/Http/Sites/Create.php
- src/Appwrite/Platform/Modules/Sites/Services/Http.php
- tests/e2e/Services/Functions/FunctionsBase.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
- tests/e2e/Services/Sites/SitesBase.php
- tests/e2e/Services/Sites/SitesCustomServerTest.php
Separates tempalte deployment creation from site/function creation to it's own endpoint
Update existing tests; must pass
x
> Feat: Template deployments

- src/Appwrite/Platform/Workers/StatsResources.php
- Always calculate images transformed in last 30 days
> Fix image trnasformation metrics

- composer.lock
- src/Appwrite/Platform/Workers/Databases.php
- src/Appwrite/Platform/Workers/Deletes.php
> Use batch delete in worker

- src/Appwrite/Platform/Modules/Compute/Base.php
- src/Appwrite/Platform/Modules/Functions/Http/Deployments/Vcs/Create.php
- src/Appwrite/Platform/Modules/Functions/Services/Http.php
- src/Appwrite/Platform/Modules/Sites/Http/Deployments/Template/Create.php
- src/Appwrite/Platform/Modules/Sites/Http/Deployments/Vcs/Create.php
- src/Appwrite/Platform/Modules/Sites/Services/Http.php
Adds new endpoint used to create deployment from VCS refferenece;currently supporting branch only
Did manual QA for sites and functions
> Add createVcsDeployment endpoints for sites and functions

- app/http.php
> Fix removed audits for shared v2

- composer.json
- composer.lock
This version fixes the compression of HEIC and AVIF image formats. Find the full changelog here:
- https://github.com/utopia-php/image/releases/tag/0.8.0
Test Script:
```js
const preview = await storage.getFilePreview(
BUCKET_ID, // bucketId
"67b73a3f001dcf15d970", // fileId
100, // width (optional)
100, // height (optional)
ImageGravity.Center, // gravity (optional)
30, // quality (optional)
0, // borderWidth (optional)
undefined, // borderColor (optional)
0, // borderRadius (optional)
0, // opacity (optional)
0, // rotation (optional)
undefined, // background (optional)
"avif" // output (optional)
);
await writeFile('sample-q30.avif', Buffer.from(preview));
```
Results:
> chore: bump utopia-php/image to 0.8.0

- app/controllers/api/health.php
- docker-compose.yml
- src/Appwrite/Platform/Modules/Functions/Workers/Builds.php
- src/Appwrite/Platform/Modules/Sites/Http/Deployments/Builds/Create.php
- src/Appwrite/Platform/Modules/Sites/Http/Deployments/Create.php
- src/Appwrite/Platform/Modules/Sites/Http/Deployments/Delete.php
- src/Appwrite/Platform/Modules/Sites/Http/Deployments/Download/Get.php
- src/Appwrite/Platform/Workers/Deletes.php
Uses deviceForSites proeprly, for all sites actions
Current tests must pass
x
> Fix: deviceForSites

- app/controllers/api/account.php
- app/controllers/api/databases.php
- app/controllers/api/messaging.php
- app/controllers/api/teams.php
- app/controllers/api/users.php
- src/Appwrite/Platform/Workers/Audits.php
> Batch per project

- Dockerfile
Bumps the appwrite [docker-base](https://github.com/appwrite/docker-base) image to fix various vulnerabilities.
Local trivy scan -
> chore: bump docker-base

- src/Appwrite/Platform/Tasks/StatsResources.php
Reverts appwrite/appwrite#9411
> Revert "Fix: stats resources only queue projects accessed in last 3 hours"

- app/controllers/general.php
- src/Appwrite/Platform/Modules/Functions/Http/Templates/Get.php
- src/Appwrite/Platform/Modules/Functions/Http/Templates/XList.php
- src/Appwrite/Platform/Modules/Sites/Http/Templates/Get.php
- src/Appwrite/Platform/Modules/Sites/Http/Templates/XList.php
- tests/e2e/Scopes/ProjectCustom.php
- tests/e2e/Services/Functions/FunctionsCustomClientTest.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
- tests/e2e/Services/Sites/SitesBase.php
- tests/e2e/Services/Sites/SitesCustomServerTest.php
- tests/resources/sites/astro/astro.config.mjs
- tests/resources/sites/astro/package.json
- tests/resources/sites/astro/src/pages/logs-action.js
- tests/resources/sites/astro/src/pages/logs-inline.astro
- tests/resources/sites/astro/tsconfig.json
- Simplify Astro, speeding up tests
- Adds endpoint to test both .js and .astro SSR logging
New tests
x
> Chore: Add SSR logs test

- src/Appwrite/Platform/Workers/StatsUsageDump.php
> Fix: use receivedAt date when available

- src/Appwrite/Platform/Workers/StatsUsageDump.php
> Fix: disable dual writing

- src/Appwrite/Platform/Workers/StatsResources.php
- src/Appwrite/Platform/Workers/StatsUsageDump.php
- Calculate database storage in stats-resources worker
> Feat: calculate database storage in stats-resources

- src/Appwrite/Platform/Modules/Functions/Http/Deployments/Duplicate/Create.php
- src/Appwrite/Platform/Modules/Functions/Services/Http.php
- src/Appwrite/Platform/Modules/Sites/Http/Deployments/Duplicate/Create.php
- src/Appwrite/Platform/Modules/Sites/Services/Http.php
- tests/e2e/Services/Functions/FunctionsBase.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
- tests/e2e/Services/GraphQL/Base.php
- tests/e2e/Services/GraphQL/FunctionsServerTest.php
- tests/e2e/Services/Sites/SitesBase.php
- tests/e2e/Services/Sites/SitesCustomServerTest.php
- tests/resources/functions/node/maintenance.js
Moves endpoint to new naming structure due to builds rehaul
x
> Chore: Migrate redeploy endpoint

- src/Appwrite/Platform/Tasks/Maintenance.php
- src/Appwrite/Platform/Workers/Deletes.php
Adds logsDB to delete worker.
before:
after:
> chore: added logsdb for deletes worker

- src/Appwrite/Platform/Workers/StatsResources.php
- Adds time taken to aggregate each project
> Feat: calculate and log time taken for each project

- app/config/collections/projects.php
- app/controllers/general.php
- src/Appwrite/Platform/Modules/Functions/Http/Deployments/Delete.php
- src/Appwrite/Platform/Modules/Functions/Http/Executions/Create.php
- src/Appwrite/Platform/Modules/Functions/Http/Functions/Create.php
- src/Appwrite/Platform/Modules/Functions/Http/Functions/Deployment/Update.php
- src/Appwrite/Platform/Modules/Functions/Http/Functions/Update.php
- src/Appwrite/Platform/Modules/Functions/Http/Variables/Create.php
- src/Appwrite/Platform/Modules/Functions/Http/Variables/Delete.php
- src/Appwrite/Platform/Modules/Functions/Http/Variables/Update.php
- src/Appwrite/Platform/Modules/Functions/Workers/Builds.php
- src/Appwrite/Platform/Modules/Proxy/Http/Rules/Function/Create.php
- src/Appwrite/Platform/Modules/Sites/Http/Deployments/Delete.php
- src/Appwrite/Platform/Workers/Functions.php
- src/Appwrite/Utopia/Database/Validator/Queries/Functions.php
- src/Appwrite/Utopia/Request/Filters/V19.php
- src/Appwrite/Utopia/Response/Filters/V19.php
- src/Appwrite/Utopia/Response/Model/Func.php
- tests/e2e/General/UsageTest.php
- tests/e2e/Services/Functions/FunctionsBase.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
- tests/e2e/Services/Proxy/ProxyBase.php
Fix outdated attribute naming convention, to make it consistent with sites and rest of products
existing tests must mass
x
> Chore: Attribute name consistency

- src/Appwrite/Platform/Workers/Deletes.php
> Feat bulk audit delete

- app/views/install/compose.phtml
- docker-compose.yml
Bump console to version 5.2.53
None
* https://github.com/appwrite/appwrite/pull/9468
> Bump console to version 5.2.53

- composer.json
- composer.lock
- src/Appwrite/Platform/Workers/Migrations.php
> Migration read from db

- composer.json
- composer.lock
Update `utopia-php/pools` to include telemetry.
> feat: add pool telemetry

- composer.json
- composer.lock
- docker-compose.yml
- src/Appwrite/Platform/Modules/Compute/Base.php
Fixes incorrect value of github commit author URLs in case of forks or clones
Tested manually
> Fix incorrect URL for git commits

- src/Appwrite/Platform/Tasks/Maintenance.php
- Use cursor pagination instead of limit/offset for iterating all projects
- Increase page size to 100 from 50
> Use cursor pagination with bigger limit for maintenance project loop

- phpunit.xml
Stop tests in case of failure, thus saving CI time.
> chore: stop tests on failure

- app/worker.php
- src/Appwrite/Platform/Workers/Deletes.php
We don't need an array for auditretention.
> refactor: initialization of audit retention

- composer.json
- composer.lock
- src/Appwrite/Utopia/Database/Validator/Queries/Base.php
- tests/e2e/Services/Databases/DatabasesCustomServerTest.php
> Bump database 0.62.x

- src/Appwrite/Platform/Workers/Deletes.php
> Deletes worker fix selects for pagination

- src/Appwrite/Platform/Workers/Deletes.php
> Add $permissions for delete documents selects

- src/Appwrite/Platform/Workers/Audits.php
This instructs the queue library to commit the last message offsets.
> chore(audits): return queue pre-fetch results

- src/Appwrite/Platform/Workers/Audits.php
Reverts appwrite/appwrite#9533
> Revert "chore(audits): return queue pre-fetch results"

- src/Appwrite/Platform/Workers/Deletes.php
> Add order by for cursor

- composer.json
- composer.lock
> Fix tenant casting

- app/controllers/shared/api.php
- Fix image transformation cache
> Fix: image transformation cache

- src/Appwrite/Platform/Workers/Audits.php
- src/Appwrite/Platform/Workers/Databases.php
- src/Appwrite/Platform/Workers/Deletes.php
Remove payload data because of huge payload in Document events
> Remove audit payload

- composer.lock
Updates utopia-php/image to 0.8.1 for better error logging.
> chore: update php image to 0.8.1

- .gitpod.yml
- removes prebuilds from gitpod config as they have been deprecated
- add `git config --global --add safe.directory /app` as a init step
> chore: update gitpod.yml config

- composer.lock
- Fix for undefined array key warning
- Fix for pagination on API resources
> Update migrations lib

- app/config/specs/open-api3-latest-client.json
- app/config/specs/open-api3-latest-console.json
- app/config/specs/open-api3-latest-server.json
- app/config/specs/swagger2-latest-client.json
- app/config/specs/swagger2-latest-console.json
- app/config/specs/swagger2-latest-server.json
Regenerates the specs for Console SDK for CSV Imports on Console.
```sh
docker compose exec -T appwrite specs
```
Related - #9662 
N/A.
- #9662
> Update: specs

- app/controllers/api/functions.php
- app/worker.php
- src/Appwrite/Platform/Workers/Builds.php
Read function size limit value from the plan
> Add configurable function and build size

- app/config/platforms.php
- composer.lock
- docs/examples/1.6.x/console-cli/examples/databases/update-float-attribute.md
- docs/examples/1.6.x/console-cli/examples/databases/update-integer-attribute.md
- docs/examples/1.6.x/console-cli/examples/health/get-queue-stats-resources.md
- docs/examples/1.6.x/console-cli/examples/health/get-queue-stats-usage-dump.md
> chore: update sdks

- app/controllers/api/functions.php
- app/worker.php
- src/Appwrite/Platform/Workers/Builds.php
Reverts appwrite/appwrite#9648
> Revert "Add configurable function and build size"

- app/config/platforms.php
- composer.lock
- docs/sdks/flutter/CHANGELOG.md
> chore: update flutter sdk

- src/Appwrite/Platform/Workers/Migrations.php
> Add: Source report method

- src/Appwrite/Platform/Appwrite.php
- src/Appwrite/Platform/Modules/Tokens/Http/Tokens/Buckets/Files/Action.php
- src/Appwrite/Platform/Modules/Tokens/Http/Tokens/Buckets/Files/Create.php
- src/Appwrite/Platform/Modules/Tokens/Http/Tokens/Buckets/Files/XList.php
- src/Appwrite/Platform/Modules/Tokens/Http/Tokens/Delete.php
- src/Appwrite/Platform/Modules/Tokens/Http/Tokens/Get.php
- src/Appwrite/Platform/Modules/Tokens/Http/Tokens/JWT/Get.php
- src/Appwrite/Platform/Modules/Tokens/Http/Tokens/Update.php
- src/Appwrite/Platform/Modules/Tokens/Module.php
- src/Appwrite/Platform/Modules/Tokens/Services/Http.php
> fix: tokens module

- src/Appwrite/Platform/Tasks/Migrate.php
> Fix length

- composer.json
- composer.lock
> chore: update domains

- app/controllers/api/databases.php
- composer.lock
> Catch query exception on get document for selects

- app/config/variables.php
- src/Appwrite/Platform/Modules/Functions/Workers/Builds.php
- tests/e2e/Services/Sites/SitesCustomServerTest.php
Append build error to build logs
> Append build error to build logs

- app/controllers/api/databases.php
- app/init/database/filters.php
- src/Appwrite/Utopia/Response/Model/AttributeString.php
- tests/e2e/Services/Databases/DatabasesBase.php
- tests/e2e/Services/Databases/DatabasesCustomServerTest.php
> Feat sync encrypt updates

- app/controllers/api/databases.php
- app/init/database/filters.php
- src/Appwrite/Utopia/Response/Model/AttributeString.php
- tests/e2e/Services/Databases/DatabasesBase.php
- tests/e2e/Services/Databases/DatabasesCustomServerTest.php
Reverts appwrite/appwrite#9871
> Revert "Feat sync encrypt updates"

- app/controllers/api/teams.php
- tests/e2e/Services/Teams/TeamsConsoleClientTest.php
Fix the deletion logic, for the last time I hope!
* https://github.com/appwrite/appwrite/pull/9888
* https://github.com/appwrite/appwrite/pull/9765
> Fix deletion logic

- tests/e2e/Scopes/Scope.php
- tests/e2e/Services/Account/AccountCustomClientTest.php
commit-id:3865765d
---
**Stack**:
- #9957
- #9956
- #9955
- #9954 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
> tests: fix flaky account tests

- tests/e2e/General/UsageTest.php
- tests/e2e/Services/Messaging/MessagingConsoleClientTest.php
**Stack**:
- #9957
- #9956 ⬅
- #9955
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
> tests: make usagetests robust

- src/Appwrite/Platform/Workers/Deletes.php
Reverts appwrite/appwrite#10017
> Revert "Update delete project scope"

- src/Appwrite/Platform/Modules/Functions/Workers/Builds.php
Add missing `screenshot finished` and `screenshot error` logs.
> Fix missing screenshot logs

- app/views/install/compose.phtml
- docker-compose.yml
fixes s3 endpoint not being set in executor
Fixes:
- https://github.com/appwrite/appwrite/issues/9906
Related:
- https://github.com/open-runtimes/executor/pull/169
> chore: update executor to fix s3 endpoint bug

- .github/workflows/benchmark.yml
- app/controllers/shared/api.php
- composer.lock
- src/Appwrite/Event/Database.php
- src/Appwrite/Platform/Workers/Databases.php
> Add database worker job logging

- composer.lock
> Updated utopia database

- app/controllers/shared/api.php
Fixes a bug in file caching where files expire after TTL and never gets updated thereafter 
Create a file on 25th May and hit the file preview endpoint (/ preview ) . This creates a cached file in the filesystem as below
```bash
stat  f7302ce87e12756b63e29e384ae23cbe
File: f7302ce87e12756b63e29e384ae23cbe
Size: 5203      	Blocks: 16         IO Block: 262144 regular file
Device: f4h/244d	Inode: 24036614    Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2025-05-27 11:53:39.859869178 +0000
Modify: 2025-05-27 11:53:39.871869527 +0000
Change: 2025-05-27 11:53:39.871869527 +0000
```
Try to hit the file preview after 30 days 
https://github.com/appwrite/appwrite/blob/36aa22793f767071bf9b3dd8ca12ee4361636a58/app/controllers/shared/api.php#L567-L568 …
> patch: increase cache ttl to ensure hits

- app/controllers/api/migrations.php
- composer.json
- composer.lock
- src/Appwrite/Platform/Workers/Migrations.php
Remove the `/` for non-local storage.
> Fix: path and type

- app/init/resources.php
Use dbForPlatform for JWT user lookup in admin mode, instead of dbForProject
Tested with @TorstenDittmann and works
_None_
> fix: JWT authentication database selection for admin mode

- app/cli.php
- app/controllers/api/health.php
- app/init/resources.php
- app/worker.php
- src/Appwrite/Platform/Tasks/ScheduleBase.php
- src/Appwrite/Platform/Tasks/ScheduleExecutions.php
- src/Appwrite/Platform/Tasks/ScheduleFunctions.php
> Add redis publisher to schedule base if available

- app/controllers/api/databases.php
- tests/e2e/Services/Databases/DatabasesBase.php
> Changed the default permission param of upsert document

- app/config/platforms.php
- composer.json
- composer.lock
- docs/examples/1.7.x/server-dotnet/examples/databases/upsert-document.md
- docs/sdks/dotnet/CHANGELOG.md
- docs/sdks/react-native/CHANGELOG.md
update react native and dotnet
> chore: update react native to 0.10.1 and dotnet to 0.14.0

- app/config/platforms.php
- composer.lock
- docs/sdks/cli/CHANGELOG.md
update cli to 8.2.1.
- https://github.com/appwrite/sdk-for-cli/pull/178
> Update cli 8.2.1

- src/Appwrite/GraphQL/Types/Mapper.php
- src/Appwrite/SDK/Specification/Format/OpenAPI3.php
- src/Appwrite/SDK/Specification/Format/Swagger2.php
> Handle redirect validator in specs + GraphQL type mapper

- src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Upsert.php
- src/Appwrite/Platform/Modules/Databases/Http/Databases/Tables/Rows/Upsert.php
- tests/e2e/Services/Databases/Legacy/DatabasesBase.php
- tests/e2e/Services/Databases/Tables/DatabasesBase.php
> Upsert fix 1.8.x

- app/config/locale/templates/email-smtp-test.tpl
- app/config/locale/templates/email-webhook-failed.tpl
- app/controllers/api/account.php
- app/controllers/api/projects.php
- src/Appwrite/Event/Mail.php
- src/Appwrite/Platform/Workers/Certificates.php
- src/Appwrite/Template/Template.php
Fixes the auth email templates!
Manual.
* https://github.com/appwrite/appwrite/issues/7916
Related Console PR:
* https://github.com/appwrite/console/pull/2133
> Fix default email templates

- CONTRIBUTING.md
We typically want people to:
1. work on "good first issue" or "help wanted" issues because those are straightforward enough to not require too much back and forth and are more likely to be merged
2. be assigned on an issue to avoid multiple people working on the same issue leading to wasted effort.
Rendered: https://github.com/appwrite/appwrite/blob/docs-contributing-how-to-start/CONTRIBUTING.md#how-to-start
None
> docs: update CONTRIBUTING.md to clarify how to start

- CONTRIBUTING.md
- app/cli.php
- app/controllers/api/health.php
- app/init/resources.php
- app/worker.php
- src/Appwrite/Platform/Tasks/ScheduleBase.php
- src/Appwrite/Platform/Tasks/ScheduleExecutions.php
- src/Appwrite/Platform/Tasks/ScheduleFunctions.php
- src/Appwrite/Platform/Tasks/ScheduleMessages.php
> feat: stats-usage on redis

- composer.lock
> updated migration release

- app/config/platforms.php
- composer.lock
- docs/sdks/dotnet/CHANGELOG.md
> chore: update changelog and sdk gen

- app/config/platforms.php
- app/config/specs/open-api3-1.7.x-client.json
- app/config/specs/open-api3-1.7.x-console.json
- app/config/specs/open-api3-1.7.x-server.json
- app/config/specs/open-api3-latest-client.json
- app/config/specs/open-api3-latest-console.json
- app/config/specs/open-api3-latest-server.json
- app/config/specs/swagger2-1.7.x-client.json
- app/config/specs/swagger2-1.7.x-console.json
- app/config/specs/swagger2-1.7.x-server.json
- app/config/specs/swagger2-latest-client.json
- app/config/specs/swagger2-latest-console.json
- app/config/specs/swagger2-latest-server.json
- composer.lock
- src/Appwrite/SDK/Specification/Format/OpenAPI3.php
- src/Appwrite/SDK/Specification/Format/Swagger2.php
- src/Appwrite/Utopia/Response/Model/Any.php
- src/Appwrite/Utopia/Response/Model/Document.php
- src/Appwrite/Utopia/Response/Model/Preferences.php
Adds models examples as per swagger/openapi specs.
> feat: add model examples + additonal examples to specs

- src/Appwrite/Event/Event.php
- src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Action.php
- src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Bulk/Delete.php
- src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Bulk/Update.php
- src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Create.php
- src/Appwrite/Platform/Modules/Databases/Http/Grids/Tables/Rows/Bulk/Delete.php
- src/Appwrite/Platform/Modules/Databases/Http/Grids/Tables/Rows/Bulk/Update.php
- src/Appwrite/Platform/Modules/Databases/Http/Grids/Tables/Rows/Create.php
- tests/e2e/Scopes/Scope.php
- tests/e2e/Services/Realtime/RealtimeCustomClientTest.php
-> Event working for bulk api
* They'll fire on existing channels only
* Clients will receive an individual event for each document
> Realtime support for bulk api

- composer.lock
- tests/e2e/Services/Databases/DatabasesBase.php
> Fix atomic number ops with limit 0

- composer.lock
- src/Appwrite/Migration/Version/V23.php
- src/Appwrite/Platform/Modules/Databases/Http/Databases/Create.php
- src/Appwrite/Utopia/Response/Model/Database.php
- tests/e2e/Services/Databases/Grids/DatabasesBase.php
- tests/e2e/Services/Databases/Legacy/DatabasesBase.php
> updated database type to grids and legacy

- app/config/platforms.php
- composer.lock
- docs/examples/1.7.x/client-android/java/functions/create-execution.md
- docs/examples/1.7.x/client-android/kotlin/functions/create-execution.md
- docs/examples/1.7.x/server-kotlin/java/functions/create-execution.md
- docs/examples/1.7.x/server-kotlin/kotlin/functions/create-execution.md
> chore: update SDK generator and sdks

- src/Appwrite/Platform/Workers/Mails.php
> Add placeholder detection

- app/cli.php
- app/controllers/api/health.php
- app/init/resources.php
- app/worker.php
- src/Appwrite/Platform/Tasks/ScheduleBase.php
- src/Appwrite/Platform/Tasks/ScheduleExecutions.php
- src/Appwrite/Platform/Tasks/ScheduleFunctions.php
> Feat: Make functions worker customizable

- app/controllers/general.php
before it would add warning header to /v1/databases which is still supported
> chore: make check for adding warning header stricter

- app/config/templates/site.php
- composer.lock
- docker-compose.yml
> Update build command for flutter

- app/cli.php
- app/controllers/api/health.php
- app/init/resources.php
- app/worker.php
- src/Appwrite/Platform/Tasks/ScheduleBase.php
- src/Appwrite/Platform/Tasks/ScheduleExecutions.php
- src/Appwrite/Platform/Tasks/ScheduleFunctions.php
Reverts appwrite/appwrite#10287
> Revert "Feat: Make functions worker customizable"

- docker-compose.yml
- tests/e2e/Client.php
- tests/e2e/Services/Functions/FunctionsCustomClientTest.php
updates executor to allow head requests and adds tests for it
before - 
after -
> feat: allow HEAD requests and add test for it

- app/config/specs/open-api3-1.7.x-client.json
- app/config/specs/open-api3-1.7.x-console.json
- app/config/specs/open-api3-1.7.x-server.json
- app/config/specs/open-api3-latest-client.json
- app/config/specs/open-api3-latest-console.json
- app/config/specs/open-api3-latest-server.json
- app/config/specs/swagger2-1.7.x-client.json
- app/config/specs/swagger2-1.7.x-console.json
- app/config/specs/swagger2-1.7.x-server.json
- app/config/specs/swagger2-latest-client.json
- app/config/specs/swagger2-latest-console.json
- app/config/specs/swagger2-latest-server.json
- app/controllers/api/databases.php
- docs/references/databases/create-documents.md
- docs/references/databases/delete-documents.md
- docs/references/databases/update-documents.md
- docs/references/databases/upsert-document.md
- docs/references/databases/upsert-documents.md
- src/Appwrite/SDK/Method.php
- src/Appwrite/SDK/Specification/Format/OpenAPI3.php
> chore: remove experiment warnings from bulk methods

- app/controllers/api/databases.php
- composer.lock
- tests/e2e/Services/Databases/DatabasesBase.php
> Fix uncaught invalid arg

- app/config/events.php
Add the `upsert` event because it's triggered by [`databases.upsertDocument()`](https://github.com/appwrite/appwrite/blob/8a7a894b65df05a63a9c048b1860cc48dd9c6191/app/controllers/api/databases.php#L4231).
In addition, this is important because this config is used as validation for [webhooks](https://github.com/appwrite/appwrite/blob/8a7a894b65df05a63a9c048b1860cc48dd9c6191/app/controllers/api/projects.php#L1208) and [functions](https://github.com/appwrite/appwrite/blob/8a7a894b65df05a63a9c048b1860cc48dd9c6191/src/Appwrite/Platform/Modules/Functions/Http/Functions/Update.php#L79) as part of [event validation](https://github.com/appwrite/appwrite/blob/8a7a894b65df05a63a9c048b1860cc48dd9c6191/src/Appwrite/Event/Validator/Event.php#L36).
(Write your test plan here. If you changed any code, …
> fix: add missing upsert event

- composer.lock
> Databaselib  bump 0.71.15

- app/config/templates/site.php
Fixes issues in the config for the event template
- Locally setup Appwrite from source and deploy the sites template
- N/A
> Fix event template configuration issues

- src/Appwrite/Utopia/Response/Model/Execution.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
- tests/e2e/Services/Sites/SitesCustomServerTest.php
- adds deploymentId to execution response
- Ensures filters for deploymentId work in listExecutions
- All above for both sites and functions
New tests
x
> Feat: execution.deploymentId response model

- app/config/locale/templates/email-base-styled.tpl
- app/config/locale/templates/email-base.tpl
- app/views/general/404.phtml
- app/views/general/error.phtml
- src/Appwrite/Transformation/Adapter/Preview.php
Uses Appwrite's assets server for fonts
> Chore: Utilize assets server for fonts

- app/controllers/api/databases.php
- tests/e2e/Services/Databases/DatabasesBase.php
> Fix Upsert No change

- src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Upsert.php
- tests/e2e/Services/Databases/Legacy/DatabasesBase.php
- tests/e2e/Services/Databases/TablesDB/DatabasesBase.php
> Upsert document no change

- composer.lock
> Bump 1.7.x

- app/config/specs/open-api3-1.8.x-client.json
- app/config/specs/open-api3-1.8.x-console.json
- app/config/specs/open-api3-1.8.x-server.json
- app/config/specs/open-api3-latest-client.json
- app/config/specs/open-api3-latest-console.json
- app/config/specs/open-api3-latest-server.json
- app/config/specs/swagger2-1.8.x-client.json
- app/config/specs/swagger2-1.8.x-console.json
- app/config/specs/swagger2-1.8.x-server.json
- app/config/specs/swagger2-latest-client.json
- app/config/specs/swagger2-latest-console.json
- app/config/specs/swagger2-latest-server.json
- app/controllers/api/account.php
- src/Appwrite/SDK/Method.php
- src/Appwrite/SDK/Specification/Format/OpenAPI3.php
- src/Appwrite/SDK/Specification/Format/Swagger2.php
> chore: add replacewith and deprecated since to account methods

- src/Appwrite/Platform/Modules/Functions/Http/Executions/Create.php
Change default method to `POST` in docs to be consistent with code
> Update default method in description

- app/config/specs/open-api3-1.8.x-client.json
- app/config/specs/open-api3-1.8.x-console.json
- app/config/specs/open-api3-1.8.x-server.json
- app/config/specs/open-api3-latest-client.json
- app/config/specs/open-api3-latest-console.json
- app/config/specs/open-api3-latest-server.json
- app/config/specs/swagger2-1.8.x-client.json
- app/config/specs/swagger2-1.8.x-console.json
- app/config/specs/swagger2-1.8.x-server.json
- app/config/specs/swagger2-latest-client.json
- app/config/specs/swagger2-latest-console.json
- app/config/specs/swagger2-latest-server.json
- app/controllers/shared/api.php
- composer.lock
- src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Upsert.php
- src/Appwrite/Platform/Modules/Databases/Http/TablesDB/Tables/Rows/Upsert.php
- src/Appwrite/Platform/Modules/Databases/Workers/Databases.php
- src/Appwrite/Utopia/Request/Filters/V20.php
> Fix nested filter selects

- app/config/specs/open-api3-1.8.x-console.json
- app/config/specs/open-api3-1.8.x-server.json
- app/config/specs/open-api3-latest-console.json
- app/config/specs/open-api3-latest-server.json
- app/config/specs/swagger2-1.8.x-console.json
- app/config/specs/swagger2-1.8.x-server.json
- app/config/specs/swagger2-latest-console.json
- app/config/specs/swagger2-latest-server.json
- src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Bulk/Upsert.php
- src/Appwrite/Platform/Modules/Databases/Http/TablesDB/Tables/Rows/Bulk/Upsert.php
> chore: update description for upsert methods

- composer.lock
- src/Appwrite/Event/StatsUsage.php
- src/Appwrite/Platform/Workers/Migrations.php
Reverts appwrite/appwrite#10400
> Revert "Added handling of database resources after migration"

- app/config/errors.php
- app/controllers/api/avatars.php
- src/Appwrite/Extend/Exception.php
> chore: update exception thrown when svg sanitization fails

- app/controllers/shared/api.php
- app/init/resources.php
> chore: make webhooks publisher overridable

- tests/e2e/Services/Databases/Legacy/DatabasesBase.php
- tests/e2e/Services/Databases/TablesDB/DatabasesBase.php
> Fix mysql tests

- app/controllers/general.php
- composer.lock
- src/Appwrite/Utopia/Response.php
Due to recent array-like header value changes, screenshots were facing some issues on production when response was getting double-compressed.
This PR fixes it
Manual QA on stage
x
> Fix: router compression

- app/config/specs/open-api3-1.8.x-console.json
- app/config/specs/open-api3-1.8.x-server.json
- app/config/specs/open-api3-latest-console.json
- app/config/specs/open-api3-latest-server.json
- app/config/specs/swagger2-1.8.x-console.json
- app/config/specs/swagger2-1.8.x-server.json
- app/config/specs/swagger2-latest-console.json
- app/config/specs/swagger2-latest-server.json
- composer.lock
- src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/XList.php
- src/Appwrite/SDK/Specification/Format/OpenAPI3.php
- src/Appwrite/SDK/Specification/Format/Swagger2.php
- tests/e2e/Services/Databases/Legacy/DatabasesBase.php
- tests/e2e/Services/Databases/TablesDB/DatabasesBase.php
* Bumping sdk gen and database
* Updating the sdk docs example via the database spatial validator
* Updating xlist for find methods for throwing query error in case where we are currently throwing error for the spatial types distance methods
> Spatial type attributes sdk updates

- app/controllers/api/storage.php
> Catch query exception on bucket/file list

- composer.lock
> bump database 1.5.0

- app/controllers/shared/api.php
> Move disable

- app/config/specs/open-api3-1.8.x-console.json
- app/config/specs/open-api3-1.8.x-server.json
- app/config/specs/open-api3-latest-console.json
- app/config/specs/open-api3-latest-server.json
- app/config/specs/swagger2-1.8.x-console.json
- app/config/specs/swagger2-1.8.x-server.json
- app/config/specs/swagger2-latest-console.json
- app/config/specs/swagger2-latest-server.json
- src/Appwrite/SDK/Specification/Format.php
> Fix healthstatus enum

- src/Appwrite/Platform/Modules/Functions/Workers/Builds.php
> chore: update afterbuild fn

- src/Appwrite/Platform/Modules/Functions/Workers/Builds.php
> chore: update afterbuild to also pass adapter

- app/config/specs/open-api3-1.8.x-console.json
- app/config/specs/open-api3-latest-console.json
- app/config/specs/swagger2-1.8.x-console.json
- app/config/specs/swagger2-latest-console.json
- app/controllers/api/projects.php
- src/Appwrite/Utopia/Response/Model/Platform.php
> fix: enum typing for platform in specs

- src/Appwrite/Platform/Modules/Functions/Workers/Builds.php
> fix: buildOutput attribute name in deployment check

- app/realtime.php
> Sanitize 5xx errors on realtime
