- app/controllers/locale.php
Fixed typo `symol` -> `symbol` :)
My samll contribution to the environment.
> fixed typo

- docs/tutorials/add-oauth-provider.md
Signed-off-by: Akshit Sarin <akshitsarin99@gmail.com>
• '*corrrectly*' to 'correctly'
> Fixed typo in docs/tutorials/add-oauth-provider.md

- docs/references/auth/confirm-resend.md
- docs/references/auth/login.md
- docs/references/auth/logout.md
- docs/references/auth/recovery-reset.md
- docs/references/auth/register.md
- docs/references/avatars/get-browser.md
- docs/references/avatars/get-credit-card.md
- docs/references/avatars/get-flag.md
- docs/references/avatars/get-image.md
Fixed multiple errors on reference documentation:
1. `references/auth`: Fixed typos on documentation on following:
- `once` -> `ones`
- Changed `Redirect Attacks` to `Redirect Attack`
- `URL's` -> `URLs` to be consistent with rest of documentation
- `added` -> `adding`. May need to be changed depending on context (i.e. `added` -> `you added`)
2. `references/auth/confirm-resend.md`: 
- Changed `acts` to `act` (might need to change `arguments` to `argument` instead)
3. `references/avatar`: Typo and grammar errors on:
- `appear` -> `it appears`
- `there` -> `their`
- `cases` -> `case`
- Replaced some inappropriate commas with periods
- Removed `a` in front of `2 letter country code`
> Fixed errors in reference documentation

- app/config/locale/es.continents.php
Update on es.continents.php. 'AN' with 'Antártida'(Related to  #25). It's the most used form.
The previous translation was 'Antártica' which is used in Chile. Sorry, but when I read it, I thought that it was a wrong translation, here in Argentina it's not used. I checked it, It's valid but it's not very common to use it in Latin America and it's not used in Spain. Only in Chile.
Refer: http://lema.rae.es/dpd/?key=Ant%C3%A1rtida
> Fix for typos in es translations

- CHANGES.md
- app/controllers/auth.php
- app/views/console/users/index.phtml
Updated the path of our OAuth login route to allow better API predictability when we introduce new login methods in the future.
New login method mights include:
/auth/login/sms
/auth/login/passwordless || /auth/login/email || /auth/login/otp
/auth/login/qrcode
etc...
> Changed OAuth paths and some route titles

- docker/entrypoint.sh
Backtick command substitution `...` is legacy syntax with several
issues.
1. It has a series of undefined behaviors related to quoting in POSIX.
2. It imposes a custom escaping mode with surprising results.
3. It's exceptionally hard to nest.
$(...) command substitution has none of these problems, and is therefore
strongly encouraged.
> Replaced $(...) instead of legacy backticked `...`

- tests/e2e/BaseConsole.php
- tests/e2e/BaseProjects.php
- tests/e2e/Client.php
- tests/e2e/ConsoleHealthTest.php
- tests/e2e/ConsoleProjectsTest.php
- tests/e2e/ConsoleTest.php
- tests/e2e/ProjectAvatarsTest.php
- tests/e2e/ProjectDatabaseTest.php
- tests/e2e/ProjectLocaleTest.php
- tests/e2e/ProjectUsersTest.php
- Removing unused white spaces.
- Adding native type hints for every method arguments and return type hints.
- Using the `assertCount` to assert expected count is same as result.
- The PHPUnit fixtures are `protected setUp(): void` and `protected tearDown(): void`.
> Test enhancement

- README.md
It's important for the licence badge to be on README.markdown as it improves the visibility of the documentation.
> Added Licence badge in README.md

- docker-compose.yml
All of the containers the compose file creates should be named the same regardless of where the docker-compose file is ran from. 
i.e running this currently from a folder called appwrite defines the container name for redis as;
```
appwrite_redis_1 
```
This change will now make the redis container name;
I can see the main appwrite container already has this but the rest do not. 
```
appwrite_redis
```
> add container_name to all of the compose containers

- docs/tutorials/add-oauth2-provider.md
I have corrected the links for Code of Conduct and Contribuiting Guide mentioned in "add-oauth2-provider.md". These links are now pointing to the right pages.
> doc-577-corrected-links-in-"add-oauth2-provider.md"-file

- CHANGES.md
- app/views/install/compose.phtml
- docker-compose.yml
Updated all origin images version and now we are using alpine as the base images for all of them (redis, traefik, and influxdb).
> Feat update base images

- app/controllers/api/database.php
- app/controllers/api/functions.php
- app/controllers/api/projects.php
- app/controllers/api/storage.php
- app/controllers/api/teams.php
- app/controllers/api/users.php
- app/tasks/migrate.php
- app/workers/certificates.php
- app/workers/deletes.php
- src/Appwrite/Database/Adapter/MySQL.php
- src/Appwrite/Database/Database.php
Optimized system queries by using the internal Appwrite numeric ID as sort field instead of using an extra join/s for custom field. This change was only applied to queries where the sort was done by according to creation date which can be replaced by our incremental numeric ID (the internal ID, not the public UID that looks like: "5e63e0a61d9c2").
Leveraging current test plan.
None.
Yes.
> Feat remove default order field where possible

- CONTRIBUTING.md
- docker-compose.yml
Replaces standard ports like 8080, 3306 1080 and other with ports in the range of 9500-9504. This is done to minimize conflict with occasional contributors that might have this standard ports already taken by other apps or containers.
None.
Yes.
> Feat switch standard ports to 95xx prefix 

- app/controllers/api/storage.php
The storage controller uses $as param for converting between PDF and text files. This is being deprecated since it is not secure. 
N/A
None
Yes
> Fix: deprecate the $as option

- app/controllers/general.php
- src/Appwrite/Utopia/Response.php
- src/Appwrite/Utopia/Response/Filters/V06.php
- tests/unit/Utopia/Filters/V06Test.php
- tests/unit/Utopia/ResponseTest.php
Fix for autoloading warning thrown by composer:
```
Class Appwrite\Utopia\Response\Filter\V06 located in ./vendor/appwrite/server-ce/src/Appwrite/Utopia/Response/Filters/V06.php does not comply with psr-4 autoloading standard. Skipping.
```
N/A
#772 
Yes.
> Minor fixes for composer warnings about autoloading

- src/Appwrite/Migration/Migration.php
- src/Appwrite/Migration/Version/V06.php
Fix for comparison bug not detecting changes in object keys thinking both are the same. This was specifically detected on the `passwordUpdate` migration. The value stayed the same and only its key was changed. The final object structure was correct, but the save never happened because the comparison was only looking for changes in values, while ignoring keys. 
Yes
> Fix migration comparison bug

- app/config/variables.php
- app/workers/functions.php
Disable the cpus, memory and swap options while running functions environment if corresponding environment variables are empty.
Yes
> Disabling functions cpus and memory limit when environment is empty

- app/controllers/general.php
When there is no response filter header in the request, set default filter instead of throwing exception
> Avoid errors when response-format header is not available

- app/config/variables.php
- app/init.php
- app/workers/certificates.php
- `_APP_SYSTEM_SECURITY_EMAIL_ADDRESS` variable is now required in the setup process
- Change default value for `_APP_SYSTEM_SECURITY_EMAIL_ADDRESS` to an empty string
- Throws an error when `_APP_SYSTEM_SECURITY_EMAIL_ADDRESS` is empty on certs worker
- Print Letsencrypt std error message on the certs worker logs
Related to some user issues raised on Discord
✅
> Force security email and better SSL errors

- CHANGES.md
- composer.json
- composer.lock
This PR addresses an abandoned package warning in composer by following its instructions: 
`Package domnikl/statsd is abandoned, you should avoid using it. Use slickdeals/statsd instead.`
Dependencies don't change, according to `composer.lock`.
- Hit any logged endpoint
- Verify endpoint activity is reflected in graphs in the console.
N/A
Yes
> Updated domnikl/statsd to slickdeals/statsd

- app/controllers/mock.php
Added 2 new mock routes for simulating HTTP errors:
https://localhost/v1/mock/tests/general/400-error
https://localhost/v1/mock/tests/general/500-error
I will update the swagger spec file in the SDK generator, so we can use new methods to test our custom exceptions using those routes.
N/A
All new custom exceptions PRs on the SDK-Generator
Yes
> Added new routes to mock errors

- app/config/variables.php
changes security email to `certs@appwrite.io` and makes the env variable optional to not be asked in the installation.
✅
> fix-security-email

- CHANGES.md
- app/controllers/api/account.php
- app/controllers/api/users.php
Correctly assigns `countryName` from `countryCode`, as the associative array `$countries` expects uppercase country codes.
- Login to public-facing appwrite server
- Navigate to `/console/account/activity`
- Verify countryName is not `Unknown` in the UI or in the network request to `GET /account/sessions`
#933 
Yes.
> Use uppercase countryCode as index for $countries assoc array

- CHANGES.md
- app/config/roles.php
- app/controllers/api/functions.php
- tests/e2e/Services/Functions/FunctionsCustomClientTest.php
- Only logged in users can execute functions (for guests, use anonymous login)
- Only the user who has triggered the execution get access to the relevant execution logs
API Keys, console users, schedules, and event functions still have access to all executions.
Added a new test.
N/A
Yes.
> Feat execution permission

- src/Appwrite/Database/Adapter/MySQL.php
- save `0` as false value in database for filtering
I didn't see a smart way to introduce `true`/`false` into the filters - since the querying of the collection rules and the parsing of the filters happen in two completely different classes. Meaning I would need to repeat one of them for introducing true/false.
✅
> fix: save false values in database for filtering

- src/Appwrite/Migration/Migration.php
- prevents throwing error when document is missing id
- shows warning when document with a missing ID is found
✅
> fix(migration): prevent throwing error when document is missing ID

- app/controllers/api/functions.php
- app/controllers/shared/api.php
- app/tasks/sdks.php
- app/workers/functions.php
- app/workers/mails.php
- app/workers/webhooks.php
Drops all DB related stuff from the webhooks worker and just pass the relevant data from the API point where we trigger the task for the worker?
The worker is only accessing  the db to fetch the project's webhooks list which is already available to us in the relevant API scope. This change will increase the size of the task payload but will reduce database queries, improve speed, and make the webhooks worker completely independent.
Leverage e2e tests
N/A
Yes
> Feat stateless webhooks worker

- app/controllers/api/account.php
- tests/e2e/Services/Account/AccountCustomClientTest.php
- Adds missing session `$id` to anon account
- Adds test to check for the `$id` and `userId` after creating anon session
✅
> fix(account): add anon session id

- app/controllers/api/users.php
- docs/references/users/update-user-verification.md
- tests/e2e/Services/Users/UsersBase.php
Adds a new endpoint PATCH `/v1/users/{userId}/verification` that accepts a boolean `status` parameter that updates the email verification status for the user
> Update Email verification

- app/workers/functions.php
Fixed a problem that caused the creation of already running functions which was causing a docker conflict error. This error was happening when the max container limit has reached and the cleanup method was wrongly removing the containers list array keys.
Existing tests.
#1232 
Yes.
> Updated sort method before containers cleanup

- bin/schedule
- bin/worker-audits
- bin/worker-certificates
- bin/worker-deletes
- bin/worker-functions
- bin/worker-mails
- bin/worker-tasks
- bin/worker-usage
- bin/worker-webhooks
Updated INTERVALS of php-resque
In general, this PR speeds up functions, webhooks and tasks by up to 5 seconds. Also, it speeds up the overall speed of the appwrite.
I run a whole project on Appwrite using functions and real-time feature.
Before using this fork, the time between running `createExecuton` and receiving the update event using real-time took 4-5 seconds.
Using this fork, I reduced the time to 1s.
I tested everything on a function that takes ~1s to execute (load libraries into NodeJS, connect to MySQL server, get some data, process them and console log result). If a request takes 1s, it means 0ms delay due to Appwrite.
Currently, Appwrite uses the default INTERVAL configuration which is 5 seconds:
https://github.com/resque/php-resque/blob/master/lib/Resque.php#L13 …
> Execute functions up to 5 seconds faster

- app/controllers/api/storage.php
- Fixes missing gravity in cache key in storage preview endpoint
N/A
YES
> fix-gravity-cache

- app/controllers/api/account.php
- src/Appwrite/Database/Adapter.php
- src/Appwrite/Database/Adapter/MySQL.php
- src/Appwrite/Database/Adapter/Redis.php
- src/Appwrite/Database/Database.php
- tests/e2e/Services/Account/AccountBase.php
This PR Fixes the behavior of not being able to create a new account with a email address if it has been previously used but changed using the change email endpoint. It fixes this by correctly cleaning up the unique key when the email gets updated.
https://github.com/appwrite/appwrite/issues/1104
https://github.com/appwrite/appwrite/issues/1295
Yes, I have
> Fix Unique Keys not being updated when changing a user's email address

- app/controllers/api/database.php
- sets a default value for getting rules on `listDocuments`
✅
> fix(database): default value for empty rules

- app/workers/functions.php
Fixes a tiny mistake, adding an `"` to wrap the environment name properly in the log.
Did not test, should not cause any bugs.
I noticed a bug when someone reported their error on Discord and the environment name was missing.
> Added " to wrap environment name in a log

- app/tasks/install.php
- escapes shell args for running Appwrite the first time installation
- when using a `$` char anywhere in the questions answered during the installation process, bash interprets the dollar sign and messes up the env variables for the first `docker-compose up -d`
> fix(install): escape shell args

- app/workers/functions.php
This PR will fix a bug where commands could potentially run before a the code tar file has finished extracting. This PR seperates the untarring process into it's own execute command and makes it a blocking task. 
I have tested it thoroughly manually and through the automatic phpunit tests.
This issue was brought up on the discord server: https://discord.com/channels/564160730845151244/564161373148414012/867413956833968158
Yes, I have
> FIX Commands executing before the tar has finished extracting

- docker-compose.yml
- tests/e2e/General/HTTPTest.php
The Swagger validator [Docker image](https://hub.docker.com/r/swaggerapi/swagger-validator-v2) is only available for `amd64`, not ARM, causing the test suite to fail on `arm64`. 
This PR reverts back to checking the spec against https://validator.swagger.io in tests.
If this PR is successful, ARM tests should 🟢 
https://github.com/appwrite/appwrite/pull/1415
Yes.
> Fix - remove local swagger validator

- .travis.yml
- upgrade ci distro to `focal`
- use `arm64-graviton2` instead of `arm64`
✅
> ci(travis): improve build speed and arm stability

- app/controllers/api/database.php
- composer.lock
- tests/e2e/Services/Database/DatabaseBase.php
This PR catches `\Utopia\Database\Exception\Duplicate` when creating or updating documents. This catches the enforcement of unique indexes.
Tests included in the PR.
https://github.com/utopia-php/database/pull/63 must be released for these tests to pass.
Yes.
> fix(refactor-db): catch duplicate exception when creating and updating documents

- CONTRIBUTING.md
Fixes the anchor link in [Tools and Libs](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md?plain=1#L102) in [CONTRIBUTING.md](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md) that refers to the **Technology Stack** heading 
1. Visit [Tools and Libs](https://github.com/appwrite/appwrite/blob/7ca025f1ad84322189ea0e1ec8ee02579ab7e3dd/CONTRIBUTING.md#tools-and-libs) in CONTRIBUTING.md in the branch
2. Click on the **Technology Stack** link
None
Yes
> Fix anchor link to Technology Stack heading

- app/workers/functions.php
- fixes casting an env variable to integer
- set count to `0` by default (unlimited)
✅
> fix(functions): properly cast cpu counts variable

- app/controllers/general.php
- skips auto generating ssl certificate on doing acme challenge
- #1581 
✅
> fix(ssl): skip auto generation with acme challenge

- app/controllers/api/account.php
Fix default Failure and Success URL to use User's instance instead of Appwrite.io
YES
> fix-oauth-default-succss-failure-url

- .travis.yml
- app/tasks/maintenance.php
- app/workers/deletes.php
In https://github.com/appwrite/appwrite/pull/1557, code was added to clean up usage stats. The last commit https://github.com/appwrite/appwrite/pull/1557/commits/b38c77255e0d03e4e5206a5da09ede133d7ec508 updates the constant for the delete queue, but the constant was not updated in the task or worker. 
This bug was deceptive because the test suite passed with this change: https://app.travis-ci.com/github/appwrite/appwrite/jobs/536125257. However, if you look at the output of `docker ps`, you'll see `appwrite-maintenance` fails to start.
This PR uses the updated constant in the maintenance task and deletes worker.
The Travis job has been updated to exit if any container is in exited status.
https://github.com/appwrite/appwrite/pull/1557
Yes.
> fix(refactor-db): use correct constant when deleting usage stats

- .travis.yml
- Dockerfile
This PR makes a few changes to the structure of the Dockerfile and Travis config to allow for much faster builds:
- Uses `buildkit` as the build engine, which is much better at running builds in parallel
- Breaks the `compile` step into multiple stages, since we can use [a previous stage as a new stage](https://docs.docker.com/develop/develop-images/multistage-build/#use-a-previous-stage-as-a-new-stage)
- Renames stages to be descriptive, instead of serial.
- Calls `docker-compose pull` before bringing the stack up, which pulls images in parallel
Test suite will demonstrate the build change is successful.
https://app.travis-ci.com/github/appwrite/appwrite/jobs/535129292
https://github.com/appwrite/appwrite/issues/714
Yes.
> Feat - Parellel builds to reduce build time

- app/controllers/api/database.php
This PR changes the response model of `getAttribute` to be oneOf the list of typed attributes.
API spec check tests cover this change.
https://github.com/appwrite/appwrite/pull/1484
Yes.
> Return oneOf models for getAttribute

- README.md
This PR will mention [Godot Engine](https://godotengine.org/) community-maintained SDK in the README
No test plan required.
[Implement Godot SDK](https://github.com/appwrite/sdk-generator/issues/276#issuecomment-934114150)
[Mention SDK](https://github.com/appwrite/awesome-appwrite/pull/365#issuecomment-955645247)
Yes, I did
> Add Godot Engine SDK to Community SDKs

- app/controllers/api/database.php
- app/controllers/api/functions.php
- app/controllers/api/projects.php
- app/controllers/api/storage.php
- app/controllers/api/users.php
This PR updates the `usage` routes to backfill with empty record if the range (e.g. 30d) doesn't have a full history (created 5d ago). The following controllers were affected:
- database
- functions
- projects
- storage
- users
Can verify visually that stats are backfilled.
N/A
Yes.
> Backfill usage stats with empty records when required

- README.md
Removes unnecessary **Getting Started for iOS (Coming soon...)** list item from the [Getting Started](https://github.com/appwrite/appwrite/tree/docs-remove-unnecessary-getting-started-tutorial-link#getting-started) section of the Readme since the **Getting Started for Apple** tutorial has already been added. 
No tests since this is just an update in the Readme
None
Yes
> (docs): Remove unnecessary Getting Started tutorial link

- src/Appwrite/Utopia/Response.php
- src/Appwrite/Utopia/Response/Model/Func.php
- src/Appwrite/Utopia/Response/Model/FuncPermissions.php
Fixes the response model for Function permission, previously it was using the permission but as function only has execute permission and not read-write so it was not working as expected
N/A
YES
> fix function model permission

- app/controllers/api/database.php
- tests/e2e/Services/Database/DatabaseCustomServerTest.php
When a collection's schema changes via `createAttribute` or `deleteAttribute`, the externalDB cache can still contain documents with now invalid schema. This PR purges the externalDB cache whenever the underlying collection schema is updated.
Added test to check cache after deleteAttribute.
N/A
Yes.
> fix(refactor-db): purge external database cache on schema update

- src/Appwrite/Specification/Format/OpenAPI3.php
- src/Appwrite/Specification/Format/Swagger2.php
Fixes swagger spec for new Permission validator (before considered as String, now Array as it should be)
YES
> Fix-swagger-spec-for-permissions

- composer.json
- composer.lock
`Redis::del()` doesn't properly process file globbing, so this PR updates the Utopia\Cache library to recognize this pattern and fetch the appropriate keys first.
Unit tested the change in Cache lib.
https://github.com/utopia-php/cache/pull/16
Yes.
> fix(refactor-db): fix cache purging while file globbing

- app/controllers/api/storage.php
- tests/e2e/Services/Storage/StorageBase.php
Allows dev to rotate image by providing negative number as input.
The test for -315 degrees image rotation is exactly the same as the test for 45 degrees rotation. So, creating a new file with the former rotation angle and keeping other parameters same as the latter angle's test verifies that the code works properly.
Fixes #2387
Yes
> Support negative numbers in file preview

- app/controllers/api/account.php
- app/controllers/api/database.php
- app/controllers/api/storage.php
- app/controllers/api/teams.php
- app/controllers/general.php
- app/controllers/shared/api.php
- src/Appwrite/Auth/Auth.php
- tests/e2e/Services/Storage/StorageCustomClientTest.php
- tests/unit/Auth/AuthTest.php
- checks for an Admin User to skip permissions check on File and Document create/update
- fixes error message
- use `Authorization::getRoles()` over accessing the static property
- make `isAppUser()` and `isPrivilegedUser()` work with non assoc arrays
https://github.com/appwrite/appwrite/discussions/2451#discussioncomment-1771016
✅
> fix(database/storage): permissions using an admin user

- app/controllers/api/database.php
- tests/e2e/Services/Database/DatabaseBase.php
- tests/e2e/Services/Database/DatabaseCustomServerTest.php
- tests/e2e/Services/Database/DatabasePermissionsGuestTest.php
- tests/e2e/Services/Database/DatabasePermissionsMemberTest.php
- tests/e2e/Services/Database/DatabasePermissionsTeamTest.php
- tests/e2e/Services/Realtime/RealtimeConsoleClientTest.php
- tests/e2e/Services/Realtime/RealtimeCustomClientTest.php
- tests/e2e/Services/Webhooks/WebhooksBase.php
- tests/e2e/Services/Webhooks/WebhooksCustomServerTest.php
- replaces `attributeId` and `indexId` with `key` to avoid confusion
We already use `$id` internally and concatenate the collection id and key. This is needed, since otherwise keys would need to be unique across collections.
- adapted existing tests
✅
> feat: replace attributeId and indexId with key

- app/controllers/api/database.php
- app/controllers/shared/api.php
- src/Appwrite/Messaging/Adapter/Realtime.php
- tests/e2e/Services/Database/DatabaseBase.php
- tests/e2e/Services/Database/DatabasePermissionsTeamTest.php
- tests/e2e/Services/Realtime/RealtimeCustomClientTest.php
- tests/unit/Messaging/MessagingTest.php
When using Document Level Permissions, we are supposed to ignore Collection Level Permissions and vice versa.
- Getting the Collection document is now always skipping authorization
- will not throw a `404` anymore, but a `401`
- fixed the returned `sum` on collection level permissions
- Fixed permission level for list, create, update and delete documents
Since this was discovered while I was working on Realtime, this PR also includes collection/document level permission for Realtime events:
- send the collection document as part of the event
- use collection permission or document permissions depending on the configured level
- extended tests for the Database
- added realtime tests
✅
> fix: collection level permissions

- app/views/console/functions/function.phtml
This PR fixes a small typo within the usage charts for functions where the milliseconds the function was active for is called seconds.
#2491 
Yes, I have
> Fix Functions Usage Chart Typo

- app/tasks/sdks.php
Fixes SDK CLI script that's causing parent folder to be pushed to git on linux
N/A
YES
> fix parent folder being copied in linux

- src/Appwrite/Utopia/Response/Model/User.php
- tests/e2e/Client.php
- tests/e2e/Services/Users/UsersBase.php
Fix: Force empty preferences to be object instead of array
- Not sure how to test as in php it would still be array. Verified manually by making a request that an object is returned instead of array
> Fix-prefs-response

- app/views/console/home/index.phtml
Previously it was not clear why data on the dashboard are not in sync. Now we show information to use so he knows what he can expect from usage stats in Appwrite.
Screensshots:
✅
> Improved dashboard aggregation UI

- src/Appwrite/Migration/Version/V11.php
- some documents can be left for previously deleted projects, this PR skips them
> fix: migration for leftover documents on deleted projects

- src/Appwrite/Utopia/Request/Filters/V12.php
When using 0.11 SDK, the `listDocuments` didn't function properly on boolean filters. Now the problem is resolved.
Manual testing
✅
> Fixed boolean request filters on listDocuments

- app/controllers/mock.php
Simple fix to set proper domain name in set cookie method in the mock API. Needed to pass the cookie test on SDKs
N/A
https://github.com/appwrite/sdk-generator/pull/322
YES
> set proper domain name while setting cookie in mock api

- app/views/console/settings/index.phtml
Deny last user from leaving a project by disabling the leave button, and adds a redirect to home console page if current user is the one leaving the project instead of getting permission error.
Because the project membership is using the teams API under the hood, I left this fix only on the UI level, not sure if we want to enforce this behavior on all Appwrite projects.
N/A
#1494
Many times.
> Fix for console memberships

- app/controllers/api/functions.php
- tests/e2e/Services/Functions/FunctionsCustomClientTest.php
Fixes an exception thrown when a function is executed without any execute permissions:
```
appwrite  | [Error] Method: POST
appwrite  | [Error] URL: /v1/functions/:functionId/executions
appwrite  | [Error] Type: Error
appwrite  | [Error] Message: Object of class Utopia\Database\Document could not be converted to string
appwrite  | [Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Validator/Authorization.php
appwrite  | [Error] Line: 61
```
Due to the `Authorization` implementation being updated to utopia-php/database from appwrite, where the appwrite implementation used to take a `Document` as the first parameter.
Test added in `e2e/Services/Functions/FunctionsCustomClientTest.php` that creates a function with no execution permissions then checks that attempting to …
> Fix function authorization exception

- app/config/collections.php
- app/controllers/api/database.php
- tests/e2e/Services/Database/DatabaseCustomServerTest.php
Add fulltext index for collections collection `name` column to fix `listCollections` when using the `search` parameter.
Currently throws a PDOException:
```
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 756
[Error] Type: PDOException
[Error] Message: Can't find FULLTEXT index matching the column list
[Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
[Error] Line: 64
```
Used the `listCollections` function from SDK's passing a value for the `search` parameter
Closes https://github.com/appwrite/sdk-for-kotlin/issues/18
> Fix list collections when passing `search` parameter

- Dockerfile
- tests/e2e/Services/Realtime/RealtimeBase.php
Pins to specific PHP and Alpine versions to avoid per-patch regressions.
Needed to add a small sleep to realtime tests which is unrelated to pinned versions.
Successful compilation and existing test suite are sufficient.
https://github.com/php/php-src/issues/7978
Yes.
> Fix: pin PHP to patch version

- app/controllers/api/teams.php
- tests/e2e/Services/Teams/TeamsBaseClient.php
This PR fixes a bug preventing non-owners from deleting their membership
I verified my changes by:
1. Create Team
2. Add User 1 as Owner
3. Add User 2 as Member
4. Log In with client SDK as User 2
5. Delete Membership
I've also updated the e2e tests to include a test for deleting membership as non-owner.
Fixes https://github.com/appwrite/appwrite/issues/2405
Yes
> Fix non-owner not able to delete their membership

- app/controllers/api/database.php
- tests/e2e/Services/Database/DatabaseCustomClientTest.php
This PR skips check for permissions when client updates document, but does not touch it's permissions.
Implemented one huge test-scenario for this
✅
> updateDocument permission check bugfix

- app/views/console/database/document.phtml
Improve UI of required and optional enum by:
- Optional now have empty option
- Required also have empty option for new documents, but wont let you submit until selected
- Empty options during creating will become default value
Manual QA:
https://user-images.githubusercontent.com/19310830/151188832-42e027c7-ff6f-441d-b101-4b77f6d8057d.mp4
https://github.com/appwrite/appwrite/issues/2698
✅
> Fix: enum AppwriteConsole UI

- src/Appwrite/Auth/OAuth2/Bitly.php
- src/Appwrite/Auth/OAuth2/Github.php
After the last OAuth refactor, Bitly and GitHub providers were not working properly, since they do not respond with JSON code. This PR fixes it.
Not sure if testing oauths other than manually is possible.
✅
> Fix non-json responding OAuth providers

- src/Appwrite/Messaging/Adapter/Realtime.php
- tests/e2e/Services/Realtime/RealtimeCustomClientTest.php
Current implementation allows event `documents.[ID]` to listen to document changes. This is limiting in combination with Custom IDs, as you can have same custom ID in two different collections.
This PR adds collection ID into event alongside document ID.
Updated relevant tests. Should pass before merging.
https://github.com/appwrite/appwrite/pull/2769
✅
> Feat: Migrated event channel

- src/Appwrite/Specification/Format/OpenAPI3.php
- src/Appwrite/Specification/Format/Swagger2.php
Forgot to separate between UID and CustomID so both fields were getting x-upload-id true. Was able to get sdk working because second parameter would override the first one.
Manually verified by generating the spec
YES
> fix spec for resumable upload

- app/controllers/general.php
During last release, we created bug that made LetsEncrypt challenges fail. This PR fixes it.
Manual QA on DO droplet:
✅
> Fix: 0.12 LetsEncrypt generation

- app/executor.php
Appends stdout to stderr when throwing a function runtime build error. In some cases, actual errors are in stdout instead of stderr.
Covered by existing tests
Yes
> Append stdout to function build error log

- app/workers/deletes.php
Fix delete worker deleting collection using wrong ID, causing dangling tables and inability to re-create attributes for existing collection IDs
> Fix delete collection using wrong ID

- composer.lock
Updates locker file to apply latest appwrite/runtimes changes - adding Dart 2.16
Manually create 2.16 function and test hello world code:
x
✅
> Fix: Runtimes version

- app/controllers/mock.php
Mock upload on chunked upload was causing after the new response params were added, because of file size treated as array
updated all to make more aligned with storage create file endpoint
YES
> fix mock upload

- app/views/install/compose.phtml
- docker-compose.yml
`_APP_EXECUTOR_SECRET` was not present in deletes worker, but he needs it for `$executor->deleteRuntime($projectId, $deploymentId);`. This PR adds configuration of this ENV var in there.
No tests, nothing should break.
x
Yes
> Fix: Updated environment secrets

- app/controllers/api/projects.php
- src/Appwrite/Network/Validator/Origin.php
Switch to using constants in the Appwrite platform whitelist to prevent mismatch in platform types during origin validation.
1. Add an Apple iOS platform
2. Make a POST API call using the added platform
3. Ensure there is no Invalid Origin error
[Invalid Origin for iOS Flutter App](https://github.com/appwrite/appwrite/issues/2898)
Yes.
> Fix platform type mismatch in origin validation

- app/executor.php
Increase limit from 8k to 16k. This is possible while staying in same database data-type.
Current tests should pass.
https://github.com/appwrite/appwrite/issues/2917
Yes
> Fix: Increase execution substring limit

- .gitpod.Dockerfile
- .gitpod.yml
- docker-compose.yml
This PR adds initial configuration for spinning up a dev environment for Appwrite with Gitpod. Developers can use the Gitpod browser extension "Open In Gitpod", or visit the https://gitpod.io/#https://github.com/appwrite/appwrite to launch a new instance. This will also allow us to enable prebuilds, so each commit to master will be built, allowing for faster startup times for new Gitpod workspaces.
- Appwrite runs on port 8080 instead of port 80 in Gitpod due to security reasons.
- PHP 8 is installed in Gitpod
Test this by going to https://gitpod.io/#https://github.com/appwrite/appwrite/pull/2891
(If this PR is …
> feat: add support for using Gitpod for development

- app/views/install/compose.phtml
Updates the docker-compose.yml template to ensure the appwrite-executor container starts after server restart just like the other services.
I updated my docker-compose.yml to add the same line to ensure the appwrite-executor container started after server restart.
https://github.com/appwrite/appwrite/issues/2932
Yes
> Fix appwrite-executor in compose.phtml

- app/controllers/general.php
This PR will move the throw that causes the double event log to before the first logger in called, this makes it so only the second logger will log the PDOException instead of both of them
Yes, I have
> Fix PDOException double event log

- app/views/console/comps/footer.phtml
GH issue URL in Appwrite Console does not show template options. Now it does.
https://github.com/appwrite/appwrite/issues/2976
✅
> Fix: GH issue url

- app/views/console/comps/header.phtml
- app/views/console/database/collection.phtml
- app/views/console/database/document.phtml
- app/views/console/database/index.phtml
- app/views/console/functions/index.phtml
- app/views/console/storage/index.phtml
- app/views/console/users/index.phtml
- composer.lock
The current frontend regex we use does not allow 1 letter attribute IDs, even tho backend allows it.
This PR fixed the regex to allow 1 letter IDs.
x
✅
> Fix:  Validation regex for custom ID

- app/executor.php
If `orchestration->run` fails, but container was already initialized, the cleanup would fail. This PR makes sure cleanup also takes care of this edge-case.
Manual QA for new edge-case, hard to simulate unless on a specific device (for instance Unbutu DO droplet with ENV set to MEMORY_SWAP=256.
Current tests should pass to ensure current cleanup works fine.
x
✅
> Fix: Orchestration Cleanup

- app/controllers/api/account.php
- docs/references/account/update-password.md
- tests/e2e/Services/Account/AccountBase.php
This PR fixes magic URL generated accounts from not being able to set a new password by setting the 'passwordUpdate' field on account creation to 0.
This PR also updates Anonymous session's `passwordUpdate` field to be 0 on user creation to keep better inline with the other non-password methods.
A new test has been added to `AccountBase.php` which will attempt to update the password after creating a new account using magicURL.
Yes, I have
> Fix 'magic URL' accounts from not being able to create a new password.

- Dockerfile
Updates the PHP base image from 8.0.14 to 8.0.17
Release notes here: https://www.php.net/ChangeLog-8.php#PHP_8_0
Yes
> Update PHP Docker Image to v8.0.17

- Dockerfile
Updates the PHP base image from 8.0.17 to 8.0.18
Release notes here: https://www.php.net/ChangeLog-8.php#PHP_8_0
Yes
> Update PHP Docker Image to v8.0.18

- app/init.php
- app/workers/database.php
- tests/e2e/Services/Database/DatabaseBase.php
- JSON encoding will loose trailing 0 values on floats - passing a flag to preserve them
- Fetch attribute again on database worker - since these values get lost as well in resque
- extended test
- https://github.com/appwrite/sdk-for-kotlin/issues/20
✅
> fix(database): casting of float values

- app/controllers/api/teams.php
At the moment, if you create a new user through membership, the `deleted`status is `NULL`:
That is a problem because in a query for listing users we check if `deleted` is `false`, which isn't in the case of NULL. So we end up with only one user listed:
By setting `deleted` to `false`, I can now see both users:
This PR addresses this bug and ensures that the `deleted` key is properly set to `false`. I also double-checked other places where we create users, and this was the only place with the `deleted` attribute missing.
- https://github.com/appwrite/appwrite/issues/3177
Yes
> Fix: Team User Creation

- app/controllers/api/database.php
Takes newly created `SortAttributes` validator and runs sort attributes through it. Thanks to this validator, we now force indexes on attributes user want to sort on, and prevent usage of unwanted attributes such as `_uid`.
TODO: We probably need to add bunch of tests
https://github.com/utopia-php/database/pull/106
✅
> Use validator on order attributes

- app/workers/certificates.php
- app/workers/deletes.php
I noticed multiple problems with certificates on custom domains, and addressed them all in this PR.
Currently, your second project would be stuck at `in progress` of cert creation, because `Renew isn't required`, which is true. This PR makes sure to set certificate ID on the domain, even tho renew isn't required.
https://user-images.githubusercontent.com/19310830/159718472-8c29373a-d6bb-4a90-a45e-fbd276f5b7bc.mp4
We currently only remove files, which results in Appwrite still thinking certificate is there (and renewal isn't required), even tho file is already missing and Traefik cannot communicate over HTTPS.
https://user-images.githubusercontent.com/19310830/159723802-5ae4466d-8302-404a-beb4-4c5405a24b34.mp4
With step 2 fixed, now if you delete a domain, it deletes the certificate too. …
> Fix: Certificates in general

- src/Appwrite/Auth/OAuth2/Google.php
Code quality changes in 0.14.x discovered wrong usage of Google API. User ID was missing, as the response does not give `id`, but `sub` instead.
> The response will be a JSON object with several properties about the user. The response will
> 
> **always include the sub key, which is the unique identifier for the user**.
> 
> Google also returns the user’s profile information such as name (first and last), profile photo URL, gender, locale, profile URL, and email. The server can also add its own claims, such as Google’s hd showing the “hosted domain” of the account when using a G Suite account.
Reference: https://www.oauth.com/oauth2-servers/signing-in-with-google/verifying-the-user-info/
Reported on Discord
Yes
> Fix: Google OAuth (userID)

- app/controllers/general.php
- app/workers/certificates.php
With this PR, if the domain in ENV is `localhost`, it will be ignored, and instead, we will use logic the same as if we didn't have any ENV domain set.
This is needed because `localhost` is the default value, and there is no way people want localhost to be their main domain 
(certificate for localhost won't work anyway).
With these changes, when using `localhost`, we still use the first visited domain as the main domain.
This PR also solves the DigitalOcean 1click setup so it properly generates SSL for the first domain without having to SSH into the server and updates ENV var.
x
Yes
> Fix: Main Domain

- app/tasks/install.php
- when a variable was missing in `.env` - we override its default with an empty value instead of the default value from the config
- manually tested
✅
> fix: installation overriding default env variables

- src/Appwrite/Auth/OAuth2/Zoom.php
Fixes a failing Zoom OAuth. problem seems to be related to the scope we request `user_profile`, which cannot be found in the Zoom dashboard:
I also found an unfinished discussion regarding this: https://devforum.zoom.us/t/has-user-profile-scope-been-removed/60857
After applying new scopes, I was able to successfully create a session:
Reported on Discord
Yes
> Fix: Zoom OAuth scopes

- app/workers/builds.php
The response from the executor no longer contains the `stdout` key. It was replaced by `response`
Existing tests & Manual QA
N/A
YES
> fix: empty build logs

- app/controllers/api/teams.php
Don't check the SMTP host env var when add team member API is called for admins/server SDKs since no email is actually sent.
1. Set `_APP_SMTP_HOST` env var to empty string
2. Add a user to a team
3. Confirm successful API call
Closes: https://github.com/appwrite/appwrite/issues/3283
Yes
> Bypass SMTP host check for admins adding team members

- docs/services/storage.md
Discussed in discord, adding this for give the _APP_STORAGE_LIMIT env variable more exposure. Since users might come to this doc page looking for information on max file size.
> doc: Add info about _APP_STORAGE_LIMIT environment variable to Storage doc

- app/config/collections.php
- app/controllers/api/projects.php
- app/workers/webhooks.php
- src/Appwrite/Utopia/Response/Model/Webhook.php
- tests/e2e/Scopes/ProjectCustom.php
- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
- tests/e2e/Services/Webhooks/WebhooksBase.php
- tests/e2e/Services/Webhooks/WebhooksCustomClientTest.php
- tests/e2e/Services/Webhooks/WebhooksCustomServerTest.php
> webhook signature

- src/Executor/Executor.php
Prevents unnecessary run of `sleep(2)` when executing a function for the first time (without runtime ready). Affects both `async=true/false`, but only really visible with `async=false`.
- https://github.com/appwrite/appwrite/issues/3332
Yes ✅
> Fix: Unnecessary execution delays

- CHANGES.md
- Dockerfile
- app/tasks/install.php
- composer.lock
`docker-compose` seems to not have some features Appwrite started using on development. As a first step before implementing these in production is to make Appwrite ready to use new `docker compose` syntax.
This PR removes `docker-compose` installation from  the Appwrite Docker image, and adds `docker compose`.
**This PR does not include documentation changes. They will be required before releasing.**
(Manual QA)
- Manually build Appwrite image `docker build . -t appwritest`
- Create Appwrite instance using new image:
```sh
docker run -it --rm \
--volume /var/run/docker.sock:/var/run/docker.sock \
--volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
--entrypoint="install" \
appwritest:latest
```
- Appwrite was started, and working properly
x
Yes
> Feat: Start using docker compose V2

- CONTRIBUTING.md
- app/tasks/install.php
- composer.lock
- docs/tutorials/add-oauth2-provider.md
- docs/tutorials/add-runtime.md
- docs/tutorials/add-storage-adapter.md
- docs/tutorials/add-translations.md
This PR updates the Docker Compose commands for 0.14.
Docker Compose V2 is now required. The command changed from `docker-compose` to `docker compose`. 
#3358 
> Update docker-compose to docker compose

- app/config/providers.php
Currently the OAuth2 docs URL in the providers section for **Yammer** leads to a deadlink (404 error). Seems that the documentation has been moved to a different URL which this PR addresses.
NIL
Yes
> fix: 404 OAuth2 docs url for Yammer

- app/views/console/webhooks/webhook.phtml
- allow re-generating webhook signature
messed up my commits somehow, the API is on the target branch 🙃 
https://github.com/appwrite/appwrite/blob/feat-prepare-0-15/app/controllers/api/projects.php#L731-L768
- manual
✅
> ui: allow generating a new webhook signature

- .gitpod.yml
Currently when you start Gitpod, it downloads preload, and then pull composer (to then update dependencies). With this change, image would be downloaded during rebuild, making Gitpod workspace a little bit faster.
x
Yes
> Feat: Improve Gitpod preloading

- app/views/console/databases/document.phtml
Arrow back from document to collection did not pass databaseId properly. Now it does.
x
Yes
> Fix: Arrow back

- app/controllers/api/databases.php
- tests/e2e/Services/Databases/DatabasesBase.php
Disallow user to change $createdAt in `updateDocument`.
x
Yes
> Fix: Lock $createdAt

- app/controllers/api/functions.php
- app/controllers/api/storage.php
- app/controllers/mock.php
- Makes `file` upload param type as `mixed` instead of `array` as that's causing `go` and `ruby` SDKs to fail and any way we are not using the parameter itself
- Existing tests
YES
> Fix file upload param type

- app/controllers/api/databases.php
- tests/e2e/Services/Databases/DatabasesBase.php
Fix the get collection usage API alias so it doesn't conflict with list documents
1. Created e2e test
2. Manual test
Before fix:
After fix:
#3504 
Yes
> Fix get collection usage alias

- app/controllers/api/databases.php
When you create a document, both $createdAt and $updatedAt are as expected. When you update the document tho, $createdAt is set to a weird date, but $updatedAt is updated as expected.
Later I found out that $createdAt is set to collection creation date, instead of the document. This PR fixes it.
- Tests will be written afterwards
x
Yes
> Fix: createdAt bug after updating document

- app/tasks/install.php
- docs/sdks/cli/GETTING_STARTED.md
`--all` for `init` and `deploy` was deprecated due to bug in `commander` library. Until we have proper solution, it will not be possible to use these parameters.
They were removed in favour of `deploy function --all` and `init collections --all` which are much more valuable commands. While those we deprecated can be achieved with 2 commands, replacing these mentioned would take a full-on bash script to list and init/deploy one by one.
Not necessary.
- https://github.com/appwrite/sdk-generator/pull/484
- https://github.com/appwrite/docs/pull/215
Yes
> Feat: Deprecate all parameter

- app/controllers/api/account.php
- tests/e2e/Services/Account/AccountBase.php
Add /v1/account/sessions as an alias for POST /v1/account/sessions/email
for backwards compatibility.
1. Add e2e test
2. Manual test
Before alias:
After alias:
#3510
Yes
> Add alias for POST /v1/account/sessions/email

- tests/e2e/Services/Databases/DatabasesBase.php
In 0.15.1 there was a bug when updating a document that changed `$createdAt` date: https://github.com/appwrite/appwrite/pull/3500
We quickly fixed this bug and released a new version.
This PR improves the PR above by adding tests to prevent this bug in the future.
- PR above
Yes
> Implemented updateDocument date tests

- app/controllers/api/projects.php
Hardcoded database name causes problems if `_APP_DB_SCHEMA` changes.
Manual test
Closes https://github.com/appwrite/appwrite/issues/3508
Yes
> Fix hardcoded appwrite database schema

- app/views/console/databases/database.phtml
- src/Appwrite/Utopia/Response/Model/Database.php
In 0.15 we refactored console into $createdAt and $updatedAt. There was one missing space which this PR fixes.
Also, the databases response model never exposed these 2 date attributes. Now it does.
- https://github.com/appwrite/appwrite/issues/3533
Yes
> Fix: Database dates

- app/init.php
- app/workers/messaging.php
- src/Appwrite/Auth/Phone/Msg91.php
- src/Appwrite/Auth/Phone/Msg91Flow.php
Hi I have integrated MSG91 service for phone adaptor. In MSG91 there are two modes of service 
1. Standard Transactional SMS
2. OTP service provided by them
This adaptor is based on first Standard Transactional SMS.
This will provide phone authentication through MSG91 Flow service
IN MSG91 service should create Flow based SMS with variable otp (Noted: Shouldn't set sender ID in flow since we are passing that as parameter)
In environment 
_APP_PHONE_PROVIDER value should be in format as phone://[senderID]:[authKey]@msg91
_APP_PHONE_FROM value should be flow ID created in Msg91(I have used this as place holder to pass flow ID)
No
Yes
> Feat phoneauth msg91flow

- app/controllers/api/functions.php
In the dashboard of the project, I can only see functions counter for executions made from the console manually (with async=true). In my app, I set async=false, and those are not counted.
This PR addresses the problem above.
x
Yes
> Fix: function usage missing

- app/config/variables.php
The timeout applies to a global limit and not individual functions. This has caused confusion to Appwrite developers. I don't think this PR alone solves the problem, I will add another PR to docs to further explain limits.
> Clarify purpose in Appwrite Functions timeout description

- app/controllers/api/users.php
- src/Appwrite/Usage/Calculators/TimeSeries.php
- tests/e2e/General/UsageTest.php
Fix usage bugs.
Updated tests/e2e/General/UsageTest.php
<details><summary>Full test log</summary>
```shell
$ docker compose exec appwrite test 
PHPUnit 9.5.20 #StandWithUkraine
Tests\Unit\Auth\AuthTest::testCookieName ended in 0.39877 milliseconds
.Tests\Unit\Auth\AuthTest::testEncodeDecodeSession ended in 0.05043 milliseconds
.Tests\Unit\Auth\AuthTest::testHash ended in 0.42204 milliseconds
.Tests\Unit\Auth\AuthTest::testPassword ended in 6044.478105 milliseconds
.Tests\Unit\Auth\AuthTest::testUnknownAlgo ended in 0.10568 milliseconds
.Tests\Unit\Auth\AuthTest::testPasswordGenerator ended in 0.051569 milliseconds
.Tests\Unit\Auth\AuthTest::testTokenGenerator ended in 0.037231 milliseconds
.Tests\Unit\Auth\AuthTest::testCodeGenerator ended in 0.3148 milliseconds …
```
> Fix usage tests

- app/views/console/functions/function.phtml
Fixes a small UI bug with variable names not wrapping
Before:
After:
Yes, I have
> Small fix to make variable keys wrap in UI

- app/views/console/databases/document.phtml
- adds missing `databaseId` to the activity page of documents
- manual
✅
> fix: ui missing database id from document activity

- app/controllers/api/databases.php
In the Create Index API, the type for the $createdAt and $updatedAt attributes were string instead of datetime.
1. Automated Tests
2. Manually Create Index
None
Yes
> Fix $createdAt and $updatedAt so they are datetime instead of string

- composer.json
- composer.lock
- src/Appwrite/Auth/Auth.php
- tests/unit/Auth/AuthTest.php
- tests/unit/Messaging/MessagingChannelsTest.php
- Assign `member` role to a user for all confirmed team memberships
Updated existing `Auth` and `MessagingChannel` tests
https://github.com/appwrite/sdk-generator/pull/546
https://github.com/utopia-php/database/pull/183
Yes
> Assign member role for all of a users confirmed team memberships

- CHANGES.md
- app/config/collections.php
- app/controllers/api/functions.php
- app/executor.php
- app/workers/functions.php
- src/Appwrite/Utopia/Database/Validator/Queries/Executions.php
- src/Appwrite/Utopia/Response/Model/Build.php
- src/Appwrite/Utopia/Response/Model/Execution.php
- tests/e2e/General/UsageTest.php
- tests/e2e/Services/Account/AccountBase.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
Rename the `time` attribute of Execution response model to `duration` to be more consistent with other Response Models
Existing Tests
NA
YES
> feat: rename time attribute to duration

- src/Appwrite/Usage/Calculators/TimeSeries.php
- Fixes issue with timeseries usage aggregation that it was always scanning the whole period instead from last time it was updated
Manual QA
YES
> fix the latest time memory store

- app/tasks/maintenance.php
- app/workers/certificates.php
- Fixes a type bug introduced after datetime refactor
- Fixes bug when retry attempts were not made after a failed generation
- Fix retry attempts from 6 to 5. 5 is intended, the check was incorrect.
- Handle certbot folder naming to ensure stability when renewing (sometimes certbot made folders `domain-0001`, `domain-0002`.. It was because we moved cert files which certbot doesn't like)
x
Yes
> Fix certificate worker and retries

- tests/e2e/General/UsageTest.php
Before this, usage tests retried creating usage AND fetching the usage which caused some expected counts to be incorrect.
Automated Tests
None
Yes
> Make usage tests only retry the usage fetch part

- app/views/console/functions/function.phtml
Fix UI after execution.time was renamed to execution.duration.
Manual Before:
Manual After
Previous PR:
* https://github.com/appwrite/appwrite/pull/3801
Yes
> Rename execution time to duration

- phpunit.xml
Since tests take almost 20 minute to run, stopping tests as soon as an failure occurs will allow for faster iteration locally and also free up resources in the CI pipeline.
None
None
Yes
> Stop tests on failure

- app/views/console/functions/function.phtml
Because it's possible for execution stdout to end up in the wrong execution, we're going to hide the result from the UI to help avoid confusion for users while we work on resolving the problem.
Manual Before:
Manual After:
None
Yes
> Hide function execution stdout from Console UI

- app/controllers/api/databases.php
- app/controllers/api/functions.php
- app/controllers/api/projects.php
- app/controllers/api/storage.php
- app/controllers/api/users.php
- tests/e2e/General/UsageTest.php
The backfilled dates were being returned like "2022-08-17 00:00:00.000. Safari had a problem parsing these and failed to load the usage graphs with the following console error:
Updated e2e usage tests
None
Yes
> Fix date format for usage APIs

- composer.lock
- tests/e2e/Services/Users/UsersBase.php
Existing tests only tested if hash password is imported, and session can be created. New tests also:
- Ensure passwords are re-hashed to argon2 after login
- Users can still login after password is re-hashed to argon2
x
Yes 😍
> Fix: Improve password hashing e2e tests

- app/workers/deletes.php
Delete worker does not delete function variables when function is deleted. It does now.
It is internal cleanup. No endpoint exposed it anyway. Not sure if we can have a test for it.
x
Yes
> Fix: Function deletes worker

- app/views/console/functions/function.phtml
Although there is still a known issue where function stdout logs can appear in the wrong execution, not having the logs easily accessible in the console makes troubleshooting functions significantly more difficult.
Manual before:
Manual after:
* https://github.com/appwrite/appwrite/issues/3934
* https://github.com/appwrite/appwrite/issues/3295
> Update Console to Show Function Stdout Logs

- app/views/console/functions/function.phtml
Before 1.0.x, function executions were async by default. This ensures executions starting 1.0.x are still async.
Manual:
* https://github.com/appwrite/appwrite/issues/3927
Yes
> Update function execution from console to be async

- README.md
PowerShell uses the backtick as line continuation character, not comma.
> Fix PowerShell line continuation character

- app/controllers/api/functions.php
- app/workers/functions.php
If you set schedule in `createFunction`, the schedule loop is never started. This occurs in Appwrite CLI. This PR solves it.
Also, this PR makes it so `updateFunction` forcefully re-triggers schedule loop. Old loop will be stopped, so no double executions. This is useful, for instance, when you clean your Redis instance and loop is gone. By clicking "Update" on function settings you can easily re-trigger the loop.
Manual QA for all edge cases I can think of:
x
Yes 😇
> Fix schedule loop triggering

- app/workers/builds.php
- app/workers/certificates.php
- app/workers/mails.php
We forgot to refactor the certificate worker regarding new Event classes, so he was not providing a proper structure of the data.
Also, the mails worker had an edge case for certificates email when he was expecting data that was not properly documented on the event.
This PR addresses that, as well as all the other places where new Event classes are not being utilized.
x
Yes 😇
> Fix: Certificate -> Mail worker communication

- CHANGES.md
- src/Appwrite/Migration/Version/V15.php
`time` attribute should be a DateTime.
Before fix:
After fix:
* #3949 
Yes
> Fix migration for audit

- CHANGES.md
- app/workers/deletes.php
Ensure attributes, indexes, and audit for correct database is deleted.
Closes #4427
Attributes and Indexes before and after database deletion shows attributes and indexes in database test1 are not deleted:
Audit during document deletion show documents are deleted as expected rather than no documents:
* https://github.com/appwrite/appwrite/issues/4427
Yes
Yes
> Only delete collection data for correct db

- CHANGES.md
- app/tasks/sdks.php
Update the SDK License to match The 3-Clause BSD License on [opensource.org](https://opensource.org/licenses/BSD-3-Clause). The difference made it so pub.dev was unable to detect the license.
I made the change to the SDK For Flutter and ran [`pana`](https://github.com/dart-lang/pana) to confirm it was able to detect the license.
* https://github.com/appwrite/sdk-for-flutter/issues/88
* https://github.com/appwrite/sdk-for-dart/issues/29
Yes
Yes
> Update SDK License to match opensource.org

- docs/tutorials/add-translations.md
Fixed the broken link
On line 65 Found there was additional brackets due to which the 'en.json' was not an hyperlink, so removed those brackets and now 'en.json' is an hyperlink leading to https://github.com/appwrite/appwrite/blob/locale/app/config/locale/translations/en.json
> Fixed the broken link

- app/controllers/api/users.php
- tests/e2e/Services/Users/UsersBase.php
Show correct toast or message when adding a duplicate phone number to a user.
Try to add duplicate phone number to different user to see the correct message.
* https://github.com/appwrite/appwrite/issues/3810
Yes
> fixed: wrong error message show on adding duplicate number to a user

- app/controllers/api/projects.php
- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
In the new console, one organization (team) can have multiple projects. This PR makes sure that a project can be deleted without forcefully also deleting a team.
x
Yes
> Deprecate team deletion with project

- README.md
- composer.lock
- docs/references/databases/list-documents.md
- docs/references/functions/list-executions.md
- docs/references/storage/list-files.md
- docs/references/teams/list-teams.md
Admin Mode is a legacy term that no longer makes sense in Appwrite 1.0. In all future versions, we should no longer refer to "Admin Mode". See the terminology section in https://github.com/appwrite/docs/pull/229
- Proposed documentation guidelines and terminology https://github.com/appwrite/docs/pull/229
> Remove references to admin mode

- CHANGES.md
- src/Appwrite/Usage/Calculators/Database.php
Pagination of projects did not work properly because callback causes the namespace to change. This caused pagination to not work, and only the first 50 projects got their stats updated. This would become a huge problem with Appwrite Cloud.
x
Yes
Yes
> V1: Fix: DB Usage projects pagination

- app/controllers/api/projects.php
- src/Appwrite/Utopia/Response.php
- src/Appwrite/Utopia/Response/Model/Project.php
- src/Appwrite/Utopia/Response/Model/Provider.php
- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
Current OAuth endpoints for Projects API is limiting as it does not allow to disable provider without deleting the data.
It also has weird response format where request ends up with MANY params on root-level.
- New response model
- Added `enabled` param to each adapter
⚠️ PR does not include UI changes
- Existing tests updated
- Improved tests to check for new `enabled` feature
x
Yes! 😎
> Feat: OAuth improvements

- app/controllers/general.php
- app/http.php
Remove the PDO rethrow.
The PDOException was rethrown in general.php so that it could be caught in the catch block of http.php. However, [a change in utopia-php/framework](https://github.com/utopia-php/framework/commit/9d37326851f65f354344cfe2e3c1a282d5231025) caused the exception to be masked as an Exception rather than the underlying PDOException. As such, the `$th instanceof PDOException` in http.php is always false and `$db = null` is never executed. Since these snippets of code aren't doing anything or adding value, they should be removed.
In addition, the `$db = null` may have been added to ensure the connection was added back to the pool and/or reset if needed, but it seems like that's not a problem anymore.
Manually tested to make sure queries to the DB were still working
* #4535 …
> Remove PDO rethrow

- CHANGES.md
- src/Appwrite/Messaging/Adapter/Realtime.php
- tests/e2e/Services/Realtime/RealtimeConsoleClientTest.php
Because the deployment event was missing the project ID, the realtime event never fired.
Debug logs before change:
```
appwrite  | triggering realtime: array (
appwrite  |   'channels' => 
appwrite  |   array (
appwrite  |     0 => 'console',
appwrite  |   ),
appwrite  |   'roles' => 
appwrite  |   array (
appwrite  |     0 => 'team:635308a7ad8f2093fb40',
appwrite  |   ),
appwrite  |   'permissionsChanged' => false,
appwrite  |   'projectId' => NULL,
appwrite  | )
```
debug logs after change:
```
appwrite  | triggering realtime: array (
appwrite  |   'channels' => 
appwrite  |   array (
appwrite  |     0 => 'console',
appwrite  |   ),
appwrite  |   'roles' => 
appwrite  |   array (
appwrite  |     0 => 'team:635308a7ad8f2093fb40',
appwrite  |   ),
appwrite  |   'permissionsChanged' => …
```
> Fix create deployment realtime not triggering

- app/controllers/api/projects.php
- src/Appwrite/Utopia/Response/Model/Project.php
- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
This PR fixes the defaults of the session API to make it not 0, it also implements new tests to ensure the default is set correctly.
This PR additionally converts the endpoint to handle seconds instead of minutes.
Tests have been updated to check defaults.
Yes
> Fix Session API Defaults and convert from minutes to seconds

- app/workers/functions.php
- src/Appwrite/Usage/Calculators/TimeSeries.php
- tests/e2e/General/UsageTest.php
- Add internal ID for async=true executions usage stats
- Stop only current aggregation when internal project id is missing
x
No changes from 1.0. Its just fixing bug we introducing in between versions.
Yes
> Fix: usage executions

- .env
- CHANGES.md
- app/config/variables.php
- app/init.php
- app/realtime.php
- app/views/install/compose.phtml
- composer.json
- composer.lock
- docker-compose.yml
- Simplify pool sizing
- Update _APP_DB_MAX_CONNECTIONS -> _APP_CONNECTIONS_MAX_CONNECTIONS
Existing tests
N/A
Yes
> Simplify pool sizing

- app/controllers/general.php
- Enable HSTS for all HTTPS requests, not just when `_APP_OPTIONS_FORCE_HTTPS` is also enabled
Manual + existing tests
N/A
Yes
> Enable HSTS for all HTTPS requests

- .env
- app/init.php
- composer.lock
- docker-compose.yml
Improves connection sharing logic in pools using following vars:
- _APP_CONNECTIONS_MAX - Maximum amount of connections to a resource  (in our case MySQL max connections)
- _APP_POOL_CLIENTS - Amount of containers to share max connections between
- _APP_SERVER_MULTIPROCESS - enabled/disabled. Must be enabled if process is using swoole async-style - spawning new process for every worker
No
x
No
Yes
> Fix: db pool sharing

- app/controllers/api/account.php
For some reason the failure status was set to null and it prevented to get the failure URL in the route `/v1/account/sessions/oauth2/:provider/redirect`
yes
> bug fix: failure status shoudn't be nulled

- CHANGES.md
- app/controllers/api/account.php
Previously, Utopia handled `/auth/oauth2/success` and `/v1/auth/oauth2/success` exactly the same (with the same handler). So on mobile, when users were redirected `$oauthDefaultSuccess` (`/v1/auth/oauth2/success`), it was still handled. After we deleted that route and [moved the code to the new console](https://github.com/appwrite/console/commit/2171d7f22d27b3a9ee99693e6b71b4a445a4eda3), the default `/v1/auth/oauth2/success` resulted in a 404. This changes the default path to remove the `/v1/` prefix so that the console can handle the redirect.
Manual
- #4714 
Yes
> Fix the default oauth paths to match the route

- CHANGES.md
- app/controllers/api/teams.php
- tests/e2e/Services/Teams/TeamsBaseClient.php
A member can only accept invitation by getting secret from email. Accepting an invitation marks account emailVerified.
This logic is there, but due to bug it's not saved to database.
x
Yes
Yes
> Fix: unsaved changes in team invitation

- app/workers/functions.php
Fixes syntax error resulting in execution not being triggered on any event.
Before:
After:
x
No, not needed.
Yes
> Fix event-triggered executions syntax error

- app/controllers/api/users.php
- tests/e2e/Services/Users/UsersBase.php
Currently, there's a bug with the way User not found exception is created. This PR fixes it.
You can see on the screenshot that `phpstan` recognizes it right away, however ideally there should be also a test case for this `if` statement. I'm not very familiar with the codebase, If anyone could point me to the appropriate test location, I could do it.
yes
> Fix User not found exception

- app/controllers/api/users.php
- tests/e2e/Services/Realtime/RealtimeCustomClientTest.php
This PR adds a `setPayload` call to the `DELETE /user/:userId/sessions/:sessionId` endpoint which was previously missing causing the error described in #3916.
An e2e test was written for the case to prevent regressions.
#3916 
Yes.
> fix: empty payload returned as list

- src/Appwrite/Docker/Env.php
- tests/resources/docker/.env
- tests/unit/Docker/EnvTest.php
This PR adds the limit argument to explode method to correctly handle `=` in .env files
The code has been manually ran and tested against test case.
Closes #4294 
Yes
> fix: correctly handle `=` in .env

- src/Appwrite/GraphQL/Resolvers.php
This query didnt work:
```
query {
databasesListDocuments(
databaseId: "63ab3cb73e378bd801e1",
collectionId: "63ab3cb92b52aefc4a9b"
) {
total
documents {
_id
}
}
}
```
Not it does
x
No.
Yes
> Fix: nested escaping

- CONTRIBUTING.md
- README.md
This is a test run for grammar edits from an editing agency. This PR updates README.md and CONTRIBUTION.md following most, but not all, suggestions from their edit.
Manual Review
> Updates readme and contributing guide according to suggestions from editing agency

- CONTRIBUTING.md
Since the Appwrite Console is a submodule now, the submodule must be initialized with:
```
git submodule update --init
```
before building Appwrite.
Manual
None
Not applicable
Yes
> Update contributing guide to include submodule update command

- src/Appwrite/Utopia/Response/Model/Func.php
The example provided for function timeout is massive and looks like a timestamp. Changed so it matches default and looks more sensible.
Manual
> Function default timeout example fix

- app/config/variables.php
- app/controllers/api/storage.php
- app/executor.php
- app/init.php
- app/workers/builds.php
- src/Appwrite/Resque/Worker.php
This is done for backwards compatibility. Up to utopia-php/storage version 0.12.X, the devices were not lowercase. Starting 0.13.X, they are all converted to lowercase, but people would still have the old case in their .env file. This change makes the value check insensitive so that the value from older versions still works.
Manual
* https://github.com/appwrite/appwrite/pull/4964
No
Yes
> Convert _APP_STORAGE_DEVICE env var to lowercase

- src/Appwrite/Utopia/Response/Model/Locale.php
> Fix typo in Model/Locale.php

- app/workers/deletes.php
- src/Appwrite/Resque/Worker.php
The delete project endpoint would delete the project from the `_console_projects` table, then the deletes worker tried to delete the entire `appwrite` database when a project was deleted, which would fail, but because the project was deleted from the projects table, the project was no longer accessible.
This meant all the project-specific tables were present in the database with no way to remove them except manually deleting them via SQL.
Project certificates, domains, functions, builds and cache were also not deleted with a project
This PR fixes the deletes worker by:
- Deleting all project domains and certificates
- Getting a project-specific database
- Listing all the project collection tables
- Deleting them all page by page
- Deleting the project metadata tables
- Deleting function, …
> Fix deletes worker not deleting project database tables

- app/workers/deletes.php
The delete collection endpoint would remove a collection from the projects `databases` tables, but collection tables themselves (e.g. `_1_database_1_collection_1`) were not being deleted from the database because the deletes worker was checking if the document `$collection` attribute was `collections` which is no longer true.
This PR changes the worker to check if the `$collection` attribute starts with `database_` instead.
Manual tests
Fixes https://github.com/appwrite/appwrite/issues/4428
Yes
Yes
> Fix deletes worker not deleting database collections

- app/views/install/compose.phtml
- docker-compose.yml
It adds a restart policy in `appwrite-worker-messaging` service in `docker-compose.yml`
This can be tested by restarting the machine where appwrite is deployed and checking the status of `appwrite-worker-messaging` container, the status should be running.
#4986 
No
Yes
> add restart policy for worker-messaging container

- .gitmodules
- CHANGES.md
- bumps `app/console` to 2.2.0
- manual
- https://github.com/appwrite/console/releases/tag/2.2.0
> feat: bump console to 2.2.0

- .github/workflows/tests.yml
Because each GitHub Action is a fresh environment, Docker's build cache isn't used by default. This change updates the build process to cache the docker build layers into GitHub action's cache so they can be reused, speeding up build times.
Actions
None
> Update tests CI to cache docker layers

- CONTRIBUTING.md
- Dockerfile
- dev/yasd_init.php.stub
- docker-compose.yml
* Update the base image since the yasd extension wasn't installed correctly
* Fix the path to the yasd_init.php file
* Use `host.docker.internal` as the remote host because that should always work inside docker
* Mount the dev folder into the appwrite container so the yasd_init.php file is picked up.
Manual
None
> Fix yasd so that the debugger works

- app/controllers/api/databases.php
- tests/e2e/Services/Databases/DatabasesCustomServerTest.php
- adds tests for the collection cache after updating attributes
- fixed purging cache when deleting database
- added
#5238
> tests: add tests for cache on updating attributes

- CONTRIBUTING.md
- app/http.php
Prevent cache from being flushed on start. We shouldn't clear the cache because scheduled functions are also in the cache, and we don't want to lose them.
Manual
None
> Prevent cache from being flushed on start

- app/workers/certificates.php
The path in the worker needs to be corrected so it doesn't error out. 
This fixes the path.
None
Previous PR:
* https://github.com/appwrite/appwrite/pull/4859
> Fix email-base.tpl path in certificates worker

- CHANGES.md
- app/workers/deletes.php
- delete projects when a team on the `console` project is deleted
- manual
> fix: deletes worker deleting projects with console team

- app/workers/functions.php
With this PR, if multiple functions execute with an event, they will all attempt to be executed instead of stopping when one execution fails. Use case explained well in the issue linked below.
I believe this is the correct behavior, as we don't have a function chaining feature in Appwrite.
https://github.com/appwrite/appwrite/issues/3666
Yes 😇
> Fix: event multi-execution

- docs/services/storage.md
Moves a piece of documentation to a more appropriate location.
Moves environment variable docs to the self-hosted configuration docs.
> Move reference to env-var to self-hosted docs.

- app/config/variables.php
**What does this PR do?**
It sets the correct values for the logowl and appsignal logging drivers according to:
https://github.com/utopia-php/logger/blob/main/src/Logger/Logger.php at line 15
**Related PRs and Issues**
https://github.com/utopia-php/logger/pull/8 / https://github.com/appwrite/appwrite/pull/2729
**Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?**
Yes
> set correct value for logging drivers

- app/tasks/install.php
By not specifying a docker-compose.yml file, docker compose automatically uses the docker-compose.yml file in the project directory and a docker-compose.override.yml file if one is present.
Manual:
- https://github.com/appwrite/appwrite/issues/4700
> Update install.php to not specify docker-compose.yml file

- app/controllers/api/storage.php
- tests/e2e/Services/Storage/StorageBase.php
- The hash of the file should always be of the original file, no the one after encryption and compression
> Fix- Original File Hash

- src/Appwrite/Event/Event.php
- src/Appwrite/Event/Func.php
- tests/unit/Event/EventTest.php
- Introduces `$paused` state in Events so that events can be paused. If the event is paused it will not trigger (webhook or Function executions)
> feature to pause events

- app/config/errors.php
- app/controllers/api/projects.php
- phpunit.xml
- src/Appwrite/Extend/Exception.php
- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
Throw the correct exception when creating a project with a requested ID already exists 
> fix: throw correct exception when project ID already exists

- app/config/errors.php
- app/controllers/api/account.php
- tests/e2e/Services/Account/AccountCustomClientTest.php
After a user updates their status, their session no longer works however, the cookie may still exist in their browser, preventing other API calls from completing successfully.
E2E test updated
* https://github.com/appwrite/appwrite/issues/5490
> Update the Update Account Status API to clear the cookie

- app/config/errors.php
- app/controllers/api/account.php
- tests/e2e/Services/Account/AccountCustomClientTest.php
After a user updates their status, their session no longer works however, the cookie may still exist in their browser, preventing other API calls from completing successfully.
E2E test updated
* https://github.com/appwrite/appwrite/pull/5561
> Fix delete account

- app/http.php
- app/workers/functions.php
- src/Appwrite/Event/Validator/Event.php
* Prevent triggering a function off of a function
* Don't clear cache on startup 
* Update console to include new fixes from https://github.com/appwrite/console/pull/458
* Add Check for recursive function execution in the functions worker. 
Tested adding a functions.* event
None
> Fix system performance

- app/controllers/api/account.php
* Fix 500 error when a passwordless user creates an email session
* Don't rely on isAnonymousUser to check whether to verify password
* Update the Update Phone API to also set the password
Closes: #4975
Automated tests should pass
- #4975
- https://github.com/appwrite/appwrite/pull/5584
> Allow Updating email and phone without password

- app/controllers/web/console.php
- tests/e2e/General/HTTPTest.php
Without this, you would get a 404 trying to browse to the default OAuth2 pages.
Added a new e2e test
* https://github.com/appwrite/appwrite/issues/5623
> Fix the routing for the default OAuth2 pages

- app/controllers/api/storage.php
- app/workers/deletes.php
fix delete cache file to dbp-master
> fix delete cache file to dbp-master

- app/controllers/general.php
- app/init.php
Don't default to console project
Defaulting to the console project leads to misleading error messages. For example, you can get a CORS error saying you haven't configured a platform yet, but the actual error is missing project ID.
Passing unit and e2e tests
Depends on:
* https://github.com/appwrite/sdk-generator/pull/681
> Fix default project

- app/workers/deletes.php
- composer.lock
Currently a schedule document was only deleted if it's associated function was deleted.
If its associated project was deleted, it was ignored. This lead to an infinite loop in the deletes worker as the same list of schedules would pop up repeatedly in the list documents call. 
This PR attempts to also delete schedules even if their parent projects are deleted
> fix: delete schedule document if project is deleted as well

- app/controllers/api/projects.php
- src/Appwrite/Utopia/Database/Validator/ProjectId.php
- tests/unit/Utopia/Database/Validator/ProjectIdTest.php
Only allow lowercase alphanumeric chars and hyphens because the project ID is used as part of url
schemes to redirect users back to mobile apps
and certain characters are not allowed.
Closes: https://github.com/appwrite/appwrite/issues/5670
I also confirmed i was able to create a new project while still accessing the project i created with the weird project ID.
* https://github.com/appwrite/appwrite/issues/5670
> Restrict characters for project ID

- app/controllers/api/account.php
Fixed expire format for get session api 
closes: #5429 
> fix: expire format for get session api

- app/config/errors.php
- app/controllers/api/teams.php
- src/Appwrite/Extend/Exception.php
- tests/e2e/Services/Teams/TeamsBase.php
Fixes the linked issue 
- Created a simple web project, tried to create team with same teamId - 
- Wrote test case for this - 
- https://github.com/appwrite/appwrite/issues/5768
> fixed team creation response if teamId already exists

- app/controllers/api/account.php
- src/Appwrite/Auth/Auth.php
An anonymous user is one that has no way to recover their account/session. The only way for someone to not be able to log in again is if they have no email AND phone number.
This PR also updates the OAuth2 flow to only update email and name if they're empty.
Automated tests should pass
None
> Fix anonymous user

- app/controllers/api/account.php
The secret in events & payload should match the secret sent to messaging.
None
> Fix phone verification secret in events & payload

- composer.json
- composer.lock
- tests/e2e/Services/Account/AccountBase.php
Upgrade utopia-php/domain to fix some incorrect validation of domains.
Version 1.1.0 was an incorrectly named git tag that has been deleted; it was equivalent to 0.2.0. 
This bump to 0.3.* is safe because it adds Registrar, but it won't be used in Appwrite yet. Bumping to 0.3.* is necessary to fix some bugs where valid domains were considered invalid.
Fixes https://github.com/appwrite/appwrite/issues/5317
- https://github.com/appwrite/appwrite/issues/5317
- https://github.com/utopia-php/domains/pull/29
- https://github.com/utopia-php/domains/issues/22
- https://github.com/appwrite/appwrite/pull/5566
> Fix np TLD validation

- app/controllers/api/teams.php
- app/workers/deletes.php
Ensure resources are deleted using their internal Id
This is necessary because a resource can be re-created with
the same id. If we don't use the internal id, the newer
recreated resource can be deleted.
Manual
None
> Ensure deletes worker deletes resources using internal id

- app/config/providers.php
- src/Appwrite/Utopia/Response/Model/Project.php
- src/Appwrite/Utopia/Response/Model/Provider.php
- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
Pass the provider key and name back so that a nicely formatted name can be shown in the Appwrite Console.
- https://github.com/appwrite/appwrite/pull/5449
- https://github.com/appwrite/console/pull/420
> Update Project providers to also include the provider key

- docs/references/account/delete-session.md
Related to https://github.com/appwrite/sdk-for-flutter/issues/153
> Update delete session description to be actually correct

- src/Appwrite/DSN/DSN.php
- tests/unit/DSN/DSNTest.php
Previously, DSN would not be able to parse special characters like "@" or "/". This adds support by requiring the input to be url encoded and then DSN would decode it after parsing.
Updated unit tests
- #5913
> Update DSN to support special chars for user and password

- app/config/errors.php
- app/controllers/api/account.php
- src/Appwrite/Auth/OAuth2.php
- src/Appwrite/Auth/OAuth2/Exception.php
- src/Appwrite/Extend/Exception.php
There are two problems when the OAuth2 flow fails.
First, if there is a problem during authentication, the user will be redirected back to Appwrite without the authorization code, and Appwrite will throw an error like this:
The other problem occurs if Appwrite receives an authorization code but fails to exchange it for an access token. In that case, an error like this occurs:
This PR improves both scenarios to show more detailed info or send the data to the failure URL for the developer.
Without a failure URL, the user will see a more detailed error:
With a failure URL, the user will be redirected to it like:
```
https://localhost/auth/oauth2/failure?error=%7B%22message%22%3A%22Failed+to+obtain+access+token.+The+Google+OAuth2+provider+returned+an+error%3A+invalid_grant%3A+Malformed+auth+co …
```
> Improve OAuth2 error handling

- app/controllers/shared/api.php
> Sync with master

- app/config/collections.php
These secrets can be used to store data from the provider that may or may not be sensitive.
For example, this will be used by the migration API when connecting to Firebase to store the service account used for the migration.
This data will only be used internally inside Appwrite and not exposed to an end user or developer.
Data here is tied to the user identity so that it can be removed when the user or the user identity is removed.
None
- https://github.com/appwrite/appwrite/pull/5921
- https://github.com/appwrite/appwrite/pull/5953
> Add a secrets attribute to the identities collection

- app/controllers/api/storage.php
- app/workers/deletes.php
fix delete cache bug to master
> Fix cache delete bug master

- src/Appwrite/Migration/Version/V19.php
The previous approach tried to migrate the 'rules' collection, but that didn't work because the data was in the 'domains' collection.
Since the 'domains' collection was removed, the migration is now done when migrating the 'projects' collection by fetching the domains and then creating the rule documents.
Manual:
None
> Fix domains migration

- CHANGES.md
- app/controllers/general.php
It's possible for the route to be null (no match) which leads to an error like:
```
appwrite  | [Error] Timestamp: 2023-08-30T21:39:58+00:00
appwrite  | [Error] Type: Error
appwrite  | [Error] Message: Call to a member function label() on null
appwrite  | [Error] File: /usr/src/code/app/controllers/general.php
appwrite  | [Error] Line: 50
```
This adds a null check to prevent the error.
Manually made an API call to a custom endpoint and confirmed no more "Call to a member function label() on null" error.
None
> Fix router error

- .github/workflows/cleanup-cache.yml
The GitHub actions cache is helpful to speed up CI jobs. Once a branch is closed, we don't need the cacche anymore so we should delete it so the disk space can be reclaimed.
This workflow was copied from https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries.
https://github.com/appwrite/appwrite/actions/runs/6031274668/job/16364664657?pr=6080
None
> Create a GH workflow to cleanup the GH cache

- src/Appwrite/Migration/Version/V19.php
The `schedule` attribute was not removed from the `functions` collection so we shouldn't delete it.
Running migration after upgrading from 1.3.8:
functions table:
Migrating after running 1.4.0 migration:
functions table:
None
> Update migration script to not remove schedule from functions

- app/controllers/api/storage.php
Because of the `getAttributes()` call, `$fileSecurity` was always true which lead to invalid permission check. This resulted in files being deleted when a user had delete permissions on the file even though they didn't on the bucket.
Closes #6042
- https://github.com/appwrite/appwrite/issues/6042
> Fix fileSecurity check

- app/controllers/api/functions.php
- src/Appwrite/Migration/Version/V19.php
After upgrading to 1.4, functions created before 1.4 should still work. This PR fixes some migration problems that:
1. prevent function variables from showing up
2. prevent executions from running
This also updates the update function API to make runtimes optional for backwards compatibility.
After all of these changes I was able to deploy a pre-1.4 function using version 2.0.2 of the Appwrite CLI:
- https://github.com/appwrite/appwrite/issues/6120
> Fix CLI backwards compatibility

- app/config/variables.php
- src/Appwrite/Platform/Tasks/Install.php
As of 1.4.0, the hostname of the executor should be executor rather than appwrite-executor. The problem is our install command always uses the existing installation's variable values as the default for the upgrade. This means the _APP_EXECUTOR_HOST will retain it's old value.
This PR Adds an overwrite key to variables.php to allow overwriting the variable value regardless of whatever was in the previous installation.
Manually installed 1.3.8, ran the upgrade command, checked .env after:
- #6137
- https://github.com/appwrite/appwrite/pull/6098
> Fix _APP_EXECUTOR_HOST for upgrades

- src/Appwrite/Utopia/Request/Filters/V16.php
- tests/unit/Utopia/Request/Filters/V16Test.php
When an older SDK executes a function without passing any data, the data param is unset/null so we need to make sure to handle that case.
Unit test added.
> Fix create execution request filter from previous SDK version

- app/config/collections.php
- app/controllers/api/functions.php
- app/controllers/api/project.php
- app/controllers/api/vcs.php
- app/init.php
- app/workers/builds.php
- app/workers/functions.php
- src/Appwrite/Auth/OAuth2/Exception.php
- src/Appwrite/Migration/Version/V19.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
- tests/resources/functions/php/index.php
Global variables didn't work due to missing subquery. Now they should.
This includes change to migration, so after release, devs needs to re-run migration
- https://github.com/appwrite/appwrite/issues/6113
> Fix: Global variables

- app/views/install/compose.phtml
Multiple changes caused the volumes to be added twice. This PR removes one.
Built the image locally and ran the install:
`docker compose up -d` works:
No duplicate volumes:
- #6184
> Remove duplicated volumes section

- app/controllers/api/functions.php
- app/workers/functions.php
In V3, we moved dynamic env vars into headers.
For proper backwards compatibility, we need to re-add those dynamic vars back into variables array for V2 functions.
https://github.com/appwrite/appwrite/issues/6209
> Fix: V2 functions env vars

- app/controllers/api/teams.php
- app/controllers/api/users.php
Fixes #6177.
I also manually tested:
new@example.com was created via create team membership. the empty user in the 2nd row was created via create user.
- #6177
> Don't update User Accessed At for Users and Teams APIs

- app/controllers/api/functions.php
- src/Appwrite/Event/Validator/Event.php
- src/Appwrite/Event/Validator/FunctionEvent.php
- src/Appwrite/GraphQL/Types/Mapper.php
- tests/unit/Event/Validator/EventValidatorTest.php
- tests/unit/Event/Validator/FunctionEventValidatorTest.php
Closes #6218 
1. Added `FunctionEventValidatorTest.php` which is the same as `EventValidatorTest.php` except that any event that starts with `functions.` will return false.
2. Tested it on a temporary local Appwrite instance, and I was able to add the `functions.*` events to a webhook but not to a function.
#6218
> Extracting function event validator to its own class.

- app/config/variables.php
Fix the _APP_FUNCTIONS_MAINTENANCE_INTERVAL variable
* Clarify the description and make it match the other maintenance
variables.
* Fix the introduction since it was introduced in 1.4.0 and not 1.2.0.
* Fix the default value because it was 1 hour in the previous versions
and a number that is too low will conflict with a function's timeout.
Fixes #6234 
Manually tested.
- #6234
> Fix function timeout

- src/Appwrite/Platform/Tasks/Schedule.php
If there was any issue fetching schedules for a particular function, the schedules container would crash resulting is schedule failures for all the other functions across projects.
Here we add a try catch block to this code, to safely skip any problematic projects and ensure the container stays operational for other schedules. 
> fix: add try catch block in the schedules task

- app/controllers/api/functions.php
- app/controllers/api/vcs.php
- app/workers/deletes.php
Prior to this, deleting a VCS deployment would fail because the deployment path for VCS deployments are empty. Because an error gets thrown, the delete function would stop and not delete the build files.
This change updates the worker to only delete the storage files if the path is set.
Fixes #6289
Manually deleted a deployment:
Manually deleted a function
- #6289
> Fix deployment delete

- src/Appwrite/Auth/OAuth2/Linkedin.php
Fix related to the issue - #6212 
Reference document - https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2?context=linkedin%2Fconsumer%2Fcontext
LinkedIn has transitioned to using OpenID for authentication and authorization, necessitating updates to the existing codebase to accommodate these changes.
- #6212
> fix-6212-Issue-With-Linkedin-OAuth

- app/workers/functions.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
- tests/resources/functions/php-event/index.php
Allows you to easily get data from event-triggered execution without having to parse it. Thanks to header, Open RUntimes will parse it.
Reported during Office Hours on Discord
> Feat: Parse event body

- app/controllers/web/console.php
Disabled console protection on custom domains. This fixed OAuth flow for mobile apps using custom domains.
Support thread on Discord
> Patch: Disable console protection

- app/views/install/compose.phtml
- docker-compose.yml
Fixes https://github.com/appwrite/appwrite/issues/6217
Manually tested and assistant stays up:
Despite not having the key set:
Command center still hides the OpenAI section if the key is not set:
With the key set:
the assistant container is still up:
but "Ask the AI" is now visible in the Command Center:
and asking a question still works:
- https://github.com/appwrite/appwrite/issues/6217
> Bump appwrite-assistant to prevent it from crashing w/o open ai key

- tests/e2e/Services/Avatars/AvatarsBase.php
Because the tests referenced images on the appwrite.io website, but the appwrite.io website changed, the tests broke. This updates the tests to reference valid images/URLs.
In addition, the favicon test was changed to use github.com because appwrite.io has an SVG favicon which the avatars API does not support.
Automated tests should pass
Fix so that we can merge the following:
- https://github.com/appwrite/appwrite/pull/6164
- https://github.com/appwrite/appwrite/pull/6354
> Fix avatars tests

- src/Executor/Executor.php
In previous patch we added `-build` suffix to deployment containers, to separate them from execution containers. This patch was supposed to prevent executor saying that same runtime already exists (possible race condition).
We forgot to rename logs container name. Realtime logs were watching logs of executor container, which didn't exit.
This PR fixes it, and realtime logs now look at proper build container.
_This patch is only necessary urgent for Cloud, as the previous patch PR was not yet released in 1.4.x._
Before:
After:
- https://github.com/appwrite/appwrite/pull/6270
> Fix: realtime logs

- app/views/install/compose.phtml
- docker-compose.yml
Every other service restarts automatically after a server reboot so the openruntimes-executor should too. Otherwise, function executions will fail as the executor is unavailable.
None
- #6442
> Ensure openruntimes-executor restarts after a server reboot

- app/workers/deletes.php
The realtime collection only exists in the console project so iterating over every project leads to the not found error.
In addition, the deleteForProjectIds() doesn't include the console project so the realtime records were not being cleaned up properly.
Fixes #6895 
Manually checked the docker logs from the appwrite-worker-deletes container to make sure the error no longer occurred. The screenshot below shows the before and after:
- #6895
> Fix realtime deletes

- app/controllers/api/projects.php
This is important because when an organization is deleted, projects are
fetched by the teamInternalId and if the teamInternalId is not updated
when the project team is updated, the project will be deleted if the
previous organization is deleted.
In addition, since the following collections also have permissions set to the team,
this PR updates them for consistency:
- installations
- repositories
- vcsComments
I did look into other collections but they didn't need to be updated:
- schedules
- Always skip so don't have to update permissions
- Team ID isn't in schedule
- platforms
- Permissions are set to any since the data is fetched via subquery filter
- keys
- Permissions are set to any since the data is fetched via subquery filter
- webhooks
- Permissions are set to any since the data is …
> Update teamInternalId when updating project team

- src/Appwrite/Platform/Workers/Functions.php
Fix a bug in which the body was not populated for async function executions.
> Fix missing body in async function execution

- app/worker.php
- `listCollections` resets the authorization state and breaks the deletes worker during runtime when a project is deleted
- covered
> fix: worker database authorization reset

- app/controllers/general.php
- src/Appwrite/Utopia/Request.php
`$this->swoole->cookie` was being referenced when it was null causing these warnings:
This PR checks for empty value before trying to iterate it.
`$requestHeaders` was being referenced before it was set. This PR reverts code back to using `$swooleRequest` to extract the header.
Manual
Previous PR:
* https://github.com/appwrite/appwrite/pull/7024
> Fix 400 error on function domain execution

- app/controllers/api/functions.php
- app/controllers/api/storage.php
Prevents the following warning
Stops setting `Content-Length` for chunked responses
Download a file larger than 20MB from storage (so it uses chunked download) and verify the warning is not shown.
> feat: fix swoole warning

- app/controllers/api/health.php
Before this, the endpoints called $client->sumProcessingJobs() which only gets the currently processing jobs, but this endpoint should return what's currently in queue, pending to be processed. This should be retrieved using $client->getQueueSize().
Steps I took to test:
1. Stop the deletes worker
2. Delete a team
3. Test the endpoint before and after the change
Before change:
After change:
None
> Fix the Health service's get X queue endpoints

- app/config/services.php
- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
Make VCS, proxy and migrations services non-optional so they aren't toggled with enable/disable all service routes
Existing tests + added service/all test
> Fix optional services

- src/Appwrite/Platform/Tasks/patchRecreateRepositoriesDocuments.php
Projects with missing metadata collections stop the script. Would take hundreds of commands typed manually to iterate all projects. Making error silent ensures script loops over all proejcts
QA on stage server will be done
x
> Fix patch script, make errors silent

- app/config/collections.php
- app/controllers/api/account.php
- app/controllers/api/messaging.php
- app/controllers/api/users.php
- app/init.php
- composer.lock
- src/Appwrite/Event/Messaging.php
- src/Appwrite/Platform/Workers/Messaging.php
- src/Appwrite/Utopia/Response/Model/Message.php
- src/Appwrite/Utopia/Response/Model/Provider.php
- tests/e2e/Services/GraphQL/Base.php
- Add `providerType` to message
- Use constants for message types
- Renamed `deliveryTime` to `scheduledAt`
- Make `Message` extends `Model` instead of `Any` so rules are applied since `data` is not hoisted
Existing tests
> Feat add message provider type

- src/Appwrite/Platform/Workers/Messaging.php
The class is SMS rather than Sms.
Attempt to fix
> Class "Utopia\Messaging\Messages\Sms" not found
error when trying to send SMS messages via the Messaging worker.
None
None
> Fix SMS import

- .gitmodules
- src/Appwrite/Platform/Tasks/CalcTierStats.php
* Update console
* Run formatter on CalcTierStats.php
> chore: update console

- app/controllers/api/account.php
Suppose a user has 2 accounts on Appwrite:
1. joe@example.com
2. joe@gmail.com
Prior to this PR, if joe@example.com created a Google OAuth2 session using his joe@gmail.com email, a new joe@gmail.com identity would be created linked to joe@example.com.
This is especially problematic because if the user tried to create a Google OAuth2 session using joe@gmail.com, Appwrite would lookup the user via email and find the joe@gmail.com user, but then find an identity from joe@example.com. This mismatching user ID would then cause an error.
This PR prevents an identity from being created if the email from the OAuth2 provider matches another user's email.
Fixes #7190 
Confirmed an error occurs when trying to link an identity when a user with the same email already exists:
- #7190
> Fix user identity attaching to wrong user

- src/Executor/Executor.php
Allow setting build timeout for app function deployment so that slower building runtimes like Swift can be used with functions.
* Pass build timeout env var to open-runtimes
1. Locally set timeout beyond 10mins (this is the default from [open-runtimes](https://github.com/open-runtimes/executor/blob/main/app/http.php#L383).
_APP_FUNCTIONS_BUILD_TIMEOUT
Note also need to set OPR_PROXY_MAX_TIMEOUT.
2. Deploy a function that takes longer than 10 minutes to build.
* https://github.com/appwrite/appwrite/issues/7318
> executor: pass build timeout to runtimes

- src/Appwrite/Platform/Tasks/Install.php
- src/Appwrite/Platform/Tasks/Upgrade.php
This can be useful for cases where the developer only wants the files to be generated and doesn't want to start Appwrite.
Closes https://github.com/appwrite/appwrite/issues/7223
Manually ran install:
Manually ran upgrade:
- #7223
> Add a flag to install and upgrade commands to not start Appwrite

- app/controllers/api/account.php
- app/controllers/api/users.php
Because no payload was set, the event params (userId and identityId) wasn't picked up automatically. This updates the endpoints so that the payload is set, but also makes sure to set the userId and identityId params since the identityId param's key doesn't match the key in the payload.
Tested by deleting an identity and ensuring no error was thrown in the logs.
None
> Update the delete identity endpoints to set the params and payload

- src/Appwrite/Utopia/Database/Validator/Queries/Targets.php
Allow filtering targets by provider type so that a developer can filter a user's targets by provider type:
Manually filtered on type == push:
Console change:
- https://github.com/appwrite/console/pull/712
> Allow filtering targets by provider type

- app/controllers/api/messaging.php
- docs/references/messaging/list-message-targets.md
- tests/e2e/Services/Messaging/MessagingBase.php
This endpoint is needed so that the Console can fetch the associated targets to display when viewing the details of a message or going in to edit a message.
Manually tested the endpoint:
None
> Add endpoint to list a message's targets

- src/Appwrite/Platform/Workers/Mails.php
Use `$variables` instead of `str_replace`
> Follow existing style of code

- app/config/locale/templates/email-base-styled.tpl
Decouple email images from landing page, and move it to Cloud instead.
x
> Fix: Email image endpoints

- app/controllers/api/users.php
Fix target deletes worker job not triggered when target deleted via API
> Trigger deletes worker when target is deleted

- app/config/errors.php
- app/controllers/api/proxy.php
- app/controllers/general.php
- app/http.php
- app/init.php
- src/Appwrite/Extend/Exception.php
- src/Appwrite/Network/Validator/CNAME.php
- src/Appwrite/Platform/Tasks/SSL.php
- src/Appwrite/Platform/Workers/Certificates.php
Adds logic to log cname validation errors into Sentry including many new details. Also adds parameter to SSL CLI task to configure if validation should be skipped
Error from API:
CLI command:
Logs on worker:
Error from worker:
x
> Feat: CNAME validation logs

- app/controllers/api/account.php
- app/controllers/api/teams.php
- src/Appwrite/Platform/Workers/Deletes.php
Use atomic operations when updating document counts
> fix: use atomic operations for count updates

- app/controllers/general.php
After last change to allow client-side error reporting (only specific ones), now some errors are being reported which is unwanted behavior.
This change ensures previous behavior for unknown error types.
None
x
> Fix: client error reporting

- app/config/errors.php
- app/controllers/api/account.php
- src/Appwrite/Extend/Exception.php
- tests/e2e/Services/Account/AccountConsoleClientTest.php
- Deleting a console user, throw an error if they are a member of active organization
- updated the existing `testAccountDelete` in AccountConsoleClientTest.php
> PEA-233-prevent console user deletion before deleting their team

- src/Appwrite/Specification/Format/OpenAPI3.php
- src/Appwrite/Specification/Format/Swagger2.php
When generating specs, we use `x-example` to populate examples in the generated code examples.
We used to use the format `[PARAM NAME]` because we had a specific PHTML restriction on `<>` type place holders.
Now we can switch to `<>` type tokens, so these placeholders will not be confused with arrays.
> Update place holders from [PARAM_NAME] to <PARAM_NAME>

- app/config/collections.php
- tests/e2e/Services/Messaging/MessagingBase.php
Fix missing unique index on target + topic, allowing users to subscribe multiple times with the same target
Added test
> Fix duplicate subscribers

- app/controllers/api/health.php
- docs/references/health/get-storage.md
- tests/e2e/Services/Health/HealthCustomServerTest.php
This health endpoint for storage will do 3 operations.
```
$device->write(uniquefile);
$device->read(uniquefile);
$device->delete(uniquefile);
```
If one fails, the endpoint fails, this way we test full range of operations. We are testing this for both local as well as remote devices.
Added test and also tested locally.
> Add storage health check

- app/http.php
- composer.json
- composer.lock
Use SWOOLE_PROCESS mode instead of SWOOLE_BASE. 
SWOOLE_BASE became the default in Swoole 5 and is intended for environments where Swoole is running 1 process and 1 thread (horizontally scaling containers).
SWOOLE_PROCESS is intended for scenarios where Swoole is running multiple processes ina single container.
Also seems to fix random crashes encountered in 1.5.x after merging in main.
https://github.com/swoole/swoole-src/discussions/4856#discussioncomment-3796282
https://github.com/swoole/swoole-src/issues/1085
> Use swoole process mode instead of base

- app/controllers/api/functions.php
Fix runtime list route returning all runtimes instead of allowed only
> Only return allowed runtimes in runtime list route

- app/controllers/api/databases.php
- tests/e2e/Services/Databases/DatabasesBase.php
Remove Internal Attributes ( $databaseId and $collectionId ) on Query select from List Documents API.
```
await databases.listDocuments("test", "test", [Query.select(["status"])]);
```
Response
```
{
"total": 6,
"documents": [
{ "status": "active" },
{ "status": "inactive" },
{ "status": "active" },
{ "status": "active" },
{ "status": "active" },
{ "status": "active" }
]
}
```
- #7587
> [Fix]: Remove internal attributes on select query

- app/config/errors.php
- tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
in this case, the error is due to a developer disabling the API on the console, and not a server error.
> Change status code from 503 to 403

- app/controllers/api/account.php
This `secret` param should be encoded as in previous versions to prevent breaking android, flutter & dart OAuth2 session implementation.
In the future we should aim to migrate them to token flow, with extra `createSession` step to prevent session sniffing.
> fix: encode secret in oauth workaround

- src/Appwrite/Migration/Version/V20.php
This throws because Appwrite tries to migrate attributes that don't exist yet like mfaRecoveryCodes. Since the attribute doesn't exist yet, just log a warning and continue.
Manually tested:
...
It might be good to merge https://github.com/appwrite/appwrite/pull/7781 into 1.5.x first and then change the base of this to 1.5.x.
> Fix Attribute not found when migrating users collection

- src/Appwrite/Platform/Workers/Builds.php
The extra trim is neded to because the extra quotes interfere with additional operations in the executor/orchestration library.
> Escape function build command

- app/controllers/general.php
- app/views/general/error.phtml
Execution via domain should be blocked if permissions does not contain any and permissions does not contain guests.
Manually verified I received the error: 
The removal of the escaping was needed because I was getting this:
- None
> Fix function domain permissions

- app/controllers/general.php
- app/views/general/error.phtml
Execution via domain should be blocked if permissions does not contain any and permissions does not contain guests.
Manually verified I received the error: 
The removal of the escaping was needed because I was getting this:
- None
> Fix functions domain permissions 1.5.x

- src/Appwrite/Platform/Workers/Functions.php
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
For a scenario where an execution is triggered through worker and deployment doesn't exist, we would create a failed execution to let user know about the failure.
> Create failed execution from worker if deployment doesn't exist

- src/Appwrite/Platform/Workers/Messaging.php
Due to a bug in the Swoole TCP hook, the worker crashes when doing the TLS handshake. This PR disables the Swoole TCP hook just like we do in the mails worker.
Fixes: https://github.com/appwrite/appwrite/issues/7914
Manually created an email and the logs show it was processed successfully:
```
appwrite-worker-messaging  | [Worker] Worker 0 is ready!
appwrite-worker-messaging  | Worker messaging  started
appwrite-worker-messaging  | [Job] Received Job (660dbf5c37b395.78058781).
appwrite-worker-messaging  | [Job] (660dbf5c37b395.78058781) successfully run.
appwrite-worker-messaging  | [Job] Received Job (660dc049d8a217.47574305).
appwrite-worker-messaging  | [Job] (660dc049d8a217.47574305) successfully run.
```
The Console also shows success for the email:
Note: the SMS failed, but that's …
> Fix worker crash when using custom SMTP provider

- app/controllers/shared/api/auth.php
- src/Appwrite/Utopia/Response/Model/Session.php
Fixes bug in mfa protected endpoints (2)
Error:
Showcase of error from CLI (second), and fixed solution (first)
x
> Fix: MFA protected group

- app/controllers/api/account.php
When recovery code gets used, its removed fro marray but indexes arent fixed.
Because of that, Appwrite then returns those as object instead of array:
I know this is issue with index 0 missing, as per test here:
Code in this PR ensires array is recreated and has proper indexing - will remain proper array everywhere. Performance isn't concern as it has only a few codes always.
None
x
> Fix: recovery code removal

- app/controllers/api/account.php
- src/Appwrite/Utopia/Response/Model/MFAFactors.php
Adds recovery code as option in listMfaFactors. This makes implementation easier as you don't need special case for recovery code.
Account with TOTP enabled:
Brand new account:
x
> Add recovery code to List factors

- src/Appwrite/Migration/Version/V20.php
This change updates the V20 (1.5.x) migration script to create the `apis` attribute in the `projects` collection since it was added to the collections config.
Manually confirmed the column was there after running the migrate command
Before:
After:
- https://github.com/appwrite/appwrite/pull/7725
> Add missing 'apis' attribute to projects collection

- app/views/install/compose.phtml
I found a similar issue and PR like this for such an error but on `webhooks` worker container...
`webhooks` container issue: #7844
PR for that issue: #7848
The same error is happening on `mails` worker 
Fixes: #8001
After installing the version from my PR, I can observe in `docker-compose.yml` in `appwrite` directory that service named `appwrite-worker-mails` now contains
```
- _APP_DB_HOST
- _APP_DB_PORT
- _APP_DB_SCHEMA
- _APP_DB_USER
- _APP_DB_PASS
```
Also after sending the invite, I got no errors while watching logs of `appwrite-worker-mails` container
* #8001
> Added DB environment variables to appwrite-worker-mails

- app/controllers/shared/api.php
This PR introduces an additional check before we access `factors` on the $session object to make sure it exists since invalid or outdated cookies will cause the session check to pass for factors to be null resulting in a 500 error on all requests including non-protected routes.
> Fix server errors from invalid or outdated cookies

- .github/workflows/stale.yml
This GitHub Actions workflow automatically marks and closes stale issues in the Appwrite/Appwrite repo. It helps maintain a clean and up-to-date issue tracker by identifying issues that have been inactive for a specified period of time.
1. The workflow identifies issues labeled as "pending-requestor-info", indicating that they require additional information from the requestor.
2. If an issue labeled as "pending-requestor-info" has been inactive for 7 days, it will be marked as stale and labeled with "stale".
3. A comment will be posted on the stale issue, informing the requestor that the issue will be closed if no further activity occurs within the next 14 days.
4. If the stale issue receives any activity (e.g., comments or updates), the "stale" label will be automatically removed.
5. If …
> Stale Issues Workflow Creation

- app/views/install/compose.phtml
- docker-compose.yml
- tests/resources/docker/docker-compose.yml
There are times when we need to upgrade MariaDB. Setting this env variable will have it automatically upgrade so the user doesn't need to do anything.
Fixes https://github.com/appwrite/appwrite/issues/7945
Manual
- https://github.com/appwrite/appwrite/issues/7945
> Enable auto upgrade for mariadb container

- .github/workflows/stale.yml
Due to failures, changing to not_planned
Fixes error as called in failed workflow 
```
Error: Unrecognized close-issue-reason "not-planned", valid values are: completed, not_planned
Error: Error: Unrecognized close-issue-reason "not-planned", valid values are: completed, not_planned
Error: Unrecognized close-issue-reason "not-planned", valid values are: completed, not_planned
```
> Fix stale action close reason

- app/config/errors.php
- app/init.php
- src/Appwrite/Platform/Tasks/CalcTierStats.php
- src/Appwrite/Platform/Tasks/CreateInfMetric.php
- src/Appwrite/Platform/Tasks/PatchRecreateRepositoriesDocuments.php
> chore: fix some typos in comments

- app/controllers/api/functions.php
Uses `resourceInternalId` to query deployments instead of `resourceId`.
Fixes https://github.com/appwrite/appwrite/issues/7999
Manual.
Note: Stopped the `appwrite-worker-deletes` first.
Before -
https://github.com/appwrite/appwrite/assets/20625965/087d0666-7f18-464e-8815-23ffe53a7120
After -
https://github.com/appwrite/appwrite/assets/20625965/e2dfde30-fc2d-4dcf-a874-f2781e90e621
- #7999
> Fix: Use `resourceInternalId` for Querying Function Deployments

- src/Appwrite/Extend/Exception.php
PDOExeptions error code are string , for example:
SQLSTATE[HY000]: General error: 2006 MySQL server has gone away.
error code is = HY000
> Handle string error codes

- README-CN.md
- README.md
Restores removed domain paths for Getting Started links in README.md.
Fixes: #8040 
No code changes.
* #8040
> Replace missing domain paths in README.md

- app/controllers/api/proxy.php
- tests/e2e/Services/Projects/ProjectsCustomServerTest.php
Prevent functions domain to be used as custom domain
Manually tested
- https://github.com/appwrite/appwrite/pull/7933
> Prevent functions domain to be used as custom domain

- app/controllers/api/account.php
- tests/e2e/Services/Account/AccountBase.php
Marks account emailVerified after email OTP sign-in. Similarly, to how it already does for email Magic URLs.
x
> Fix: Email OTP verified account

- app/controllers/general.php
The APP_VERSION_STABLE constant should be used for the version in API errors so that developers see a version that makes more sense (such as 1.5.5).
Fixes: #8039
Before:
After:
- #8039
> Fix version in error response

- app/config/locale/templates/email-mfa-challenge.tpl
The font family was set to Inter without any fallback and since the Inter isn't available in emails, the font rendered the default font, Times New Roman. This commit adds a fallback font to the font-family ensuring an sans-serif font like Inter is used.
Tested by triggering the email into Maildev and then forwarding it to Gmail:
Before:
After:
None
> Fix MFA email verification code font

- app/controllers/api/account.php
- app/init.php
* remove auth duration from `Auth::sessionVerify()` calls because the method doesn't require it
* ensure user isn't kicked out after enabling MFA as it is very disruptive to the user experience
* ensure session factors don't contain duplicates
Manual
None
> Don't kick user and require verification after enabling MFA

- app/realtime.php
Disable sending realtime stats because the `$database->find('realtime')` is throwing:
> Cannot execute queries while other unbuffered queries are active.
In addition, the realtime stats are not being collected so there's no point in having this enabled.
Manually confirmed realtime still works:
- None
> Disable sending realtime stats

- composer.lock
- src/Appwrite/Platform/Workers/Deletes.php
- Fix shared tables project deletes not deleting data
- Update database to https://github.com/utopia-php/database/releases/tag/0.49.8
Manual tests, can't be tested automatically as projects are deleted successfully leaving no way to access the data
> Fix project deletes for shared tables

- app/realtime.php
SQL can throw an error where the code is a string like 'HY000':
```
appwrite-realtime | [Error] Type: PDOException
appwrite-realtime | [Error] Message: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
appwrite-realtime | [Error] File: @swoole/library/core/Database/PDOStatementProxy.php
appwrite-realtime | [Error] Line: 44
appwrite-realtime | 
appwrite-realtime | Fatal error: Uncaught TypeError: Utopia\WebSocket\Server::close(): Argument #2 ($code) must be of type int, string given, called in …
```
> Handle SQL error code 'HY000' in realtime

- app/controllers/api/project.php
Because limit was not passed for the find() query, the limit defaulted to 25. As such, when requesting stats for the last 30 days, only the last 25 were retrieved.
Fixes https://github.com/appwrite/appwrite/issues/8110
Manual
- #8110
> Set limit to retrieve all stats for the usage range

- app/controllers/api/account.php
- src/Appwrite/Auth/OAuth2/Apple.php
Fixes #7268
Manually tested Apple OAuth2 and got my name to appear:
- #7268
> Fix email used for name when user is created via Apple OAuth2

- src/Appwrite/Platform/Workers/Messaging.php
The class name in utopia-php/mssaging is TextMagic so use the same here to prevent an error like:
> Class "Utopia\Messaging\Adapter\SMS\Textmagic" not found ...
Manual
-
> Fix TextMagic class name

- app/config/locale/languages.php
TLTR: for Chinese language, say **中國人** which means "Chinese Citizen" when the language should be **中文**
This PR updates the native names for the Chinese language in the languages.php file. The changes ensure that the language names are correctly represented in their native script, improving localization and user experience for Chinese-speaking users.
- None
> Update Chinese language native names in languages.php

- app/config/errors.php
> Fix don't publish max users exceed

- app/views/install/compose.phtml
- app/worker.php
- docker-compose.yml
- src/Appwrite/Platform/Workers/Messaging.php
- Refactor the `localStorageDevice` of **Messaging Worker** to its own class.
- Mounting the `uploads` volume for local use-cases.
- Adding the storage variables.
Tested against a local `1.5.5` environment with and without attachment, using the following request.
```http
POST http://localhost/v1/messaging/messages/email
x-sdk-name: Console
...
{
"messageId": "6a131313d6a2",
"subject": "subject",
"content": "content",
"topics": [],
"users": [],
"targets": [
"664cf54317f85b349215"
],
"attachments" : ["664b6260dbc042b1f13c:664cf2c2001a03a9a1c8"],
"html": false
}
```
> Refactor localdevice injection

- app/controllers/shared/api.php
The document ID should not have special characters like "*" or it will
cause problems with things like cursor based pagination which is done
in migrations.
We did have the cache buster inside the md5 call before, but when the
usage code was reverted and whatnot, the change wasn't added back
properly.
Also fixed the key used for loading from cache because it was different
than the key used for saving.
Related: https://github.com/appwrite/appwrite/issues/7887
Tests should pass
- https://github.com/appwrite/appwrite/issues/7887
> Fix invalid cache document id

- app/controllers/general.php
This PR allows using custom `robots.txt` on function domains.
Manual -
Robots.txt
Humans.txt
N/A
> Fix: Don't Override `robots.txt` for Other Domains

- app/config/variables.php
- composer.json
- composer.lock
- src/Appwrite/Platform/Workers/Messaging.php
Allows `_APP_SMS_FROM` to be set to a Messaging Service Sid when using Twilio as SMS provider. See https://www.twilio.com/docs/messaging/services
> feat: support twilio messaging service sid

- app/controllers/api/account.php
Before this, users who only signed in with OAuth2 were not able to verify their sessions with MFA because their session already used an email factor and they couldn't use an additional email factor.
This commit changes the OAuth2 session to include 2 factors: email and oauth2. This second special factor is used to bypass MFA checks. It is fine to bypass MFA checks because OAuth2 is supposed to handle the entire authentication process, verifying who the user is and we, as the resource provider, only need to trust the OAuth2 provider.
Fixes https://github.com/appwrite/appwrite/issues/8211
Enabled MFA and confirmed I was able to log in via GitHub only.
https://github.com/appwrite/appwrite/assets/1477010/ef01358f-ab5f-4ee1-9ed1-22f691bf90dd
- https://github.com/appwrite/appwrite/issues/8211
> Fix MFA for OAuth2 only accounts

- src/Appwrite/Platform/Tasks/Maintenance.php
Deletes the expired messaging targets per project.
Fixes https://github.com/appwrite/appwrite/issues/8159
N/A.
- #8159
> Delete Expired Targets Per Project

- tests/e2e/Services/Functions/FunctionsCustomClientTest.php
> Add Test to Validate Headers aren't Overridden

- app/controllers/api/account.php
- app/controllers/api/users.php
- tests/e2e/Services/Account/AccountCustomClientTest.php
If you create a user, set the target then delete the user and the target from console and then create a user again, you get a type error in the User Model
This happens cause it tries to populate the target field but the response was false
Adds a check if the document exists then set the target
WIP
https://discord.com/channels/564160730845151244/1062789941727338577/1247967828015972362
> Fix: Don't set the target field if the existing target document is false

- src/Appwrite/Platform/Tasks/Migrate.php
Skip the validation so that queries that typically fail can pass. This is fine because the validation is failing on internal attributes such as an $id for cache key with * and $id for attributes that are too long because we prefix the $id with the internal database and collection id.
Before:
After:
- https://github.com/appwrite/appwrite/issues/6196
- https://github.com/appwrite/appwrite/issues/7887
> Disable validation for project DBs during migration

- tests/e2e/Services/Health/HealthCustomServerTest.php
There seems to be a load balancer in front of www.google.com that has either a certificate issuer of "Google Trust Services LLC" or "Google Trust Services". This causes the test to fail intermittently.
This PR updates the test to check for the substring "Google Trust Services" instead of the exact string "Google Trust Services LLC".
CI should pass
None
> Fix flaky certificate test

- app/controllers/api/users.php
- tests/e2e/Services/Users/UsersBase.php
Before this, the Create session API call would throw:
> Invalid document structure: Missing required attribute "expire"
This is because the `expire` attribute is required, but it was omitted
from the document. This PR ensures the `expire` attribute is set when
creating the session document.
Fixes #8280 
The create session endpoint created a 6 character secret which is too
short. This changes the secret to be 256 characters which is in line
with the secret for `account.createEmailPasswordSession()`.
Added a test case
- #8280 
Parent PR:
* https://github.com/appwrite/appwrite/pull/8317
> Fix 'Missing required attribute "expire"' on `users.createSession()`

- src/Appwrite/Platform/Workers/Builds.php
Set `path` for vsc-deployed functions
Was done manually
> fix: Setting `path` for vsc function deployments

- app/controllers/api/users.php
- app/init.php
- tests/e2e/Services/Users/UsersBase.php
Marks sessionId in users.createJwt optional. This makes impersonation on local development much easier to start.
x
> Fix: users JWT methods

- app/controllers/api/functions.php
- src/Appwrite/Platform/Workers/Builds.php
Fixes following flows:
1. Create deployment A -> redeploy (B) -> delete A -> redeploy B (fails, no file found in build logs)
2. Create deployment A -> redeploy (B) -> delete A -> redeploy B -> delete B (server error, cannot delete file)
3. Push to git (deployment A) -> download A (fails, deployment not found)
x
> Fix: function redeployments

- app/controllers/api/teams.php
- app/realtime.php
1. add userId to queueForEvents so that the [permissionsChanged](https://github.com/appwrite/appwrite/blob/483ef3c00bcbda150102070e3a15c01692b21626/app/realtime.php#L371-L389) handler is triggered
2. unsubscribe before resubscribing on permission change to ensure old subscriptions are removed
Manually tested by:
1. granting a team access to a collection
2. adding a user to the team
3. subscribing
4. updating the document to verify the user receives the event
5. removing the user from the team
6. updating hte document again to verify the user doesn't receive the event
- None
> Fix realtime permission change

- app/controllers/api/proxy.php
If the value of `_APP_DOMAIN_FUNCTIONS` is empty, the proxy check via `str_ends_with` always returns `true`. This PR fixes it.
Manual.
N/A.
> Fix Domain Check

- app/views/install/compose.phtml
- docker-compose.yml
One thing this update fixes are warnings like:
```
Warning: Undefined array key "listening" in /usr/local/app/http.php on line 1023
Warning: fsockopen(): Unable to connect to 66aeafc1c683e:3000 (Connection refused) in /usr/local/src/Executor/Validator/TCP.php on line 45
```
See [0.5.6](https://github.com/open-runtimes/executor/releases/tag/0.5.6) and [0.5.7](https://github.com/open-runtimes/executor/releases/tag/0.5.7) for changes.
CI should pass
None
> Bump executor version from 0.5.5 to 0.5.7

- src/Appwrite/Platform/Tasks/Migrate.php
The iterator was in the loop so it was always reset to null and the same data set to be scanned.
For cases where this happened, the iterator was not empty, but the keys returned from the scan was empty. According to [redis](https://redis.io/docs/latest/commands/scan/#number-of-elements-returned-at-every-scan-call), this is expected behavior.
> SCAN family functions do not guarantee that the number of elements returned per call are in a given range. The commands are also allowed to return zero elements, and the client should not consider the iteration complete as long as the returned cursor is not zero.
As such, we must make sure we're using the new iterator returned to continue scanning the keys.
Fixes https://github.com/appwrite/appwrite/issues/8518
Manually tested:
- …
> Fix migration stuck at "Starting Data Migration [...]"

- app/controllers/api/functions.php
Adds templates endpoint to API group, giving proper CORS response headers
Before:
After:
x
> Fix: Templates CORS

- app/config/function-templates.php
Reorder template runtimes to maintain existing order on console (see: https://github.com/appwrite/console/pull/1266#pullrequestreview-2235610745)
> fix: reorder runtimes

- app/views/install/compose.phtml
- tests/e2e/Services/Functions/FunctionsCustomServerTest.php
Fixes problem in released RC when async/scheduled/event functions don't have endpoint env var set
After:
x
> Fix missing function variables

- app/controllers/api/account.php
Ensure that when a phone session is created, we do not call the sendSessionAlert() function
Manual Testing. Verified that when creating a session the second time with a phone number, the exception is not thrown
https://github.com/user-attachments/assets/d1d29fc5-4b0e-4dd3-b843-19f9c3866214
> chore: fix session alerts

- app/controllers/web/console.php
- tests/e2e/General/HTTPTest.php
Use `$request->getParams()` because `$request->getURI()` does not include the query string.
Added test case
- https://github.com/appwrite/console/pull/1332
> Update console redirect to include query params

- src/Appwrite/Platform/Tasks/ScheduleBase.php
- src/Appwrite/Platform/Tasks/ScheduleExecutions.php
- src/Appwrite/Platform/Tasks/ScheduleMessages.php
Uses schedule doc internal ID as in-memory key of scheduler. This prevent issues with same resource ID across different projects.
No new tests; existing tests must pass
Project `66dc8ecf00208a16edb8`, function `66dc8ebb001477bdfcf0`:
Project `66dc8eb30013a1a2f5e8`, function `66dc8ebb001477bdfcf0`:
^ Notice both have executions every minute, so scheduler works as expected for this scehario.
- https://github.com/appwrite/appwrite/issues/8583
> Fix: cross-project scheduler stability

- src/Appwrite/Platform/Workers/Builds.php
Ensures size doesn't say 0 for deployments made with VCS.
x
> Fix: vcs deployment size

- app/views/install/compose.phtml
Currently, docker doesn't restart the usage-dump container after a system reboot, causing appwrite to not show usage correctly. This fix makes it restart along with the other containers.
> Fix: Update docker-compose to restart usage-dump

- app/views/install/compose.phtml
The resources are injected in the deletes worker so the env vars need to be passed to the container.
Manually worked with a user to update their docker-compose.yml file
* https://github.com/appwrite/appwrite/pull/8662
> fix: add retention env vars to deletes worker

- app/views/install/compose.phtml
The resources are injected in the deletes worker so the env vars need to be passed to the container.
Manually worked with a user to update their docker-compose.yml file
None
> Add retention env vars to deletes worker

- src/Appwrite/Platform/Workers/Messaging.php
Because `$deliveryErrors` is an array, adding an int to it here:
https://github.com/appwrite/appwrite/blob/154993dafd175032121857b71c5e7bfce2de293a/src/Appwrite/Platform/Workers/Messaging.php#L293
results in a fatal error:
We need to get a count before using it in metrics.
In addition, this PR ensure the Messaging provider is set in the metric rather than having:
```
+-----+----------------------------------+-------------------------+-------------------------+--------------+-----------------------------+---------+--------+-------------------------+--------+
| _id | _uid                             | _createdAt              | _updatedAt              | _permissions | metric                      | region  | value  | time                    | period | …
```
> Fix messaging metrics

- app/config/variables.php
Because the variable is required and there is no default, the user is prompted to supply a value, but because there is no question set, all they see is:
Manually tested:
None
> Fix missing question for _APP_EMAIL_CERTIFICATES during install

- app/config/function-templates.php
- Some templates were missing `scopes` value, causing an error on console.
- Switch some cases of `"` to `'`
> fix: add missing template scopes

- .github/workflows/tests.yml
- tests/e2e/Services/Functions/FunctionsBase.php
- tests/e2e/Services/Functions/FunctionsCustomClientTest.php
- tests/e2e/Services/FunctionsScheduler/FunctionsCustomClientTest.php
Since scheduled functions take too long, this PR splits functions tests into two services - `Functions` and `FunctionsScheduler` so that they can run parallely.
This reduces total time to run function tests from 21.5m to 11.5m
> Create FunctionScheduler test service

- app/views/install/compose.phtml
The worker uses the env vars
https://github.com/appwrite/appwrite/blob/fdd39a29c3667069d97af3fc40bd5098bd32c41c/src/Appwrite/Platform/Workers/Mails.php#L68-L69
So we need to include it in the compose file to ensure the variable passes into the container.
None
None
> Add domain and force HTTPS env vars to mail worker

- src/Appwrite/Platform/Workers/Deletes.php
When deleting a project with many2many relations attributes with junctions tables inside _metadata collection.
While iterating _metadata collections which includes junction tables. Trying to delete them will trigger an Exception  Collection not found which will terminate the script leaving orphan collections not deleted and orphan collections inside _metadata.
This happens because if the collection or related collection holding the many2many attribute is deleted, the junction table is also deleted on the fly.
> Ignore junction tables

- app/controllers/api/storage.php
- Now that safari supports webp but without the appropriate header, remove the fallback
- Manual test in safari
> Remove JPEG fallback for webp

- app/config/collections.php
- app/controllers/general.php
- src/Appwrite/Messaging/Adapter/Realtime.php
- src/Appwrite/Utopia/Response/Model/Project.php
- tests/e2e/General/PingTest.php
- tests/e2e/Services/Realtime/RealtimeConsoleClientTest.php
Onboarding kits need to send a ping. 
- Ping endpoint, which needs a project id header
- Two new attributes: `pingedAt` and `pingCount` to the `projects` collection
- Realtime event `projects.[projectId].ping` for console to listen for
> feat: ping endpoint

- .github/workflows/tests.yml
- composer.lock
- phpunit.xml
- src/Appwrite/Platform/Workers/Migrations.php
- tests/e2e/Scopes/ProjectCustom.php
- tests/e2e/Services/Migrations/MigrationsBase.php
- tests/e2e/Services/Migrations/MigrationsConsoleClientTest.php
This PR fixes a bug where the source credentials would be overwritten with Appwrite's own. It also introduces tests for E2E Appwrite migrations
Tests have now been added for E2E Appwrite migrations.
> Fix Migrations having source creds being overwritten and add Migration tests

- Dockerfile
XDebug's Zend API version changed with 8.3 so the xdebug.so file was not being correctly removed. This PR fixes the Zend API folder version.
> Fix XDebug Extension not being removed

- src/Appwrite/Platform/Workers/Migrations.php
This PR removes the getDocument call for the migration document in an attempt to fix the $id is null issue.
Existing tests should suffice
> Remove double fetch from migrations worker

- app/controllers/general.php
Reverts appwrite/appwrite#8962
As a side effect of this PR, functions executed through a custom domain get redirected to `/console`
> Revert "feat fix web routes"

- app/http.php
Adds safe-worker logic to API servers, separating functions and API request handling to ensure zombie worker cannot occur.
_Zombie worker used to be when a worker was handling a synchronous function execution, but from inside function API request was sent and picked up by same worker. This created deadlock only released by function timeout._
Existing tests must pass
x
> Feat: Safe workers

- app/controllers/api/users.php
- tests/e2e/Services/Users/UsersBase.php
1. Include at least 1 factor because the minumum number of factors
required when mfa is disabled is 1.
2. Purge the cached user document to ensure the new session is included
in subsequent requests for the user.
3. Fix the encoding of the secret to match other parts of the codebase.
Fixes #8569 
Updated test case
- #8569
> Fix users create session secret

- app/http.php
Leftover bug after syncing with latest chagnes:
Before:
AFter:
https://github.com/appwrite/appwrite/pull/9016
> Fix: swoole task warning

- app/realtime.php
The counter is incremented after it's added to `$realtime->connections`. Only decrement the counter if the connection is known.
> fix(realtime): decrement connectionCounter only if connection is known

- app/controllers/api/databases.php
- docs/references/databases/create-document.md
…own attribute.
- Create document description doesn't warn users to create an attribute first
- Improve the error message with some suggested next steps.
- https://github.com/appwrite/website/issues/677
> Docs: Create document and unknown attribute error messages.

- app/config/runtimes/specifications.php
This PR rolls back a temporary change that set the base specification's CPU to 1 instead of 0.5
> Set base specification CPUs to 0.5 again

- app/controllers/general.php
- app/http.php
- app/init.php
- app/worker.php
- composer.json
- composer.lock
When a PDO or database exception is thrown, and the exception was due to a lost connection, mark a pool connection as unhealthy, so that on next reclaim it will be re-created.
Introduces a `connectionForProject` resource that intercepts the project DB so that the connection can be used directly when needed for marking as unhealthy.
Manual tests + library tests
> Fix dead connections

- app/controllers/api/account.php
- app/controllers/api/teams.php
- src/Appwrite/Event/Messaging.php
- src/Appwrite/Platform/Workers/Messaging.php
- Shifts usage tracking for MESSAGE_SEND_TYPE_INTERNAL from message worker to api calls: phone, mfa, team and verification.
- uses `authPhone` in plan object to set abuse checks if within free limit dont report usage for message
- a small comment fix
> chore: shifted authphone usage tracking to api calls

- .github/workflows/tests.yml
- tests/e2e/Services/Messaging/MessagingConsoleClientTest.php
Adds a generic `sleep` to allow a write to Audits DB. This fixes an internal failing test issue with the new Audits approach.
Manual.
With `sleep` -
Without `sleep` -
N/A.
> Add assertEventually to messaging provider logs test

- app/controllers/api/users.php
- tests/e2e/Services/Users/UsersBase.php
The session document created by users.createSession() was missing delete permissions for the user so when the user tried to delete it, they got a 401 error.
This PR ensure the permissions are added just like if the document was created from the Account API so that the user has access to delete the document.
Fixes #9052 
Updated test to check delete session case 
- #9052
> Ensure user can delete session

- app/config/function-templates.php
Fixes a missing scope on a Perplexity AI Chat template causing a crash on Console.
N/A.
* https://github.com/appwrite/console/pull/1609
> Add missing scope on function template

- src/Appwrite/Platform/Workers/Certificates.php
When renew wasn't required in Certificate.php, it would throw a 500 error that was not required. Instead we just want the job to be skipped.
> chore: skipped job instead of throwing error

- app/controllers/api/account.php
- src/Appwrite/Auth/Validator/Phone.php
- tests/unit/Auth/Validator/PhoneTest.php
When a invalid phone number is passed, the `libphonenumber\PhoneNumberUtil` library would throw a error which since wasn't handled properly would throw a 500 error.
This PR adds proper handling for this error, throwing a 400 error instead.
> fix: phone number parsing exception handling

- app/controllers/api/teams.php
- tests/e2e/Services/Teams/TeamsBaseClient.php
When creating a team invite page using the redirect url passed, a user might want the created team's name as well.Currently, they are only provided the teamId, but they can't fetch as the new user isn't logged in yet. 
This PR adds `teamName` to the redirect url as well.
> chore: added teamName to membership redirect url

- app/config/storage/inputs.php
Adds `image/webp` to supported storage inputs.
Fixes https://github.com/appwrite/appwrite/issues/9317
- #9317
> Fix WEBP File Preview Rendering Issue

- src/Appwrite/Platform/Workers/Builds.php
Before building a function, check if it's blocked. This ensures we don't keep building blocked functions due to e.g. webhooks.
> feat(builds): check if function is blocked before building

- src/Appwrite/Platform/Workers/StatsResources.php
- The metric's time period was not written to DB, so `time` was always null, this PR fixes it
> Fix: metric time was not being written to DB

- app/controllers/general.php
On sending a request to the `/v1/ping` endpoint without a projectId, by default console project is returned. This project does not contant the key store as its a special project, leading to 500 errors. This PR adds a check to the endpoint to prevent this.
Before:
After:
> Fix Model Platform is missing response key: store 

- app/config/errors.php
- app/controllers/api/teams.php
- src/Appwrite/Extend/Exception.php
- tests/e2e/Services/Teams/TeamsBaseClient.php
- tests/e2e/Services/Teams/TeamsBaseServer.php
Prevents resending of team invite if already accepted. It also fixes generation of a new `$secret` when resending the invite.
1. Invite a team member to your organisation.
2. Accept the invite.
3. Send the invite again.
Expected:
- It should not send an invite again since the user already accepted it.
What's happening:
- Its sending the invite again. This is likely due to the recent fix that allows resending of invite but we should only do that when invitation is pending, if it's not then we should throw an error.
> Fix resend team invite if already accepted

- app/controllers/api/teams.php
An invitee's name may be `null` on rare cases, leading to errors. The PR fixes this by replacing the value with `$name` which can either be the optional name param set by user or the invitee's email, or if the invitee's account exist then the account's name (that too if not empty).
Priority if all 3 exist:
```
Invitee's account name > Optional Name set by inviter > Invitee's email
```
> chore: fix null errors on team invite

- docs/sdks/cli/GETTING_STARTED.md
- It replaces the `deploy` command with a `push`
- It fixes the outdated create document command to resolve errors users might encounter.
Fixes https://github.com/appwrite/sdk-for-cli/issues/146 
Fixes https://github.com/appwrite/sdk-for-cli/issues/152
- appwrite/sdk-for-cli#152
- https://github.com/appwrite/sdk-for-cli/issues/146
> Fix outdated CLI commands in documentation

- src/Appwrite/Platform/Tasks/StatsResources.php
- Stats resources: Queue projects only if accessed in last 3 hours instead of last 24 hours as the loop runs every hour
> Fix: stats resources only queue projects accessed in last 3 hours

- composer.json
- composer.lock
According to issue mentioned below, sending emails to multiple recipients can lead to data privacy issues.
This PR makes the messaging worker send a separate mail for each recipient if the provider is **SMTP** as for sendgrid and mailgun there are api endpoints for _batch-sending_
> Note: If users want to send a single email, they can use `cc`, and don't want to expose emails to all recipients, they can use `bcc`
* #8261
> Fix: email (smtp) to multiple recipients

- tests/e2e/General/UsageTest.php
- tests/e2e/Services/Migrations/MigrationsBase.php
- tests/e2e/Services/Realtime/RealtimeCustomClientTest.php
- tests/e2e/Services/Webhooks/WebhooksBase.php
If a resource is not set properly, let's say `queueForWebhooks` these tests would keep running forever. This PR adds timeout to them.
Testing by commenting out queueForWebhooks init:
> chore: added timeout to deployment builds in tests

- src/Appwrite/Utopia/Response/Model/UsageProject.php
Makes `imageTransformations` an array instead of integer
> fix: model for image transformations in usage project

- app/cli.php
- app/config/console.php
- app/init.php
- src/Appwrite/Platform/Tasks/Maintenance.php
Till now console project was not scheduled for deletes, specifically for DELETE_TYPE_MAINTENANCE as the loop would just list projects inside dbForPlatform, that won't contain console project.
This PR initializes console project for `CLI` and queues it for delete as well.
> chore: queue console project for maintenance delete

- src/Appwrite/Platform/Workers/Deletes.php
Updates initialization of logDb in delete user stats worker and prevent console project to queue for stats delete.
> chore: update initializing dbForLogs

- app/views/install/compose.phtml
The deletes worker uses the certificates resource to delete certificates, but the certificates resource requires the _APP_EMAIL_CERTIFICATES env var to be set or it will throw an exception and not process any delete jobs. This commit adds the missing env var to the deletes worker.
Fixes: https://github.com/appwrite/appwrite/issues/9488
Before:
After:
- https://github.com/appwrite/appwrite/issues/9377
- https://github.com/appwrite/appwrite/issues/9488
> Fix certificates in deletes worker

- src/Appwrite/Platform/Modules/Sites/Http/Frameworks/XList.php
- tests/e2e/Services/Sites/SitesCustomClientTest.php
- tests/e2e/Services/Sites/SitesCustomServerTest.php
Used to be with key, causing JSON response to be object, not array as intended.
New test added
x
> Fix: Response model for framework (adapters)

- app/controllers/api/databases.php
Sets minimum number of operations calculated for a read or write to 1.
> chore: set min operations to 1 for reads and writes

- app/controllers/api/teams.php
- tests/e2e/Services/Teams/TeamsBase.php
Fixes an issue where an organization owner could accidentally change their own role, resulting in limited access. This PR ensures at least one owner remains to prevent accidental privilege loss.
Manual.
N/A.
> Restrict role change for sole org owner

- app/init/resources.php
Initialises cache using `telemetry` in resource.php.
Allows simple overriding of `telemetry` resource in cloud.
> feat: cache telemetry

- src/Appwrite/Migration/Version/V21.php
Between version 1.6.0 and 1.6.1, the migrations collection was updated to include a destination attribute and the databases collection was updated to include an originalId attribute. However, the upgrade migration was not updated to create these attributes.
This PR updates the migration to create the missing attributes.
Fixes https://github.com/appwrite/appwrite/issues/9626
Successfully ran the migration:
Successfully ran migration:
- https://github.com/appwrite/appwrite/issues/9626
> Fix migrations

- src/Appwrite/Utopia/Response/Model/Migration.php
`utopia-php/migration` doesn't log the reports for documents, but for checking the status of the migration and accessing the database and collection ids, we need the `resourceId` in the response modal.
Manual.
* #9622
> Add `resourceId`

- app/controllers/api/account.php
Ensure that all 4XX errors redirect to the failure URL
> fix: ensure all 4xx errors in OAuth redirect lead to the failure URL

- app/config/variables.php
- app/controllers/api/functions.php
- src/Appwrite/Functions/Validator/RuntimeSpecification.php
Prior versions of Appwrite treated 0 as unlimited for _APP_FUNCTIONS_CPUS and _APP_FUNCTIONS_MEMORY. As such, this PR updates the specification validator and the list specifications endpoint to also treat the default 0 value as unlimited, allowing any specification.
Manually tested spinning up Appwrite with 0 for _APP_FUNCTIONS_CPUS and _APP_FUNCTIONS_MEMORY and confirmed list specifications showed all the specs:
None
> fix(functions): treat 0 as unlimited for CPUs and memory

- app/http.php
Swoole `dispatch_func` gets called multiple times during a request lifecycle:
* on connection establish, with the initial HTTP request data (up to first 8k bytes of request)
* on connection close, without request data
The underlying TCP connection is shared between all Swoole processes and it's not guaranteed that the `dispatch_func` is called on the same process all the time.
The previous implementation returned a random workerId when there was no data as part of the request. This happens during connection close phase. Debugging the trace here showed the `dispatch_func` getting invoked over and over again. This caused really high CPU load.
It seems Swoole expects the same workerId during connection close that was initially assigned during the connection establish phase. This means we …
> feat(dispatch): add contextual dispatch logic

- app/controllers/api/teams.php
- tests/e2e/Services/Teams/TeamsConsoleClientTest.php
If a user is an `Owner` in more than one org, the logic still allowed downgrade. This PR adds a `teamInternalId` to Query to prevent that case.
Manual.
N/A.
> Fix owner role downgrade

- app/config/storage/inputs.php
- app/config/storage/outputs.php
Processing a gif file can consume large amounts of memory causing the container to crash.
As a safety precaution, don't output to gif either. Any attempt to output to gif will result in an error.
Tests should pass
Manually tested output of png to gif:
Manually tested output of gif:
Reference for high memory usage of gifs:
* https://github.com/ImageMagick/ImageMagick/issues/3418
> fix(storage): do not preview gif input/output

- app/config/variables.php
Without this, API calls to Appwrite can result in rule_not_found errors.
None
None
> fix: add _APP_DOMAIN_SITES variables.php so the env is initialized

- app/controllers/api/storage.php
Before this fix it was possible to execute `curl -vv --output /dev/null -H 'Range: bytes=0-4607000000' 'http://localhost:8080/v1/storage/buckets/682d919f000890038797/files/682d922900365078d7dc/download?project=682d919a0034fafe31ae&mode=admin'` and get the full file range, skipping the 20MB buffer restriction.
> fix(storage): do not allow full range

- app/controllers/api/account.php
- src/Appwrite/URL/URL.php
- tests/unit/URL/URLTest.php
We switched to using the Redirect class for validating redirect URLs to cover additional cases like react native expo scheme, but we missed this validation.
Before the change, we would get an error for the success param:
After we don't see the error on the success param:
And working login using android development build:
https://github.com/user-attachments/assets/f7b7fe41-a80f-4ff7-87bf-c36d7e1fc5e1
- https://github.com/appwrite/appwrite/pull/9650
- https://github.com/appwrite/appwrite/pull/10107
> fix: success validation in oauth2 redirect

- app/controllers/api/account.php
1. handle non-standard ports if the request came in on a non-standard port
2. use the _APP_CONSOLE_DOMAIN env var to handle cases where the Console domain may not be the endpoint domain such as on Appwrite Cloud
3. use the _APP_OPTIONS_FORCE_HTTPS env var to determine the protocol to be consistent with the rest of the codebase
Fixes https://github.com/appwrite/appwrite/issues/2365
Manually tested:
Similar fix:
- https://github.com/appwrite/appwrite/pull/9999
Related issues:
- https://github.com/appwrite/appwrite/issues/2365
> fix: update OAuth2 redirect URLs

- src/Appwrite/Platform/Modules/Functions/Workers/Builds.php
Ensure failed git actions don't fail the whole deployment
It's almost impossible to simulate an organic flow, so did a manual test by throwing an ad-hoc exception in `runGitAction` function and ensured warning logs are added + deployment continues.
> Suppress git-action exception in deployment worker

- app/controllers/general.php
This PR updates the domain validation logic to properly handle CNAME record configurations:
- Changed: Use _APP_CONSOLE_DOMAIN instead of _APP_DOMAIN for console domain validation
Fixed: Domain mismatch issues when using CNAME records that redirect to the configured domain
- Problem: Previously, when using a CNAME record to redirect to a domain, the hostname validation would fail because the actual hostname didn't match the configured _APP_DOMAIN value.
- Solution: The updated validation logic now correctly handles scenarios where the request hostname differs from the configured domain due to CNAME redirects, ensuring proper routing for both robots.phtml and humans.phtml templates.
> fix: 500 errors on robots and humans txt files

- app/controllers/api/avatars.php
many sites like those protected by cloudflare will not let you make request to them, leading to url failed to parse errors. in those cases we should fallback to `favicon.ico` fetch instead of directly giving error.
> fix: favicons endpoint to fallback to ico instead of throwing error

- src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Logs/XList.php
> Fix: wrong resource path for audits

- app/config/specs/open-api3-1.7.x-client.json
- app/config/specs/open-api3-1.7.x-console.json
- app/config/specs/open-api3-1.7.x-server.json
- app/config/specs/open-api3-latest-client.json
- app/config/specs/open-api3-latest-console.json
- app/config/specs/open-api3-latest-server.json
- app/config/specs/swagger2-1.7.x-client.json
- app/config/specs/swagger2-1.7.x-console.json
- app/config/specs/swagger2-1.7.x-server.json
- app/config/specs/swagger2-latest-client.json
- app/config/specs/swagger2-latest-console.json
- app/config/specs/swagger2-latest-server.json
- src/Appwrite/SDK/Specification/Format/OpenAPI3.php
- src/Appwrite/SDK/Specification/Format/Swagger2.php
- src/Appwrite/Utopia/Response/Model.php
- src/Appwrite/Utopia/Response/Model/Document.php
currently the sdks given an error when trying to pass in entire documents since those contain readonly attributes: sequence, databaseId and collectionId.
we need to filter them out before making the request.
why not just not allow them?
we need to allow them in sdks so the DX is easy to just update a `Document` object and pass the entire object to updateDocument method
> chore: add readonly param to sequence, databaseId and collectionId

- app/config/templates/function.php
Add native sign in with Apple function to list of function templates
Locally setup console and test
- https://github.com/appwrite/templates/pull/332
> Add native sign in with Apple function template

- app/controllers/general.php
- composer.lock
- src/Appwrite/Platform/Modules/Functions/Http/Executions/Create.php
- src/Appwrite/Platform/Workers/Functions.php
Ensures dynamic api keys work woth a bit of leeway, useful when timeouts are set to be very short, like 5 seconds, but cold-starts could take some of that time
existing tests should pass
x
> Feat: Increase dynamic API key expiration

- app/controllers/general.php
new warning:
```
Route /v1/databases/:databaseId/collections/:collectionId/documents is deprecated since 1.8.0. Please use `tablesDB.listRows` instead. See: https://appwrite.io/docs/references/cloud/server-rest/tablesDB#listRows
```
> chore: remove sdk deprecation warnings

- src/Appwrite/Platform/Workers/Audits.php
> Check audits logs

- app/controllers/api/account.php
Piroritize identity check in oauth flow above finding existing user based on user email.
This ensures oauth always uses identity first, which is correct behaviour in case of collision.
This fixes specific oauth flows, and should not break any existing ones.
---
If there is user A with email A but identity email B, and user with email B, such GitHub sign-in will always end up with failure:
https://github.com/user-attachments/assets/c337dd7e-6648-4e57-9a39-ba37b0c0a753
This PR fixes it, here is stage with fix:
https://github.com/user-attachments/assets/45da967f-1e67-44a6-983e-51c27c44b84b
Test on stage 
x
> Fix: oauth identity check

- src/Appwrite/Event/Certificate.php
- src/Appwrite/Platform/Workers/Certificates.php
Allows job to override validation hostname, useful for cross-region proxying of certificate jobs
staging env
x
> Feat: add certificate valdiation override

- src/Appwrite/Platform/Modules/Databases/Http/Databases/Usage/Get.php
In this PR, we are fixing the incorrect env vars responsible for displaying the incorrect metrics 
- METRIC_DATABASES_OPERATIONS_WRITES --> METRIC_DATABASE_ID_OPERATIONS_WRITES
- METRIC_DATABASES_OPERATIONS_READS --> METRIC_DATABASE_ID_OPERATIONS_READS
- https://linear.app/appwrite/issue/SUC-1668/usage-metrics-anomaly-on-database
> SUC-1668 fix:database usage metrics 

- app/init/database/filters.php
> Sub query variables order by

- src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Logs/XList.php
- src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Logs/XList.php
Because we initially planned Grids, this was missed during TablesDB migration!
Reference -
1. https://github.com/appwrite/appwrite/blob/1.8.x/src/Appwrite/Platform/Modules/Databases/Http/TablesDB/Tables/Create.php#L37
2. https://github.com/appwrite/appwrite/blob/1.8.x/src/Appwrite/Platform/Modules/Databases/Http/TablesDB/Tables/Rows/Create.php#L47
Manual.
Before -
After -
N/A.
> Fix activities

- src/Appwrite/Event/Event.php
- tests/e2e/Services/Realtime/RealtimeCustomClientTest.php
-> Issue
Related documents are present in the realtime payload and without permissions anyone can view the document
-> Solution
`$sensitive` wasn't getting copied to the realtime queue as it was missing in the `from` method and realtime worker skipping the keys
> Bug fix -> related data in realtime payload

- src/Appwrite/Messaging/Adapter/Realtime.php
- tests/e2e/Services/Realtime/RealtimeCustomClientTest.php
Issue -> Depending on namespace either tableid or collection id is included in the realtime channel but all 6 channels are present
Current -> Adding both ids
> added both collection and table id in the realtime

- app/config/errors.php
- app/controllers/api/account.php
- tests/e2e/Services/Account/AccountCustomClientTest.php
Task: https://linear.app/appwrite/issue/SER-378/code-quality-setrecipient-argument-1-must-be-of-type-string-null-given
> Throw error when email is not available for account verification

- app/config/platforms.php
- docs/examples/1.8.x/client-rest/examples/account/create-email-verification.md
- docs/examples/1.8.x/client-rest/examples/account/create-phone-verification.md
- docs/examples/1.8.x/client-rest/examples/account/create-verification.md
- docs/examples/1.8.x/client-rest/examples/account/update-email-verification.md
- docs/examples/1.8.x/client-rest/examples/account/update-phone-verification.md
- docs/examples/1.8.x/client-rest/examples/account/update-verification.md
- docs/examples/1.8.x/server-rest/examples/account/create-email-verification.md
- docs/examples/1.8.x/server-rest/examples/account/create-phone-verification.md
- docs/examples/1.8.x/server-rest/examples/account/create-verification.md
- docs/examples/1.8.x/server-rest/examples/account/update-email-verification.md
- docs/examples/1.8.x/server-rest/examples/account/update-phone-verification.md
- docs/examples/1.8.x/server-rest/examples/account/update-verification.md
- docs/sdks/android/CHANGELOG.md
- docs/sdks/apple/CHANGELOG.md
- docs/sdks/cli/CHANGELOG.md
- docs/sdks/dart/CHANGELOG.md
- docs/sdks/dotnet/CHANGELOG.md
- docs/sdks/flutter/CHANGELOG.md
- docs/sdks/go/CHANGELOG.md
- docs/sdks/kotlin/CHANGELOG.md
- docs/sdks/nodejs/CHANGELOG.md
- docs/sdks/php/CHANGELOG.md
- docs/sdks/python/CHANGELOG.md
- docs/sdks/react-native/CHANGELOG.md
- docs/sdks/ruby/CHANGELOG.md
- docs/sdks/swift/CHANGELOG.md
- docs/sdks/web/CHANGELOG.md
- src/Appwrite/Platform/Tasks/SDKs.php
This PR adds minor version releases for all client and server SDKs to deprecate the `createVerification` method in the Account service and introduce the new `createEmailVerification` method as its replacement.
- Android: 11.0.0 → 11.1.0
- Web: 21.0.0 → 21.1.0
- Flutter: 20.0.0 → 20.1.0
- Apple: 13.0.0 → 13.1.0
- React Native: 0.15.0 → 0.16.0
- Node.js: 20.0.0 → 20.1.0
- PHP: 17.2.0 → 17.3.0
- Python: 13.2.0 → 13.3.0
- Ruby: 19.0.0 → 19.1.0
- Go: 0.13.0 → 0.14.0
- .NET: 0.19.0 → 0.20.0
- Dart: 19.0.0 → 19.1.0
- Kotlin: 12.0.0 → 12.1.0
- Swift: 13.0.0 → 13.1.0
- CLI: 10.0.1 → 10.1.0
Each SDK changelog now includes:
- Deprecate `createVerification` method in `Account` service
- Add `createEmailVerification` method in `Account` service
- `app/config/platforms.php` - Updated all SDK versions
- …
> Add minor releases for all SDKs - deprecate createVerification, add createEmailVerification
